<!-- START of: finna - reservationlist/reservationlist-navi.phtml -->
<?php
  $currentLimit = 20; // default limit for favorites
  if (isset($this->results)) {
     $limitList = $this->results->getParams()->getLimitList();
     foreach ($limitList as $limitVal => $limitData) {
        if ($limitData['selected']) {
          $currentLimit = $limitVal;
          break;
        }
     }
  }
  $lists = array_column($lists, 'list_entity');

  $side = $this->config()->offcanvasSide();
?>
<ul class="dropdown-menu subtabs collapse show" role="presentation">
  <li class="mobile-navigation-header-container visible-xs visible-sm">
    <h1 class="mobile-navigation-header"><?=$this->transEsc('ReservationList::All hold requests')?></h1>
    <span class="visible-xs visible-sm close-offcanvas">
      <a class="close-offcanvas-btn" href="#" data-toggle="vufind-offcanvas" role="button">
        <?='left' === $side ? $this->icon($this->layout()->rtl ? 'offcanvas-hide-left' : 'offcanvas-hide-right') : ''?>
        <span class="btn-link__label"><?=$this->transEsc('navigate_back') ?></span>
        <?='right' === $side ? $this->icon($this->layout()->rtl ? 'offcanvas-hide-right' : 'offcanvas-hide-left') : ''?>
      </a>
    </span>
  </li>
  <?php $active = empty($activeId); ?>
  <li>
    <a class="dropdown-item<?=$active ? ' active' : ''?>" role="menuitem" href="<?= $active ? '#' : $this->url('reservationlist-displaylists') ?>" aria-current="<?=$active ? 'page' : 'false'?>"><?= $this->transEsc('ReservationList::All Lists') ?></a>
  </li>
  <?php foreach ($lists as $list): ?>
    <?php $active = ($list->getId() === $activeId); ?>
    <li role="none" class="favorites-menulist-item">
      <a role="menuitem" href="<?= $active ? '#' : $this->url('reservationlist-displaylist', ['listId' => $list->getId()])?>?limit=<?=$currentLimit;?>" class="dropdown-item<?=$list && $active ? ' active' : ''?>" aria-current="<?=$active ? 'page' : 'false' ?>">
        <div class="favorite-list-holder">
          <div class="float-start favorite-list-title"><?=$this->escapeHtml($list->getTitle())?></div><?php if ($list->getOrdered()): ?><div>(<?= $this->transEsc('ReservationList::Ordered')?>)</div><?php endif; ?>
        </div>
      </a>
    </li>
  <?php endforeach; ?>
</ul>
<!-- END of: finna - reservationlist/reservationlist-navi.phtml -->
