<!-- START of: finna - myresearch/bulk-action-buttons.phtml -->
<?php if (isset($list)): ?>
  <input type="hidden" name="listID" value="<?=$this->escapeHtmlAttr($list->id)?>">
  <input type="hidden" name="listName" value="<?=$this->escapeHtmlAttr($list->title)?>">
  <input type="hidden" name="listDescription" value="<?=$this->escapeHtmlAttr($list->description)?>">
<?php endif; ?>
<?php $user = $this->auth()->isLoggedIn(); ?>
<div class="bulk-action-buttons-row hidden-print">
  <div class="bulkActionButtons bulk-action-buttons-col">
    <div class="checkboxFilter mylist-select-all">
      <div class="checkbox">
        <label>
          <input type="checkbox" class="checkbox-select-all" name="selectAll" id="<?=$this->idPrefix?>addFormCheckboxSelectAll"<?php if($this->formAttr):?> form="<?=$this->escapeHtmlAttr($this->formAttr) ?>"<?php endif; ?>>
        </label>
      </div>
    </div>
    <div class="mylist-functions btn-group">
      <span class="sr-only"><?=$this->transEsc('bulk_noitems_advice')?></span>
      <button id="button_email" class="btn btn-primary" type="submit" name="email" value="<?=$this->transEscAttr('Email')?>" title="<?=$this->transEscAttr('bookbag_email_selected')?>" disabled<?php if($this->formAttr):?> form="<?=$this->escapeHtmlAttr($this->formAttr) ?>"<?php endif; ?>><?=$this->transEsc('Email')?></button>
      <?php $exportOptions = $this->export()->getActiveFormats('bulk');
      if (count($exportOptions) > 0): ?>
        <button class="btn btn-primary" type="submit" name="export" value="<?=$this->transEscAttr('Export')?>" title="<?=$this->transEscAttr('bookbag_export_selected')?>" disabled<?php if($this->formAttr):?> form="<?=$this->escapeHtmlAttr($this->formAttr) ?>"<?php endif; ?>><?=$this->transEsc('Export')?></button>
      <?php endif; ?>
      <?php if ((null !== $this->list && $this->list->editAllowed($user)) || (null === $this->list && $user)): ?>
        <button class="btn btn-primary" id="<?=$this->idPrefix?>delete_list_items_<?=null !== $this->list ? $this->escapeHtmlAttr($this->list->id) : ''?>" type="submit" name="delete" value="<?=$this->transEscAttr('Delete')?>" title="<?=$this->transEsc('delete_selected')?>" disabled<?php if($this->formAttr):?> form="<?=$this->escapeHtmlAttr($this->formAttr) ?>"<?php endif; ?>><?=$this->transEsc('Delete')?></button>
      <?php endif; ?>
        <?php if ($lists): ?>
        <select id="add-to-list" class="btn btn-primary form-control" autocomplete="off" aria-label="<?= $this->translate('Add to List'); ?>" disabled<?php if($this->formAttr):?> form="<?=$this->escapeHtmlAttr($this->formAttr) ?>"<?php endif; ?>>
          <option value=""><?= $this->translate('Add to List'); ?>&hellip;</option>
          <?php foreach ($lists as $l): ?>
            <?php if ($list && $list->id == $l->id) {
              continue;
            } ?>
            <?php $title = $this->truncate($l->title, 20) ?>
            <option value="<?=$this->escapeHtmlAttr($l->id) ?>"><?=$this->escapeHtml($title) ?></option>
          <?php endforeach; ?>
        </select>
        <span id="add-to-list-spinner" class="hidden"><?=$this->icon('spinner') ?></span>
      <?php endif; ?>
      <?php if ($this->cart()->isActive()): ?>
        <button class="btn btn-primary" id="<?=$this->idPrefix?>updateCart" type="submit" name="add" title="<?=$this->transEsc('Add to Book Bag')?>" disabled<?php if($this->formAttr):?> form="<?=$this->escapeHtmlAttr($this->formAttr) ?>"<?php endif; ?>><?=$this->transEsc('Bag') ?></button>
      <?php endif; ?>
    </div>
  </div>
  <div class="clearfix"></div>
</div>
<!-- END of: finna - myresearch/bulk-action-buttons.phtml -->
