<!-- START of: finna - myresearch/fines.phtml -->
<?php
    // Set up page title:
    $this->headTitle($this->translate('My Fines'));

    // Set up breadcrumbs:
    $this->layout()->breadcrumbs = '<li><a href="' . $this->url('myresearch-home') . '">' . $this->transEsc('Your Account') . '</a></li> <li class="active">' . $this->transEsc('Fines') . '</li>';

    $user = $this->auth()->isLoggedIn();

    $totalDue = 0;
    if (!empty($this->fines)) {
      $hideTitle = true;
      $hideCheckout = true;
      $hideDueDate = true;
      $hideFineCreationDate = true;
      $hideAmount = true;
      foreach ($this->fines as $fine) {
          if (!empty($fine['title'])) {
              $hideTitle = false;
          }
          if (!empty($fine['checkout'])) {
              $hideCheckout = false;
          }
          if (!empty($fine['duedate'])) {
              $hideDueDate = false;
          }
          if (!empty($fine['createdate'])) {
              $hideFineCreationDate = false;
          }
          if (!empty($fine['amount']) && $fine['amount'] !== $fine['balance']) {
              $hideAmount = false;
          }

          if (isset($fine['balance'])) {
            $totalDue += $fine['balance'];
          }
      }
    }
    $currencyTemplate = $this->safeMoneyFormat(11.22);
?>
<!-- Leftside navigationbar -->
<?= $this->context($this)->renderInContext('myresearch/menu.phtml', ['active' => 'fines']); ?>

<div class="<?=$this->layoutClass('mainbody-myresearch')?>">
  <div class="my-research-content">
    <?php if ($user): ?>
      <?php if (!empty($this->registerPayment)): ?>
        <div class="alert alert-info">
          <span class="register-payment-spinner"><?=$this->icon('spinner') ?> <?=$this->translate('Registering Payment');?></span>
          <div id="online-payment-status" class="info hide"></div>
        </div>
      <?php endif; ?>
    <?php endif; ?>
    <?php if (!$this->translationEmpty('fines_instructions_html')): ?><p class="no-content-message"><?=$this->translate('fines_instructions_html')?></p><?php endif; ?>
    <div class="fines-info-area">
      <div class="useraccount-row">
        <?=$this->context($this)->renderInContext('librarycards/selectcard.phtml', ['user' => $user, 'label' => 'Library Card'])?>
      </div>
      <div class="useraccount-header">
        <h2><?=$this->transEsc('Your Fines') . ' (' . count($this->fines ?? []) . ')'?></h2>
      </div>
    </div>
    <?=$this->flashmessages()?>
    <?=$this->partial('myresearch/borrowing-block.phtml', ['blocks' => $this->blocks]); ?>
    <div class="fines-info-area">
      <?php if (!empty($this->lastTransaction)): ?>
        <div class="last-transaction-information">
          <div>
            <?=$this->transEsc('Payment::Last Paid')?>:
            <span class="amount"><?=$this->safeMoneyFormat($this->lastTransaction->amount / 100.00)?></span>
            <?=$this->dateTime()->convertToDisplayDateAndTime('Y-m-d H:i:s', $this->lastTransaction->paid)?>
          </div>
          <div class="text-right">
            <a href="?transactionReport=true" class="btn btn-sm btn-primary"><?=$this->transEsc('Payment::download_transaction_breakdown_pdf')?></a>
          </div>
        </div>
      <?php endif; ?>
      <div id="online_payment_total_due" data-raw="<?=$this->escapeHtmlAttr($totalDue)?>">
        <p>
          <?=$this->transEsc('Total Balance Due')?> (<?=count($this->fines ?? []);?>):
          <span class="amount"><?=$this->safeMoneyFormat($totalDue / 100.00) ?></span>
        </p>
      </div>
      <?php if ($this->onlinePayment && $this->onlinePaymentEnabled): ?>
        <div class="online-payment-info">
          <div id="online_payment_payable">
            <p>
              <?=$this->transEsc('online_payment_payable_online'); ?> (<?=$payableOnlineCnt ?>):
              <span class="amount"><?=$this->safeMoneyFormat($payableOnline / 100.00);?></span>
            </p>
          </div>
          <div id="online_payment_minimum_payment" data-raw="<?=$this->escapeHtmlAttr($minimumFee)?>" class="alert alert-warning hidden">
            <?=$this->transEsc('online_payment_minimum_fee'); ?>:
            <span class="amount"><?=$this->safeMoneyFormat($minimumFee / 100.00)?></span>
          </div>
        </div>
        <?php if (!empty($transactionFee)): ?>
          <div id="online_payment_transaction_fee" data-raw="<?=$this->escapeHtmlAttr($transactionFee)?>">
            <p>
              <?=$this->transEsc('online_payment_transaction_fee'); ?>:
              <span class="amount"><?=$this->safeMoneyFormat($transactionFee / 100.00);?></span>
            </p>
          </div>
        <?php endif; ?>
        <?php if ($this->selectFees): ?>
          <div id="online_payment_remaining_after">
            <p>
              <?=$this->transEsc('online_payment_remaining_after'); ?>:
              <span class="amount" data-template="<?=$this->escapeHtmlAttr($currencyTemplate)?>">
                <?=$this->safeMoneyFormat(($this->selectFees ? $totalDue : $totalDue - $payableOnline) / 100)?>
              </span>
            </p>
          </div>
        <?php endif; ?>
        <?php if ($this->startedTransaction): ?>
          <div class="alert alert-danger">
            <?=$this->transEsc('online_payment_in_progress_warning', ['%%startDateTime%%' => $this->dateTime()->convertToDisplayDateAndTime('Y-m-d H:i:s', $this->startedTransaction->created)]); ?>
          </div>
        <?php endif; ?>
      <?php endif; ?>
    </div>
    <?php if ($this->onlinePayment): ?>
      <?php if ($this->onlinePaymentEnabled): ?>
        <form id="online_payment_form" class="online-payment-form" action="<?=$this->url('myresearch-fines')?>" method="post" data-lightbox data-clear-account-cache="fines" data-disable-on-submit>
          <input name="transactionId" type="hidden" value="<?=$this->escapeHtmlAttr($this->transactionId)?>">
          <?php if (!$this->selectFees): ?>
            <div class="fines-info-area payment-row">
              <input type="submit" name="pay" class="btn btn-primary btn-lg" value="<?=$this->transEscAttr('online_payment_go_to_pay', ['%%amount%%' => $this->safeMoneyFormat(($payableOnline + ($transactionFee ?? 0)) / 100.00)])?>">
            </div>
          <?php endif; ?>
      <?php elseif (!empty($this->nonPayableReason) && !empty($this->fines)): ?>
        <div class="fines-info-area">
          <p><?=$this->transEsc($this->nonPayableReason); ?><?=$this->nonPayableReason == 'online_payment_minimum_fee' ? (': <span class="amount">' . $this->safeMoneyFormat($this->minimumFee / 100.00)) . '</span>' : '';?></p>
        </div>
      <?php endif; ?>
    <?php endif; ?>
    <?php if (isset($this->noSupport)): ?>
      <?php if ($user->getLibraryCards()->count() > 0): ?>
        <div class="support-notice">
          <p><?=$this->transEsc('no_ils_support_description') ?></p>
        </div>
      <?php endif; ?>
    <?php else: ?>
      <?php if ($template = $this->content()->findTemplateForLng('content/Additions/fines-pre-list')): ?>
        <div class="fines-pre-list"><?=$this->render($template)?></div>
      <?php endif; ?>
      <?php if (empty($this->fines)): ?>
        <h3><?=$this->transEsc('You do not have any fines')?></h3>
      <?php else: ?>
        <?php if ($this->onlinePaymentEnabled && $this->selectFees): ?>
          <input type="hidden" value="<?=$this->escapeHtmlAttr($this->auth()->getManager()->getCsrfHash())?>" name="csrf">
          <div class="myresearch-table online-payment" aria-label="<?=$this->transEscAttr('Actions');?>">
            <div class="toolbar">
              <div class="text-left checkbox-col">
                <div class="checkboxFilter mylist-select-all">
                  <div class="checkbox">
                    <label>
                      <input type="checkbox" name="selectAll" class="checkbox-select-all">
                      <span class="selected"></span>
                    </label>
                  </div>
                </div>
              </div>
              <div class="payment-row fines-info-area">
                <span id="online_payment_selected_sr" class="sr-only" data-template="<?=$this->transEscAttr('online_payment_selected_to_pay') . ' ' . $this->transEscAttr($currencyTemplate)?>">
                  <?=$this->transEscAttr('online_payment_selected_to_pay') . ' ' . $this->safeMoneyFormat(0)?>
                </span>
                <input type="submit" id="pay_selected" name="pay" class="btn btn-primary" value="<?=$this->transEscAttr('online_payment_go_to_pay', ['%%amount%%' => ''])?>" data-template="<?=$this->transEscAttr('online_payment_go_to_pay', ['%%amount%%' => $currencyTemplate])?>" disabled>
              </div>
            </div>
          </div>
        <?php endif; ?>
        <div class="table-responsive">
          <table class="table table-striped useraccount-table<?=$this->onlinePayment ? ' online-payment' : ''?>">
            <tr class="headers">
              <?php if ($this->onlinePaymentEnabled && $this->selectFees): ?>
                <th class="user-account-table-select"></th>
              <?php endif; ?>
              <th class="user-account-table-title <?php if ($hideTitle): ?> hidden<?php endif; ?>"><?=$this->transEsc('Title')?></th>
              <th class="<?= $hideCheckout ? 'hidden' : 'hidden-xs' ?>">
                <?=$this->transEsc('fine_checkout_date')?>
              </th>
              <th class="<?= $hideDueDate ? 'hidden' : '' ?>">
                <?=$this->transEsc('Due Date')?>
              </th>
              <th>
                <?=$this->transEsc('fine_description')?>
              </th>
              <th class="<?= $hideFineCreationDate ? 'hidden' : 'hidden-xs' ?>">
                <?=$this->transEsc('fine_creation_date')?>
              </th>
              <th class="<?= $hideAmount ? 'hidden' : 'hidden-xs' ?>">
                <?=$this->transEsc('Fee')?>
              </th>
              <th class="balance"><?=$this->transEsc('Balance')?></th>
            </tr>
            <?php foreach ($this->fines as $record): ?>
            <?php
              $showNonPayable = $this->onlinePayment && !$record['payableOnline'];
              $fine = null;
              if (isset($record['fine'])) {
                $fine = $record['fine'];
                if (!$this->translationEmpty("fine_status_$fine")) {
                  $fine = "fine_status_$fine";
                } elseif (!$this->translationEmpty("status_$fine")) {
                  // Fallback to item status translations for backwards-compatibility
                  $fine = "status_$fine";
                }
              }
            ?>
            <tr>
              <?php if ($this->onlinePaymentEnabled && $this->selectFees): ?>
                <td class="user-account-table-select">
                  <?php if ($record['payableOnline']): ?>
                    <div class="checkboxFilter">
                        <label>
                          <span class="sr-only">
                            <?=$this->transEsc('Select');?>
                            <?=$this->escapeHtml(trim($record['title'] ?? '', '/: '))?>
                            <?=isset($fine) ? ('(' . $this->transEsc($fine) . ')') : ''?>
                            <?=$this->safeMoneyFormat($record['balance'] / 100.00)?>
                          </span>
                          <input class="checkbox-select-item" type="checkbox" name="selectedIDS[]" value="<?=$this->escapeHtmlAttr($record['fine_id'])?>" data-amount="<?=$this->escapeHtmlAttr($record['balance'])?>">
                        </label>
                    </div>
                  <?php endif; ?>
                </td>
              <?php endif; ?>

              <td class="user-account-table-title<?php if ($hideTitle): ?> hidden<?php endif; ?>">
                <?php if (empty($record['title'])): ?>
                  <?=$this->transEsc('not_applicable')?>
                <?php elseif (!isset($record['driver']) || !is_object($record['driver'])): ?>
                  <?=$this->escapeHtml(trim($record['title'], '/: '))?>
                <?php else: ?>
                  <a href="<?=$this->escapeHtmlAttr($this->recordLinker()->getUrl($record['driver']))?>"><?=$this->escapeHtml(trim($record['title'], '/: '))?></a>
                <?php endif; ?>
              <td class="<?= $hideCheckout ? 'hidden' : 'hidden-xs' ?>">
                <?=isset($record['checkout']) ? $this->escapeHtml($record['checkout']) : ''?>
              </td>
              <td class="<?=$hideDueDate ? 'hidden' : '' ?>">
                <?=isset($record['duedate']) ? $this->escapeHtml($record['duedate']) : ''?>
              </td>
              <td><?=isset($fine) ? $this->transEsc($fine) : ''?></td>
              <td class="<?=$hideFineCreationDate ? 'hidden' : 'hidden-xs' ?>">
                <?=isset($record['createdate']) ? $this->escapeHtml($record['createdate']) : ''?>
              </td>
              <td class="<?=$hideAmount ? 'hidden' : 'hidden-xs' ?>">
                <?=isset($record['amount']) ? $this->safeMoneyFormat($record['amount'] / 100.00) : ''?>
              </td>
              <td class="balance">
                <?php if ($showNonPayable): ?>
                  <span class="online-payment-nonpayable">
                <?php endif; ?>
                <?=isset($record['balance']) ? $this->safeMoneyFormat($record['balance'] / 100.00) : ''?>
                <?php if ($showNonPayable): ?>
                  </span>
                <?php endif; ?>
                <?php if ($showNonPayable): ?>
                  <div class="online-payment-remark"><?=$this->translate('online_payment_nonpayable_fees');?></div>
                <?php endif; ?>
              </td>
            </tr>
            <?php endforeach; ?>
          </table>
        </div>
        <?php if ($this->onlinePaymentEnabled): ?>
          </form>
        <?php endif; ?>
        <div>
          <?php if ($this->onlinePayment): ?>
            <?php if ($template = $this->content()->findTemplateForLng('content/Additions/online-payment')): ?>
              <div class="online-payment-note"><?=$this->render($template)?></div>
            <?php endif; ?>
          <?php endif; ?>
          <?php if ($template = $this->content()->findTemplateForLng('content/Additions/fines-post-list')): ?>
            <div class="fines-post-list"><?=$this->render($template)?></div>
          <?php endif; ?>
        </div>
      <?php endif; ?>
    <?php endif; ?>
  </div>
</div>
<?php
  if (!empty($this->registerPayment)) {
    $paramsJson = json_encode($registerPaymentParams);
    $js = <<<JS
        $(document).ready(function() {
          finna.onlinePayment.registerPayment($paramsJson);
        });
        JS;
    echo $this->inlineScript(\Laminas\View\Helper\HeadScript::SCRIPT, $js, 'SET');
  }
?>

<?=$this->render('myresearch/notify-account-status.phtml', ['method' => 'fines', 'accountStatus' => $this->accountStatus]); ?>
<!-- END of: finna - myresearch/fines.phtml -->
