<!-- START of: finna - myresearch/menu.phtml -->
<?php
    $capabilityParams = [];
    $user = $this->auth()->isLoggedIn();
    $patron = $user ? $this->auth()->getILSPatron() : false;
    $capabilityParams = $patron ? ['patron' => $patron] : [];
    $showLibraryTabs = $this->ils()->loginAvailable();
    $ilsOffline = 'ils-none' === $this->ils()->getOfflineMode();
    $r2SearchEnabled = $this->R2()->isAvailable();
    $listOpen = $this->active == 'favorites' || substr($this->active, 0, 4) == 'list';
    $activeToLower = strtolower($this->active ?? '');
    //Get the data for vertical menu to show lists on correct site
    if ($listOpen) {
      $list = $this->results->getListObject();
      $listParams = [
        'activeId' => $list['id'] ?? null,
        'lists' => $user ? $user->getLists() : null,
        'results' => $this->results,
        'user' => $user,
      ];
    }

    $menuListItems = [];
    if ($showLibraryTabs && !$ilsOffline) {
      $menuListItems = [
        'checkedout' => [
          'url' => 'myresearch-checkedout',
          'translation' => 'Checked Out Items',
          'statusKey' => 'checkedout',
        ],
        'historicloans' => [
          'url' => 'checkouts-history',
          'translation' => 'Loan History',
          'show' => $this->ils()->checkCapability('getMyTransactionHistory', $capabilityParams),
        ],
        'holds' => [
          'url' => 'holds-list',
          'translation' => 'Holds and Recalls',
          'statusKey' => 'holds',
        ],
        'storageretrievalrequests' => [
          'url' => 'myresearch-storageretrievalrequests',
          'translation' => 'Storage Retrieval Requests',
          'show' => $this->ils()->checkFunction('StorageRetrievalRequests', $capabilityParams),
          'statusKey' => 'storageretrievalrequests',
        ],
        'illrequests' => [
          'url' => 'myresearch-illrequests',
          'translation' => 'Interlibrary Loan Requests',
          'show' => $this->ils()->checkFunction('ILLRequests', $capabilityParams),
          'statusKey' => 'illrequests',
        ],
        'fines' => [
          'url' => 'myresearch-fines',
          'translation' => 'Fines',
          'statusKey' => 'fines',
        ],
        'librarycards' => [
          'url' => 'librarycards-home',
          'translation' => 'Library Cards',
          'show' => $user && $user->libraryCardsEnabled(),
        ],
      ];
    }

    $nonLibraryItems = [];
    if ($r2SearchEnabled) {
        $nonLibraryItems['r2-accessrights'] = [
            'url' => 'myresearch-r2accessrights',
            'translation' => 'R2_accessrights_menu_heading',
        ];
    }
    $nonLibraryItems += [
      'profile' => [
        'url' => 'myresearch-profile',
        'translation' => 'Profile',
        'show' => !$ilsOffline && $this->ils()->checkCapability('getMyProfile'),
        'statusKey' => 'profile',
      ],
      'history' => [
        'url' => 'search-history',
        'query' => '?require_login',
        'translation' => 'history_saved_searches',
      ],
      'favorites' => [
        'url' => 'myresearch-favorites',
        'translation' => 'Favorites',
        'show' => $this->userlist()->getMode() !== 'disabled',
      ],
      'logout' => [
        'url' => 'myresearch-logout',
        'translation' => 'Log Out',
        'iconClass' => $this->icon('sign-out', 'pull-right'),
        'desktopOnly' => true,
      ],
    ];

    $menuListItems = array_merge($menuListItems, $nonLibraryItems);

    $desktopList = [
      'r2-accessrights',
      'checkedout',
      'historicloans',
      'holds',
      'storageretrievalrequests',
      'illrequests',
      'fines',
      'librarycards',
      'profile',
      'history',
      'open-list' => [
        'active' => $listOpen,
        'url' => 'myresearch-favorites',
        'translation' => 'Favorites',
        'show' => $this->userlist()->getMode() !== 'disabled',
        'partial' => [
          'url' => 'myresearch/mylist-navi.phtml',
          'wrapperClass' => 'mylist-bar',
          'params' => $listParams ?? [],
        ],
      ],
      'logout',
    ];

    $headerKey = substr($activeToLower, 0, 4) === 'list' ? 'favorites' : $activeToLower;
    $activeMobileTab = $menuListItems[$headerKey]['translation'] ?? 'Your Account';
?>

<div class="mobile-main-tabs visible-xs visible-sm">
  <div class="dropdown useraccount-nav-mobile myresearch-menu" role="menu">
    <div class="dropdown-toggle" data-toggle="dropdown">
      <div class="tab-title">
        <?=$this->transEsc($activeMobileTab)?>
      </div>
      <div class="more hidden-print"><?= $this->transEsc('Your Account') ?><?=$this->icon('menu-open', 'js-toggle-menu') ?></div>
    </div>
    <ul class="dropdown-menu">
      <?php foreach ($menuListItems as $id => $listItem) : ?>
        <?php if (isset($listItem['desktopOnly']) && $listItem['desktopOnly']) {
          continue;
        } ?>
        <?php if (!isset($listItem['show']) || $listItem['show'] !== false): ?>
          <li role="menuitem" class="<?=$id?><?= $activeToLower === $id ? ' active' : ''?>">
            <a href="<?=$this->escapeHtmlAttr($this->url($listItem['url']) . ($listItem['query'] ?? ''))?>" class="list-group-item" <?=$activeToLower === $id ? 'aria-current="page"' : ''?>>
            <?=$this->transEsc($listItem['translation'])?>
              <?php if (!empty($listItem['statusKey'])): ?>
                <span class="<?=$listItem['statusKey']?>-status status hidden"><?=$this->icon('spinner') ?></span>
              <?php endif; ?>
            </a>
          </li>
        <?php endif; ?>
      <?php endforeach; ?>
    </ul>
  </div>
</div>

<ul class="<?=$this->layoutClass('sidebar-myresearch')?> <?= $listOpen ? '' : 'move-list' ?> nav-tabs-personal list-group useraccount-nav nav-tabs finna-movement myresearch-menu account-menu" role="menu">
  <li role="none" class="menu-header hidden-xs hidden-sm">
    <h1>
      <?= $this->transEsc('Your Account') ?>
      <?php if (!$this->translationEmpty('tooltip_myaccount_html')): ?>
        <button class="tooltip-myaccount" data-toggle="tooltip" data-placement="auto" data-html="true" data-original-title="<?= $this->transEsc('tooltip_myaccount_html') ?>"><?=$this->icon('help') ?><span class="sr-only"><?=$this->transEsc('My account tips');?></span></button>
      <?php endif; ?>
    </h1>
  </li>
  <?php foreach ($desktopList as $id => $value) : ?>
  <?php
    $isArray = is_array($value);
    $listItem = $isArray ? $value : $menuListItems[$value] ?? ['show' => false];
    if (isset($listItem['show']) && !$listItem['show']) {
      continue;
    }
    $name = $isArray ? $id : $value;
    $hasPartial = $listItem['partial'] ?? false;
    $showSpinner = $listItem['showSpinner'] ?? false;
  ?>
    <?php if ($hasPartial): ?>
      <li role="none" class="dropdown <?= $listItem['active'] ? ' active' : ''?>">
        <a role="menuitem" href="<?=$this->escapeHtmlAttr($this->url($listItem['url']) . ($listItem['query'] ?? ''))?>" id="<?=$id?>" class="menu-parent sticky-menu hidden-xs hidden-sm list-group-item <?= !$listItem['active'] ? 'collapsed' : '' ?>" aria-haspopup="true" aria-expanded="<?=$listItem['active'] ? 'true' : 'false'?>">
          <?=$this->transEsc($listItem['translation'])?>
          <?php if ($showSpinner) : ?>
            <?=$this->icon('spinner', ['class' => 'hidden']) ?><span class="ajax-error hidden"><small> <?=$this->translate('An error has occurred'); ?></small></span>
          <?php endif; ?>
          <?=$this->icon('collapse-open', 'collapse-icon') ?>
        </a>
        <div class="<?= $value['partial']['wrapperClass'] ?? 'ajax-wrapper'?>">
          <?php if ($listItem['active']): ?>
            <?= $this->partial($value['partial']['url'], $value['partial']['params']); ?>
          <?php endif; ?>
        </div>
      </li>
    <?php else: ?>
      <li role="none" class="hidden-xs hidden-sm <?="menu-$name"?> <?=$activeToLower === $name ? ' active' : ''?>">
        <a role="menuitem" href="<?=$this->escapeHtmlAttr($this->url($listItem['url']) . ($listItem['query'] ?? ''))?>" class="list-group-item" <?=$activeToLower === $name ? 'aria-current="page"' : ''?>>
          <?=$this->transEsc($listItem['translation'])?>
          <?php if (isset($listItem['iconClass'])): ?>
            <?=$listItem['iconClass']?>
          <?php endif; ?>
          <?php if (!empty($listItem['statusKey'])): ?>
            <span class="<?=$listItem['statusKey']?>-status status hidden"><?=$this->icon('spinner') ?></span>
          <?php endif; ?>
        </a>
      </li>
    <?php endif; ?>
  <?php endforeach; ?>
</ul>

<!-- END of: finna - myresearch/menu.phtml -->
