<!-- START of: finna - myresearch/mylist.phtml -->
<?php
  // Grab list object from search results (if applicable):
  $list = $this->results->getListObject();

  // Set up page title:
  $this->headTitle(isset($list) ? $list->title : $this->translate('Favorites'));

  // Set up breadcrumbs:
  $currPage = isset($list) ? 'List' : 'Favorites';
  $this->layout()->breadcrumbs = '<li><a href="' . $this->url('myresearch-home') . '">' . $this->transEsc('Your Account') . '</a></li> <li class="active">' . $this->transEsc($currPage) . '</li>';

  // Load Javascript dependencies into header:
  $this->headScript()->appendFile("check_item_statuses.js");

  // Load Javascript only if list view parameter is NOT full:
  if ($this->params->getOptions()->getListViewOption() != "full") {
    $this->headScript()->appendFile("record.js");
    $this->headScript()->appendFile("embedded_record.js");
  }

  $recordTotal = $this->results->getResultTotal();

  // Convenience variable:
  $account = $this->auth()->getManager();
  $user = $this->auth()->isLoggedIn();

  $lists = $user ? $user->getLists() : null;

  $this->jsTranslations()->addStrings(['add_list_description' => 'Add list description', 'loading' => 'Loading']);
?>

<!-- Leftside navigationbar -->
<?= $this->context($this)->renderInContext("myresearch/menu.phtml", ['active' => isset($list) ? 'list' . $list['id'] : 'favorites']); ?>

<?php foreach ($this->results->getRecommendations('side') as $current): ?>
  <?=$this->recommend($current)?>
<?php endforeach; ?>

<div class="<?=$this->layoutClass('mainbody-myresearch')?>">
  <div class="mylist-error hidden"><?=$this->translate('An error has occurred'); ?></div>
  <?php if (isset($list)): ?>
    <input type="hidden" name="listID" value="<?=$this->escapeHtmlAttr($list->id)?>">
    <input type="hidden" name="listName" value="<?=$this->escapeHtmlAttr($list->title)?>">
  <?php endif; ?>
  <div class="clearfix mylist-header hidden-print">
    <div>
      <?=$this->flashmessages()?>
    </div>
    <div>
      <?php if ($list): ?>
        <div class="useraccount-header">
          <h2 class="list-title"><i class="list-title-edit fa fa-pen" aria-label="<?=$this->transEscAttr('edit')?>"></i><span><?=$this->escapeHtml($list->title)?></span></h2>
        </div>
        <?php if ($list && $user && $list->user_id === $user->id && $list->public): ?>
          <div class="list-public-indicator">
            <strong><i class="fa fa-public"></i> <?=$this->transEsc('public_list_indicator') ?></strong>
          </div>
        <?php endif; ?>
        <?php $markdown = $list ? $this->markdown()->replaceDeprecatedTags($list->description ?? '') : ''; ?>
        <?= $this->component('@@organisms/widgets/finna-md-editable', [
            'attributes' => ['class' => 'list-description'],
            'markdown' => $markdown,
            'html' => $markdown ? $this->markdown()->toHtml($markdown, false) : '',
            'emptyHtml' => $this->translate('Add list description'),
            'preview' => true,
          ]); ?>
        <?php if ($this->usertags()->getListMode() === 'enabled'): ?>
          <?php $listTags = $list->getListTags(); ?>
          <div class="list-tags">
            <div class="tags view-tags">
              <?= $this->partial('mylist-tags.phtml', ['tags' => $listTags, 'editable' => false])?>
            </div>

            <div class="edit-tags">
              <div class="toggle" title="<?=$this->transEscAttr('edit-list-tags')?>">
                <span><?=$this->transEsc('edit-list-tags')?> </span><i aria-hidden="true" class="fa fa-tag" aria-label="<?=$this->transEscAttr('edit-list-tags')?>"></i>
              </div>
              <div class="ui">
                <p class="info"><i aria-hidden="true" class="fa fa-info"></i> <?=$this->transEsc('add-list-tag-note')?></p>
                <form>
                  <fieldset>
                    <legend></legend>
                    <div class="add-new">
                      <input type="text" class="new-tag" name="new-tag" value="" aria-required="true" required aria-label="<?= $this->transEscAttr('list-tags-info')?>" placeholder="<?= $this->transEscAttr('list-tags-info')?>">
                      <button type="submit" class="btn btn-primary "><?=$this->transEsc('Save')?></button>
                      <div><i aria-hidden="true" class="fa fa-spin fa-spinner hide"></i></div>
                    </div>
                    <div class="tags editable">
                      <div class="tag-list">
                        <?= $this->partial('mylist-tags.phtml', ['tags' => $listTags, 'editable' => true])?>
                      </div>
                    </div>
                  </fieldset>
                </form>
              </div>
            </div>
          </div>
        <?php endif ?>
      <?php else: ?>
        <div class="useraccount-header">
          <h2 class="list-title no-edit"><span><?=$this->transEsc("All Favourites")?></span></h2>
        </div>
      <?php endif; ?>
    </div>
  </div>
  <?php if ($template = $this->content()->findTemplateForLng("content/Additions/myresearch-favorites")): ?>
    <div class="myresearch-favorites">
      <?=$this->render($template)?>
    </div>
  <?php endif; ?>
  <div class="mylist-header">
    <?php if ($recordTotal > 0): ?>
      <div class="mylist-controls search-controls">
        <div class="pagination-container">
          <?=$this->paginationControl($this->results->getPaginator(), 'Sliding', 'search/pagination_simple.phtml', ['results' => $this->results])?>
        </div>
        <div class="control-container hidden-print">
          <?php if (isset($list)): ?>
            <a class="btn btn-sm btn-primary btn-sort-order" href="<?=$this->url('sortList', ['id' => $list->id]) ?>" data-backdrop=”static” data-lightbox><span class="fa fa-sort" aria-hidden="true"></span> <span class="hidden-xs"><?=$this->transEsc('Sort manually');?></span></a>
          <?php endif; ?>
          <?=$this->render('search/controls/sort.phtml')?>
          <?=$this->render('search/controls/limit.phtml')?>
        </div>
      </div>
      <div>
        <form class="form" method="post" name="bulkActionForm" action="<?=$this->url('cart-myresearchbulk')?>" data-lightbox data-lightbox-onsubmit="bulkFormHandler">
          <?=$this->context($this)->renderInContext('myresearch/bulk-action-buttons.phtml', ['idPrefix' => '', 'list' => $list ?? null, 'account' => $this->account, 'lists' => $lists])?>
          <?php foreach ($this->results->getResults() as $i => $current): ?>
            <?=$this->record($current)->getListEntry($list, $user)?>
          <?php endforeach; ?>
        </form>
      </div>
    <?php else: ?>
      <div class="useraccount-header">
        <h3><?=$this->transEsc('You do not have any saved resources')?></h3>
      </div>
    <?php endif; ?>
  </div>
  <?php if ($recordTotal > 0): ?>
    <div>
      <div class="text-center">
        <hr>
        <?=$this->paginationControl($this->results->getPaginator(), 'Sliding', 'search/pagination_simple.phtml', ['results' => $this->results])?>
      </div>
    </div>
  <?php endif;?>
</div>
<?php if ($user && $list): ?>
  <form class="pull-left delete-list" action="<?=$this->url('myresearch-deletelist') ?>?listID=<?=urlencode($list->id)?>&confirm=1" method="post">
    <ul class="dropdown-menu">
      <li class="disabled"><a><?=$this->transEsc('confirm_delete_list_text')?></a></li>
      <li class="confirm"><a href="#"><?=$this->transEsc('confirm_dialog_yes') ?></a></li>
      <li class="cancel"><a href="#"><?=$this->transEsc('confirm_dialog_no')?></a></li>
    </ul>
  </form>
<?php endif; ?>
<div class="mylist-mobile mobile-navigation visible-xs visible-sm hidden-print">
  <ul>
    <li class="sidebar-navigation"><i class="fa fa-arrow-up"></i> <?=$this->transEsc('Your Lists')?></li>
  </ul>
</div>

<!-- END of: finna - myresearch/mylist.phtml -->
