<ul>
  <?php foreach ($this->tags as $tag): ?>
    <li class="tag"><span class="text" data-tag="<?=$this->escapeHtmlAttr($tag->tag)?>"><?= $this->escapeHtml($tag->tag) ?></span>
      <?php if ($this->editable): ?>
        <button class="delete-tag" aria-label="<?=$this->transEscAttr('Delete')?>"><?=$this->icon('list-tag-delete') ?></button>
      <?php endif ?>
    </li>
  <?php endforeach ?>
</ul>
