<!-- START of: finna - myresearch/mylist-navi.phtml -->
<?php
  $numOfResources = $user->getNumOfResources();
  $currentLimit = 20; // default limit for favorites
  if (isset($this->results)) {
     $limitList = $this->results->getParams()->getLimitList();
     foreach ($limitList as $limitVal => $limitData) {
        if ($limitData['selected']) {
          $currentLimit = $limitVal;
          break;
        }
     }
  }
?>
<ul class="dropdown-menu subtabs collapse in" role="presentation">
  <li><h1 class="visible-xs visible-sm"><?=$this->icon('sidebar-collapse') ?> <?=$this->transEsc('Your Lists')?></h1></li>
  <li role="none" class="favorites-menulist-item">
    <a role="menuitem" href="<?=$this->url('myresearch-favorites')?>?limit=<?=$currentLimit;?>" class="<?=!$activeId ? ' active' : ''?>" aria-current="<?= !$activeId ? 'page' : 'false' ?>">
      <div class="favorite-list-holder">
        <div class="pull-left favorite-list-title"><?=$this->transEsc('default_list_title')?></div>
        <div class="pull-right">(<?=$numOfResources;?>)</div>
      </div>
    </a>
  </li>
  <?php foreach ($lists as $current): ?>
    <?php $list = $current['list_entity']; ?>
    <?php $active = ($list->getId() === $activeId); ?>
    <li role="none" class="favorites-menulist-item">
      <a role="menuitem" href="<?= $active ? '#' : $this->url('userList', ['id' => $list->getId()])?>?limit=<?=$currentLimit;?>" class="<?=$list && $active ? ' active' : ''?>" aria-current="<?=$active ? 'page' : 'false' ?>">
        <div class="favorite-list-holder">
          <div class="pull-left favorite-list-title"><?=$this->escapeHtml($list->getTitle())?></div>
          <?php if ($list->isPublic()): ?>
            <?=$this->icon('public') ?>
          <?php endif; ?>
          <div class="pull-right">(<?=$current['count']?>)</div>
          <?php if ($active): ?>
            <button class="pull-right remove-favorite-list remove"><?=$this->icon('list-remove') ?></button>
          <?php endif; ?>
        </div>
      </a>
      <?php if ($active): ?>
        <?php $url = $this->url('list-page', ['lid' => $list->getId()], ['force_canonical' => true]) ?>
        <?= $this->partial('myresearch/list-visibility.phtml', ['listUrl' => $url, 'public' => $list->isPublic()]); ?>
      <?php endif; ?>
    </li>
  <?php endforeach; ?>
  <li class="add-new-list-holder favorites-menulist-item">
    <div class="list-group-item add-new-list">
      <input type="text" class="new-list-input" placeholder="<?=$this->transEsc('Create a List') ?>">
      <?=$this->icon('list-add', 'list-add-icon') ?>
    </div>
  </li>
</ul>
<!-- END of: finna - myresearch/mylist-navi.phtml -->
