<!-- START of: finna - RecordTab/holdingsils/electronic.phtml -->
<div class="table record-holdings-table electronic-holdings">
  <div class="headers">
    <span class="holdings-title"><?=$this->transEsc('Electronic')?></span>
  </div>
  <?php foreach ($this->holdings as $item): ?>
    <?php
      $locationText = $this->transEscWithPrefix('location_', $item['location']);
      if ($this->driver->tryMethod('urlBlocked', [$item['locationhref'] ?? '', $locationText])) {
        continue;
      }
    ?>
    <div class="holdings-container-heading">
      <div class="location electronic">
        <?php if ($item['locationhref'] ?? false): ?>
          <a href="<?=$this->escapeHtmlAttr($this->proxyUrl($item['locationhref']))?>" target="_blank">
            <?=$this->icon('external-link') ?> <?=$locationText?>
          </a>
        <?php else: ?>
          <?=$locationText?>
        <?php endif; ?>
      </div>
      <div class="holdings-details electronic">
        <?php if ($item['use_unknown_message'] ?? false): ?>
          <span><?=$this->transEsc('status_unknown_message')?></span>
        <?php elseif ((int)$item['availability'] === \VuFind\ILS\Logic\ItemStatus::STATUS_UNAVAILABLE): ?>
          <span class="text-danger"><?=$this->transEsc($item['status'])?></span>
        <?php elseif ((int)$item['availability'] === \VuFind\ILS\Logic\ItemStatus::STATUS_UNCERTAIN): ?>
          <span class="text-warning"><?=$this->transEsc($item['status'])?></span>
        <?php else: ?>
          <span class="text-success">
            <?=!empty($item['status']) ? $this->transEsc($item['status']) : $this->transEsc('Available')?>
          </span>
        <?php endif; ?>
        <?php if (isset($item['item_notes'])): ?>
          <div class="item-notes">
            <ul>
              <?php foreach ($item['item_notes'] as $item_note): ?>
                <li><?=$this->escapeHtml($item_note) ?></li>
              <?php endforeach; ?>
            </ul>
          </div>
        <?php endif; ?>
      </div>
      <div class="clearfix"></div>
    </div>
  <?php endforeach; ?>
</div>
<!-- END of: finna - RecordTab/holdingsils/electronic.phtml -->
