<!-- START of: finna - RecordDriver/SolrAipa/encapsulated-records.phtml -->
<?php if ($this->results->getResultTotal() > 0): ?>
  <div class="encapsulated-records">
    <?php foreach ($this->results->getResults() as $result): ?>
      <?php
        $recordFormat = $result->tryMethod('getRecordFormat');
        $recordAttributes = $this->htmlAttributes([
          'id' => 'encapsulated-record-' . $result->getUniqueId(),
          'class' => [
            'encapsulated-record',
            $recordFormat ? 'record-format-' . $recordFormat : '',
          ],
        ]);
      ?>
      <div<?= $recordAttributes ?>>
        <?php if ($result instanceof \VuFind\RecordDriver\Missing): ?>
          <p><?= $this->transEsc('Cannot find record') . ': ' . $this->escapeHtmlAttr($result->getUniqueID()) ?></p>
        <?php else: ?>
          <?= $this->record($result)->getCoreMetadata() ?>
        <?php endif; ?>
      </div>
    <?php endforeach; ?>
  </div>
<?php endif; ?>
<!-- END of: finna - RecordDriver/SolrAipa/encapsulated-records.phtml -->
