<!-- START of: finna - content/about_finna_se.phtml -->
<?php $this->headTitle($this->translate('Oahpásmuva Finna-oidnosiidda'));
$this->content()->setHeading($this->translate('Oahpásmuva Finna-oidnosiidda')); ?>
<p>Finna.fi-ohcanbálvalusa lassin mii fállat  girjerájuide, museaide ja arkiivvaide oktiidoaibmi ja luohtehahtti Finna-vuogádatbálvalusa. Jo badjel 130 organisašuvnna geavahit dan iežaset neahttabálvalusaid huksemii.
</p>
<p>Finna-oidnosiid vehkiin organisašuvnnat buktet iežaset materiála álkit gávdnanláhkai ja dorvvolaččat ávkkástallanláhkai. Organisašuvnnat sáhttet heivehit ja hukset vuogádahkii iežaset bálvalusaid, nugo neahttagirjerájuid ja čoakkáldatozuid.
</p>
<div class="finna-aboutfinna-panel panel">
  <div class="panel-body">
    <p><a href="https://www.finna.fi">Finna.fi</a> čohkke oktii čuđiid girjerájuid, museaid, arkiivvaid, publikašuvdnaarkiivvaid ja dutkanlágádusaid materiálaid. <a href="https://www.finna.fi/Content/about_finnafi">Loga lasi Finnas</a></p>
  </div>
</div>
<div class="panel-body">
  <ul class="finna-aboutfinna-nav nav">
    <li><a href="#archives"><?=$this->translate('Archives') ?></a></li>
    <li><a href="#museums"><?=$this->translate('Museums') ?></a></li>
    <li><a href="#publiclib"><?=$this->translate('Public Libraries') ?></a></li>
    <li><a href="#speciallib"><?=$this->translate('Special libraries') ?></a></li>
    <li><a href="#univlib"><?=$this->translate('University Libraries') ?></a></li>
    <li><a href="#polylib"><?=$this->translate('Polytechnic Libraries') ?></a></li>
    <li><a href="#thematic"><?=$this->translate('Thematic views') ?></a></li>
    <li><a href="#regionallib"><?=$this->translate('Regional views') ?></a></li>
  </ul>
</div>
<hr>
<?=$this->render('content/about_finna_sites.phtml') ?>
<!-- END of: finna - content/about_finna_se.phtml -->
