<!-- START of: finna - content/about_finna_fi.phtml -->
<?php $this->headTitle($this->translate('Tutustu Finna-näkymiin'));
$this->content()->setHeading($this->translate('Tutustu Finna-näkymiin')); ?>
<p>Finna.fi-hakupalvelun lisäksi tarjoamme kirjastoille, museoille ja arkistoille yhteentoimivan ja luotettavan Finna-alustapalvelun. Jo yli 130 organisaatiota hyödyntää sitä omien verkkopalvelujensa toteuttamiseen.
</p>
<p>Finna-alusta auttaa tekemään aineistoista helposti löydettäviä, saavutettavia ja turvallisesti käytettäviä. Organisaatiot voivat rakentaa ja räätälöidä alustalle omia palvelujaan, kuten verkkokirjastoja ja kokoelmahakuja.
</p>
<div class="finna-aboutfinna-panel panel">
  <div class="panel-body">
    <p><a href="https://www.finna.fi">Finna.fi</a>-hakupalvelu kokoaa yhteen satojen kirjastojen, arkistojen, museoiden, julkaisuarkistojen ja tutkimuslaitosten aineistot. <a href="https://www.finna.fi/Content/about_finnafi">Tutustu Finnaan</a></p>
  </div>
</div>
<div class="panel-body">
  <ul class="finna-aboutfinna-nav nav">
    <li><a href="#archives"><?=$this->translate('Archives') ?></a></li>
    <li><a href="#museums"><?=$this->translate('Museums') ?></a></li>
    <li><a href="#publiclib"><?=$this->translate('Public Libraries') ?></a></li>
    <li><a href="#speciallib"><?=$this->translate('Special libraries') ?></a></li>
    <li><a href="#univlib"><?=$this->translate('University Libraries') ?></a></li>
    <li><a href="#polylib"><?=$this->translate('Polytechnic Libraries') ?></a></li>
    <li><a href="#thematic"><?=$this->translate('Thematic views') ?></a></li>
    <li><a href="#regionallib"><?=$this->translate('Regional views') ?></a></li>
  </ul>
</div>
<hr>
<?=$this->render('content/about_finna_sites.phtml') ?>
<!-- END of: finna - content/about_finna_fi.phtml -->
