<!-- START of: finna - content/about_finna_sv.phtml -->
<?php $this->headTitle($this->translate('Upptäck Finna-vyer'));
$this->content()->setHeading($this->translate('Upptäck Finna-vyer')); ?>
<p>Parallellt med söktjänsten Finna.fi erbjuder vi den interoperabla och tillförlitliga plattformstjänsten Finna för våra organisationskunder.  Fler än 130 bibliotek, museer och arkiv har byggt sina egna tjänster på vår Finna-plattform.
</p>
<p>Finnas plattform hjälper till att göra material lätt att hitta, tillgängligt och säkert att använda. Organisationer kan skräddarsy egna tjänster på plattformen, såsom webbibliotek och söktjänster för samlingar.
</p>
<div class="finna-aboutfinna-panel panel">
  <div class="panel-body">
    <p>I <a href="https://www.finna.fi">Finna.fi</a> samlas material från hundratals bibliotek, arkiv, museer, publikationsarkiv och forskningsinstitut. <a href="https://www.finna.fi/Content/about_finnafi">Läs mer om Finna</a></p>
  </div>
</div>
<div class="panel-body">
  <ul class="finna-aboutfinna-nav nav">
    <li><a href="#archives"><?=$this->translate('Archives') ?></a></li>
    <li><a href="#museums"><?=$this->translate('Museums') ?></a></li>
    <li><a href="#publiclib"><?=$this->translate('Public Libraries') ?></a></li>
    <li><a href="#speciallib"><?=$this->translate('Special libraries') ?></a></li>
    <li><a href="#univlib"><?=$this->translate('University Libraries') ?></a></li>
    <li><a href="#polylib"><?=$this->translate('Polytechnic Libraries') ?></a></li>
    <li><a href="#thematic"><?=$this->translate('Thematic views') ?></a></li>
    <li><a href="#regionallib"><?=$this->translate('Regional views') ?></a></li>
  </ul>
</div>
<hr>
<?=$this->render('content/about_finna_sites.phtml') ?>
<!-- END of: finna - content/about_finna_sv.phtml -->
