<!-- START of: finna - content/about_finna_en-gb.phtml -->
<?php $this->headTitle($this->translate('Explore Finna views'));
$this->content()->setHeading($this->translate('Explore Finna views')); ?>
<p>Accompanying the Finna.fi search service, the interoperable and reliable Finna platform is available as a service for our organisational customers. More than 130 libraries, museums and archives have built their services on the platform.
</p>
<p>The Finna platform helps make materials easy to find, accessible and safe to use. Organisations can tailor their own services on the platform, such as online libraries and collection search services.</p>
<div class="finna-aboutfinna-panel panel">
  <div class="panel-body">
    <p><a href="https://www.finna.fi">Finna.fi</a> brings together content from hundreds of libraries, museums, archives, repositories and research institutes. <a href="https://www.finna.fi/Content/about_finnafi"> Read more about Finna</a></p>
  </div>
</div>
<div class="panel-body">
  <ul class="finna-aboutfinna-nav nav">
    <li><a href="#archives"><?=$this->translate('Archives') ?></a></li>
    <li><a href="#museums"><?=$this->translate('Museums') ?></a></li>
    <li><a href="#publiclib"><?=$this->translate('Public Libraries') ?></a></li>
    <li><a href="#speciallib"><?=$this->translate('Special libraries') ?></a></li>
    <li><a href="#univlib"><?=$this->translate('University Libraries') ?></a></li>
    <li><a href="#polylib"><?=$this->translate('Polytechnic Libraries') ?></a></li>
    <li><a href="#thematic"><?=$this->translate('Thematic views') ?></a></li>
    <li><a href="#regionallib"><?=$this->translate('Regional views') ?></a></li>
  </ul>
</div>
<hr>
<?=$this->render('content/about_finna_sites.phtml') ?>
<!-- END of: finna - content/about_finna_en-gb.phtml -->
