<!-- START of: finna - content/help_advanced_sv.phtml -->
<?php $this->headTitle($this->translate('tabs_help-advanced'))?>

<?php if ($this->resolver('content/help-tabs.phtml')): ?>
    <?=$this->render('content/help-tabs.phtml', ['activeTab' => 'help-advanced'])?>
<?php endif; ?>
<div class="sidebar left">
  <div class="content-navigation-menu">
  </div>
</div>
<div class="mainbody right">
  <h1>Avancerad sökning</h1>
  <div id="adv-search-fields" class="content-section">
    <h2>Sökfälten</h2>
    <p>Med hjälp av <a href="<?=$this->url('search-advanced')?>">avancerad sökning</a> kan du göra mer komplicerade sökningar. På sidan för avancerad sökning finns flera olika sökfält där du kan skriva ord eller fraser. Du kan också använda booleska operatorer (AND, OR, NOT).</p>
    <p>Bredvid varje sökfält finns en rullgardinsmeny där du kan rikta in sökningen på exempelvis upphovsman, tema eller t.ex. utgivare. Du kan kombinera flera olika sökord genom att använda flera sökfält eller sökgrupper samtidigt.</p>
  </div>
  <div id="adv-match-menu" class="content-section">
    <h2>Sökfältet i en sökgrupp</h2>
    <p>Rullgardinsmenyn Sök inom en sökgrupp bestämmer huruvida sökresultatet ska innehålla alla sökord i samtliga sökfält, ett eller flera sökord, eller inget av sökorden.</p>
    <p><strong>Med alla följande (AND)</strong> — Söker material som innehåller alla sökord i samtliga sökfält.</p>
    <p><strong>Med något av följande (OR)</strong> — Söker material som innehåller ett eller flera av sökorden i sökfälten. Obs! Man får ofta flera sökresultat med OR än med AND.</p>
    <p><strong>Med inget av följande (NOT)</strong> — Söker material som inte innehåller sökorden från något av sökfälten. Använd det här alternativet om du vill att sökresultaten inte ska innehålla ett visst sökord.</p>
  </div>
  <div id="adv-search-groups" class="content-section">
    <h2>Sökgrupper</h2>
    <p><strong>Lägg till en sökgrupp</strong> kan användas för att lägga till en ny sökgrupp med sökfält.</p>
    <p><strong>Radera sökgruppen</strong> kan användas för att ta bort sökgrupper.</p>
    <p>Relationen mellan sökgrupperna kan definieras med operatorerna <strong>Alla grupper (AND)</strong> och <strong>Vilken grupp som helst (OR)</strong>.</p>
  </div>  
  <div id="adv-search-narrow" class="content-section">
    <h2>Avgränsningar</h2>
    <p>Du kan avgränsa avancerade sökningar för att ta fram resultat på olika språk, enligt materialtyp eller enligt utgivningsår.</p>
    <p>Det är möjligt att inkludera flera olika språk och materialtyper i samma sökning.</p>
    <p>Du kan göra ytterligare avgränsningar i dina sökningar på sidan för sökresultat exempelvis enligt upphovsrätt eller organisation som tillhandahåller materialet.</p>
  </div>
  <div id="adv-search-geo" class="content-section">
    <h2>Geografisk region</h2>
    <p>Du kan på kartan välja en viss region där du vill att materialet ska finnas. Du kan välja hur stort område du vill ta med i sökningen. Observera att allt material inte kan hittas på basis av materialets geografiska läge.</p>
    <p>Tips: Prova att söka på ortnamn! Du kan eventuellt få fram flera resultat.</p>
  </div>
  <div id="adv-search-examples" class="content-section">
    <h2>Exempel på avancerad sökning</h2>
    <h3>Sökning inom en och samma sökgrupp</h3>
    <p>Du söker böcker av Jörn Donner, men är inte intresserad av hans filmer.</p>
    <ol class="list-numbers">
      <li>Skriv i sökfältet <i>Donner Jörn författare</i>.</li>
      <li>Avgränsa sökningen genom att i rullgardinsmenyn bredvid sökfältet välja <strong>Upphovsman och roll</strong>.</li>
    </ol>
    <h3>Kombinera olika sökord och sökgrupper</h3>
    <p>Du söker material om Alvar Aaltos formgivning, men vill inte få med material om arkitektur eller möbler.</p>
    <ol class="list-numbers">
      <li>Skriv <i>Aalto Alvar</i> i sökgruppens sökfält och <i>formgivning</i> i fältet nedanför.</li>
      <li>Se till att du har valt operatorn <strong>Med alla följande (AND)</strong>. Sökprogrammet kombinerar sökorden i bägge sökfälten.</li>
      <li>Lägg till en ny sökgrupp med knappen <strong>+Lägg till en sökgrupp</strong>.</li>
      <li>Skriv <i>möbler</i> och <i>arkitektur</i> i den nya sökgruppens sökfält.</li>
      <li>Avgränsa sökningen genom att i rullgardinsmenyn bredvid sökfältet välja <strong>Ämne</strong>.</li>
      <li>Kombinera sökfälten i sökgruppen genom att i Sök-menyn välja <strong>Med inget av följande (NOT)</strong>. Sökprogrammet utesluter sökorden i sökresultatet.</li>
      <li>Kombinera till slut sökgrupperna med villkoret <strong>Alla grupper (AND)</strong>.</li>
    </ol>
  </div>         
</div>
<!-- END of: finna - content/help_advanced_sv.phtml -->
