<!-- START of: finna - content/privacy_se.phtml -->
<?php $this->headTitle($this->translate('Privacy'));
$this->content()->setHeading($this->translate('Privacy')); ?>

<div class="page-content">
  <h2>Finna – ohcanbálvalusaid ollisvuohta</h2>
  <p>Finna čoahkkana materiálaid oktii čohkkejeaddji Finna.fi:s ja eará Finna-ohcanbálvalusain. Finna.fi:s gávnnat buot doibmiid, geat leat Finnas fárus, dego arkiivvaid, girjerájuid ja museaid, materiálaid. Eará Finna-ohcanbálvalusat vuojulduvvet dihto materiálaide ja bálvalusaide. Lassidiehtu: <a href="https://finna.fi/Content/about">Ohcanbálvalusaid ollisvuohta</a>.
  </p>
  <p>Álbmotgirjerájus lea ovddasvástádus Finna.fi bajásdoallamis ja Finna-ollisvuođa almmolaš ovdánahttimis ovttas guimmiideasetguin. Finna-bálvalusaid buvttadeapmái oassálastá maid CSC – Diehtaga diehtoteknihka guovddáš Oy. Dán siiddus gávnnat dieđu heaggadieđuid gieđahallamis, mat laktásit Finnai, Álbmotgirjerájus ja CSC:s. Dasa lassin bagadit, mot sáhtát váldit oktavuođa materiála fállái dihto materiála heaggadieđuide laktásettiin.
  </p>
  <p>Doibmiin, geat leat mielde Finnas,lea ovddasvástádus iežaset Finna-ohcanbálvalusaid hábmemiin ja dasa gullevaš heaggadieđuid gieđahallamis. Iežaset Finna-ohcanbálvalusain sáhttet fállojuvvot dakkár lassibálvalusat, mat eai leat Álbmotgirjeráju ja CSC:a bajásdoallamis. Juos du geavahan ohcanbálvalussii gullet lassibálvalusat, mat gieđahallet heaggadieđuid, gávnnat áššis dieđu dán siiddus.
  </p>
  <h2>Čálihuvvi geavaheaddji dieđuid gieđahallan Finnas</h2>
  <p>Go geavaheaddji čálihuvvá  Finna-bálvalussii Finna.fi-siidduin dehe eará Finna-ohcanbálvalusas, de furkejuvvojit bálvalussii čuovvovaš dieđuid čálihuvvanvuogis sorjádettiin:
  </p>
  <ul class="list-bullets">
    <li>Girjerádjogoartta dovddaldagaiguin čálihuvadettiin bálvalussii furkejuvvojit girjerádjogoartta nummár, PIN-koda, geavaheaddji ovdanamma ja goargu, šleađgaboastačujuhus ja ruovttugirjerádju. Dieđut sirdojuvvojit automáhtalaččat goartta mieđihan girjeráju vuogádagas Finna-bálvalussii.
    </li>
    <li>Haka-dovddaldagaiguin čálihuvadettiin Finna-bálvalussii furkejuvvo automáhtalaččat čálihuvvi geavaheaddjidovddaldat, namma ja šleađgaboastačujuhus.
    </li>
    <li>Finna-dovddaldagain čálihuvadettiin Finna-bálvalussii furkejuvvojit dieđut, mat leat addojuvvon dovddaldaga duddjoma olis dehege šleađgaboastačujuhus ja geavaheaddjidovddaldat. Vuollel 13-jahkásaččain galgá leat fuolaheaddji miehtan dovddaldaga duddjomii.
    </li>
    <li>Šleađgaboastačujuhusain čálihuvadettiin furkejuvvo čálihuvvi namma, šleađgaboastačujuhus ja ruovttugirjerádji.
    </li>
  </ul>
  <p>Dieđut gieđahallojuvvojit Finna-bálvalusa ollahuhttimii Álbmotgirjerájus ja CSC – Diehtaga diehtoteknihka guovddáš Oy:s (bálvalusa buvttadeaddjit).
  </p>
  <p>Dieđut buvttaduvvojit čuovvovaš geavahanulbmiliidda:
  </p>
  <table class="content-table">
    <tr>
      <td><strong>Diehtu</strong></td>
      <td><strong>Ulbmil</strong></td>
    </tr>
    <tr>
      <th>Geavaheaddjidovddaldat</th>
      <td>Geavaheaddji dovdán</td>
    </tr>
    <tr>
      <th>Šleađgaboastačujuhus</th>
      <td>Navdinčujuhus šleađgaboastta sáddema várás, geavaheaddji hábmemis Finnas. Šleađgaboasttain čálihuvadettiin: čálihuvvanliŋkka sádden áššehasdieđuide furkejuvvon šleađgaboastačujuhussii.</td>
    </tr>
    <tr>
      <th>Ovdanamma</th>
      <td>Dieđu čájeheapmi čálihuvvan geavaheaddjái</td>
    </tr>
    <tr>
      <th>Goargu</th>
      <td>Dieđu čájeheapmi čálihuvvan geavaheaddjái</td>
    </tr>
    <tr>
      <th>Girjerádjogoartta dovddaldat</th>
      <td>Geavaheaddji dovdán</td>
    </tr>
    <tr>
      <th>PIN-koda</th>
      <td>Geavaheaddji dovdán bálvalanrádjegierragiid várás</td>
    </tr>
    <tr>
      <th>Ruovttugirjerádju</th>
      <td>Navdinviežžančuokkis várremiid várás, geavaheaddji hábmemis Finnas</td>
    </tr>
  </table>
  <p>Finna-ohcanbálvalusas geavaheaddji lea maid vejolaš ieš furket ja rievdadit dieđuidis. Finnai furkejuvvon šleađgaboastačujuhussii sáddejuvvojit dušše geavaheaddji ieš bivdin šleađgaboasttaid dego earrebeaivemuittuhusat ja ođasvuođa fávtta sáhkasisdoaluid.
  </p>
  <p>Ovdal namuhuvvon dieđuid lassin Finna-bálvalussii sáhttet furkejuvvot dieđut čuovvumuššan geavaheaddji doaimmas Finnas. Dákkár dieđut leat ee. geavahangiella, maŋemus čálihuvvanáigemuddu, Finna bakte máksojuvvon mávssuid dieđut ja áigemuddu vejolaš meattáhusdiliid čilgemii, earrebeaivemuittuhusaid atnuiváldin, ođasvuođa fávttat, iežas listtuide furkejuvvon merkošat, ieš lasihuvvon girjerádjogoarttat, kommeanttat, árvvoštallamat ja čoavddasánit.
  </p>
  <p>Eará girjerájuid doaimmain, main gieđahallojuvvojit geavaheaddji dieđut, várremiid dahkamis ja luoikamiid ođasteamis sihke áššehassan dieđiheamis, geavahuvvojit girjerádjovuogádaga bálvalanrádjegierragiid. Dát dieđut eai furkejuvvo Finna-bálvalussii earret válljenevttolaš earrebeaivemuittuhusaid. Earrebeaivemuittuhusaid sáddema olis furkejuvvon luoikama ID-nummár ja earrebeaivi. Dáid mielde sáhttá sihkkarastojuvvot dat, ahte guhtenai earrebeaivemuittuhus sáddejuvvo dušše okte.
  </p>
  <p>Girjerádjogoarta-, Finna- ja Haka-dovddaldagaiguin duddjojuvvon Finna-konttut leat nuppiineaset earálágánat, vaikko daidda gulalii seamma spesifiserejuvvon dovddaldat.
  </p>
  <p>Geavaheaddji sáhttá goas beare sihkkut dieđuidis Finna-bálvalusas nu ahte heaittiha iežas konttu bálvalusas. Dieđut sihkkasit automáhtalaččat, go maŋemus čálihuvvamis lea gollan badjel 18 mánu. Go kontu lea jávkan, geavaheaddji bálvalussii vejolaččat dahkan kommeanttat ja árvvoštallamat báhcet anonyman dehege almmá almmá geavaheaddji heaggadieđuid. Juos geavaheaddji háliida sihkkut maid kommeanttaid ja árvvoštallamiid , dat galgá dahkkojuvvot manuálalaččat ovdal konttu sihkkuma. Finna-ohcanbálvalusa geavaheaddji sáhttá sihtat dieđu heaggadieđuidis gieđahallamis nu ahte váldá oktavuođa Álbmotgirjeráju <a href="https://finna.fi/Feedback/Home">Finna.fi-siidduid máhcahatskoviin</a>. eavaheaddjis lea riekti dieđuidis dárkkisteapmái ja njulgemii.
  </p>
  <div class="well">Lassidiehtu gávdno Finna <a href="register_details">diehtosuodječilgehusas</a>.</div>
  <h2>Eará heaggadieđut Finnas</h2>
  <p>Finna.fi-siidduid dehe eará Finna-ohcanbálvalusa bakte gávdnama várás fállojuvvon materiálaid ja dieđuid ovddasvástádus lea daid bálvalussii buktán organisašuvnnain. Vejolaš bivdagat dehe gáibádusat materiálain ja dieđuin gánnáha vuosttaš sajis ovddidit organisašuvdnii, mii fállá daid Finnai.
  </p>
  <p>Materiálain ja dieđuin, mat daid govvidit, sáhttet leat heaggadieđut, dego olbmuid namat dehe govat. Olbmuin, geat laktásit muhtin materiálaide, dego materiálaid dahkkiin, fállojuvvo lassidiehtu iežas siiddus. Juos heaggadieđuin, mat laktásit materiálii dehe dan govvidandieđuide, lea dárbu jearrat gažaldagaid dehe ovdamearkka dihte dahkat dieđuide njulgemiid dehe gáibidit dieđuid sihkkuma, Finna-ohcanbálvalusa geavaheaddji sáhttá leat oktavuođas dan organisašuvdnii, mii fállá materiála dehe dieđu bálvalussii. Váldde oktavuođa -skoviin, mii gávdno Finna.fi-siidduin dihto materiálii dehe olbmui laktáseaddji siiddu olis, lihkostuvvá materiála dehe dieđu fálli dábuheapmi. Juos skovvi váilu, ulbmila várás sáhttá geavahit jv. ohcanbálvalusa iežas máhcahatskovi
  </p>
  <p>Juos Finna-ohcanbálvalusa materiálaid geavaheaddjikommeanttain lea heaggadiehtu, man lea dárbu omd. njulget  dehe gáibidit sihkkojuvvot, sáhttá bivdaga ovddidit skoviin, mii gávdno kommeanttaid olis.
</p>
  <?php if ($template = $this->content()->findTemplateForLng('content/Additions/privacyAdditions')): ?>
    <?=$this->render($template)?>
  <?php endif; ?>
  <h2 id="cookies">Diehtočoahkuid atnu</h2>
  <p>Diehtočoahkuin dárkkuhuvvo diehtu, man server sádde du atnin neahttaloganii. Geavadis gažaldagas lea unna diehtomearáš, dego oanehis deaksta.
  </p>
  <p>Diehtočoahkut eai váikkut diehtodorvui, eaige dat sáhte viiddidit virusiid dehe árroprográmmaid.
  </p>
  <p>Diehtočoahkut álkidahttet Finna geavahusa. Vealtameahttun diehtočoahkut dahket vejolažžan Finna njuovžilis doaimma ja dahket siidduin geavaheaddjiustitlačča. Statistihkkadiehtočoahkuiguin čoggojuvvon diehtu adnojuvvo bálvalusa ovdánahttimii.
  </p>
  <p>Don sáhtát biehttalit ii-vealtameahttun diehtočoahkuin nu ahte gieđahalat diehtočoahkkoásahusaid. Juos rievdadat oaivila, sáhtát gieđahallat miehtama “Diehtočoahkkoásahusat” liŋkkain dehe mielčuovvu boalu bakte, mat gávdnojit siiddu vuolleoasis.
  </p>
  <?php if ($this->cookieConsent()->isEnabled()): ?>
    <h3>Diehtočoahkkoásahusat</h3>
    <?php if ($consent = $this->cookieConsent()->getConsentInformation()): ?>
      <p>Du dálá ásahusat:</p>
      <ul>
        <li>Doaibmasuorgi: <?=$this->escapeHtml($consent['domain'] . ('/' !== $consent['path'] ? $consent['path'] : ''))?></li>
        <li>Sadji: Sallittu (<?=implode(', ', array_map([$this, 'escapeHtml'], $consent['categoriesTranslated']))?>)</li>
        <li>Dohkkehandovddaldat: <?=$this->escapeHtml($consent['consentId'])?>
        <li>Dohkkehanbeaivemearri: <?=$this->escapeHtml($consent['lastConsentDateTime'])?>
      </ul>
    <?php else: ?>
      <p>Et ole vielä hyväksynyt evästeiden käyttöä.</p>
    <?php endif; ?>
    <p>
      <a class="btn btn-default" href="#" data-cc="show-preferencesModal" aria-haspopup="dialog"><?=$this->transEsc('Cookie Settings')?></a>
    </p>
  <?php endif; ?>
</div>
<!-- END of: finna - content/privacy_se.phtml -->
