<!-- START of: finna - content/terms_fi.phtml -->
<?php $this->headTitle($this->translate('Terms'));
$this->content()->setHeading($this->translate('Terms')); ?>

<div class="page-content">
  <h2>Materiála geavahusa guoski eavttut</h2>
  <ul class="list-bullets">
    <li><strong>Digitála materiálat:</strong> Digitála govaid ja eará materiálaid geavahanvuoigatvuođat molsašuddet. Dárkkis gažaldatvuloš materiála oktavuođas geavahanvuoigatvuođadieđuid ja čuovo almmuhuvvon geavahaneavttuid. Jus geavahat materiála almmolaččat, dáhkki ja gáldu ferte dábálaččat almmuhit. <br><br>

    Jus diehtu geavahanvuoigatvuođain váilu, dahje leat eahpesihkkar materiálii laktáseaddji geavahanvuoigatvuođain, váldde oktavuođa organisašuvdnii, mii vástida materiálas. Materiála fáladeaddjái oaččut oktavuođa Finna.fi-siiddus guđege materiála oktavuođas gávdnu Váldde oktavuođa -skoviin.<br><br>

    Organisašuvnna iežas siidduin lea diehtu geavahanvuoigatvuođain ja -ráddjehusain ja oktavuođadieđut lassidieđuid oažžumii. Organisašuvnnaid siidduide beasat omd. <a href="https://finna.fi/Content/organisations?lng=se" target="_blank">Materiálaid fáladeaddjit</a> -oasi bokte.<br><br>

    Stuorámus oassi Finna olggošgovain lea dahkkivuoigatvuođalága vuloš materiála, man geavaheamis galgá soahpat sierra ovdamearkka dihte koasttideaddjiin dahje materiála gaskkusteaddjiin.<br><br>

    </li>
    <li><strong>Govvidandieđut:</strong> <a href="https://finna.fi/?lng=se" target="_blank">Finna.fi</a> -geavahanlavtta ohcanbohtosiid oktavuođas oidnovaš materiálaid govvidandieđuid sáhttá váldoáššis geavahit friija. Spiehkastahkan leat govvidandieđuid čoahkkáigeassoteavsttat, girjjiid maŋŋebearbmateavsttat ja Finna geavaheaddjiid buvttadan govvidandieđut, maidda sáhttet laktásit goalmmát oassebeali dahkkivuoigatvuođat. Eará Finna-geavahanlavttaid ja -neahttagirjerájuid govvidandieđuide sáhttet laktásit geavahanráddjehusat.
    </li>
  </ul>

  <p>Materiála geokodemis lea geavahuvvon OpenStreetMap rabas data, mii lea lisenserejuvvon <a href="http://opendatacommons.org/licenses/odbl/" target="_blank">Open Data Commons Open Database</a> -liseanssaiguin.
  </p>

  <h3>Bálvalusa geavaheami guoski almmolaš eavttut</h3>
  <p>
    Bálvalusa dahje dan osiid ii oaččo geavahit dábálaš geavahusas spiehkkaseaddji geavahanulbmiliidda.
    Bálvalusa sisačáliheami gáibideaddji doaimmaid automáhtalaš geavaheapmi (maiddái "robot-", "spider-", "scraper-" ja "offline reader-" prográmmat) lea gildojuvvon.
  </p>
  <p>
  Mii várret vuoigatvuođa ráddjet bálvalusa oažžuma ovdamearkka dihte bajásdoalu, divodanbargguid dahje bálvalusa doaimma dorvvastan dihte.
  </p>
</div>
<!-- END of: finna - content/terms_fi.phtml -->