<?php
  $__attributes = $this->htmlAttributes($attributes ?? []);
  $__titleElement = $sectionTitleElement ?? 'h3';
  $__titleStartTag = "<$__titleElement class=\"level-data-section-title\">";
  $__titleEndTag = "</$__titleElement>";
?>
<section<?= $__attributes->add('class', 'finna-educational-level-data') ?>>
  <?php if (!empty($learningAreas)): ?>
    <section>
      <?= $__titleStartTag ?><?= $this->transEsc($learningAreasTitle ?? '') ?><?= $__titleEndTag ?>
      <ul>
        <?php foreach ($learningAreas as $__learningArea): ?>
          <li><?= $this->transEsc($__learningArea) ?></li>
        <?php endforeach; ?>
      </ul>
    </section>
  <?php endif; ?>
  <?php if (!empty($studyContents)): ?>
    <section>
      <?= $__titleStartTag ?><?= $this->transEsc($studyContentsTitle ?? '') ?><?= $__titleEndTag ?>
      <ul>
        <?php foreach ($studyContents as $__subject => $__values): ?>
          <li>
            <dl>
              <dt><?= $this->transEsc($__subject) ?>:</dt>
              <?php foreach ($__values as $__value): ?>
                <dd><?= $this->transEsc($__value) ?></dd>
              <?php endforeach; ?>
            </dl>
          </li>
        <?php endforeach; ?>
      </ul>
    </section>
  <?php endif; ?>
  <?php if (!empty($studyObjectives)): ?>
    <section>
      <?= $__titleStartTag ?><?= $this->transEsc($studyObjectivesTitle ?? '') ?><?= $__titleEndTag ?>
      <ul>
        <?php foreach ($studyObjectives as $__subject => $__values): ?>
          <li>
            <dl>
              <dt><?= $this->transEsc($__subject) ?>:</dt>
              <?php foreach ($__values as $__value): ?>
                <dd><?= $this->transEsc($__value) ?></dd>
              <?php endforeach; ?>
            </dl>
          </li>
        <?php endforeach; ?>
      </ul>
    </section>
  <?php endif; ?>
  <?php if (!empty($transversalCompetences)): ?>
    <section>
      <?= $__titleStartTag ?><?= $this->transEsc($transversalCompetencesTitle ?? '') ?><?= $__titleEndTag ?>
      <ul>
        <?php foreach ($transversalCompetences as $__transversalCompetence): ?>
          <li><?= $this->transEsc($__transversalCompetence) ?></li>
        <?php endforeach; ?>
      </ul>
    </section>
  <?php endif; ?>
  <?php if (!empty($vocationalUnits)): ?>
    <section>
      <?= $__titleStartTag ?><?= $this->transEsc($vocationalUnitsTitle ?? '') ?><?= $__titleEndTag ?>
      <ul>
        <?php foreach ($vocationalUnits as $__subject => $__values): ?>
          <li>
            <dl>
              <dt><?= $this->transEsc($__subject) ?>:</dt>
              <?php foreach ($__values as $__value): ?>
                <dd><?= $this->transEsc($__value) ?></dd>
              <?php endforeach; ?>
            </dl>
          </li>
        <?php endforeach; ?>
      </ul>
    </section>
  <?php endif; ?>
  <?php if (!empty($vocationalCommonUnits)): ?>
    <section>
      <?= $__titleStartTag ?><?= $this->transEsc($vocationalCommonUnitsTitle ?? '') ?><?= $__titleEndTag ?>
      <ul>
        <?php foreach ($vocationalCommonUnits as $__vocationalCommonUnit): ?>
          <li><?= $this->transEsc($__vocationalCommonUnit) ?></li>
        <?php endforeach; ?>
      </ul>
    </section>
  <?php endif; ?>
  <?php if (isset($objective)): ?>
    <section class="educational-level-objective">
      <?= $__titleStartTag ?><?= $this->transEsc($objectiveTitle ?? '') ?><?= $__titleEndTag ?>
      <p><?= $this->transEsc($objective) ?></p>
    </section>
  <?php endif; ?>
</section>
