<?php $cnt = 0; ?>
<ul class="article-links">
<?php foreach ($this->items as $item): ?>
  <?php
    $selected = $numeric
      ? $element === $cnt
      : $element === $item['id'];

    $link = $item['link'];
    if ($this->feedId) {
      $link .= !str_contains($item['link'], '?') ? '?' : '&';
      $link .= 'id=' . urlencode($this->feedId);
    }
  ?>
  <li><?= !$selected ? ('<a href="' . $this->escapeHtmlAttr($link) . '">' . $this->escapeHtml($item['title']) . '</a>') : $this->escapeHtml($item['title']) ?></li>
  <?php $cnt++; ?>
<?php endforeach;?>
</ul>
