<!-- START of: finna2 - Recommend/SideFacets/usage-rights-ext-facet-footer.phtml -->
<div class="list-group-item facet-info">
  <div class="more-info">
    <a href="<?=$this->url('content-page', ['page' => 'terms'])?>#terms"><?=$this->transEsc('usage_rights_ext_info_more_link')?></a>
  </div>
</div>
<div class="list-group-item alert facet-info facet-info-highlight">
  <?=$this->icon('info') ?><div class="info"><?=$this->transEsc('usage_rights_ext_info')?></div>
</div>
<!-- END of: finna2 - Recommend/SideFacets/usage-rights-ext-facet-footer.phtml -->
