<!-- START of: finna - search/home/home-2_en-gb.phtml -->
<div>
  <h2>home-2_en-gb.phtml</h2>
</div>
<div>
  <div class="info-col">
    <div class="infobox">
    <h2>Try the search for international scholarly material</h2>
    <p>Do a search that interests you and then select the tab for international material.<p>
    <p><small>The international material contains peer-reviewed full texts as well as material available online.</small></p>
    <p><a class="btn btn-primary" role="button" href="<?=$this->url('primo-search');?>?lookfor=Work%20intensification&amp;type=AllFields&amp;filter%5B%5D=tlevel%3A%22online_resources%22"><?=$this->icon('search') ?> Example Search</a>
    </div>
  </div>
  <div class="info-col">
    <div class="infobox">
      <h2>New loans</h2>
      <p><a class="btn btn-primary" role="button" href="<?=$this->url('myresearch-checkedout')?>" title="Login"><?=$this->icon('sign-in') ?> Login </a> using your library card or Haka-login.</p>
      <p>Select the button Renew all loans.</p>
      <p>All renewable loans will be renewed.</p>
    </div>
  </div>

  <div class="info-col">
    <div class="infobox">
      <h2>Class infobox styles can be edited in variables.less file</h2>
      <ul>
        <li>@home-middle-background = background of full container</li>
        <li>@infobox-background = infobox background</li>
        <li>@infobox-border = infobox border</li>
        <li>@infobox-text-color = text default color</li>
        <li>@infobox-box-shadow = shadow of infoboxes</li>
      </ul>
    </div>
  </div>
</div>
<!-- END of: finna - search/home/home-2_en-gb.phtml -->
