<!-- START of: finna - RecordDriver/SolrLido/core.phtml -->
<?php
  $params = $this->searchMemory()->getLastSearchParams($this->searchClassId);
  $img = $this->recordImage($this->record($this->driver));
  $urls = $this->record($this->driver)->getLinkDetails();
  if (!empty($urls)){
      $videoUrls = [];
      $audioUrls = [];
      $otherUrls = [];
      foreach ($urls as $url){
          if (!empty($url['videoSources']) || !empty($url['embed']) && $url['embed'] == 'video' || $this->recordLinker()->getEmbeddedVideo($url['url']) == 'data-embed-iframe'){
            array_push($videoUrls, $url);
          } elseif (!empty($url['embed']) && $url['embed'] == 'audio') {
            array_push($audioUrls, $url);
          } else {
            array_push($otherUrls, $url);
          }
      }
  }

  $thumbnail = false;
  $thumbnailAlignment = $this->record($this->driver)->getThumbnailAlignment('result');
  ob_start();
?>
  <div class="media-<?=$thumbnailAlignment ?><?=!empty($audioUrls) ? ' audio' : ''?>">

    <?=$this->record($this->driver)->renderTemplate('record-image-information.phtml', ['img' => $img, 'sizes' => ['small' => ['w' => 100, 'h' => 100], 'medium' => ['w' => 1200, 'h' => 1200]]]);?>

    <?php if (!empty($videoUrls)): ?>
      <?=$this->record($this->driver)->renderTemplate('record-video-player.phtml', ['videoUrls' => $videoUrls, 'type' => 'SolrLido']);?>
    <?php endif; ?>

    <?php if (!empty($audioUrls)): ?>
      <?=$this->record($this->driver)->renderTemplate('record-audio-player.phtml', ['audioUrls' => $audioUrls]);?>
    <?php endif; ?>

    <?php if ($this->record($this->driver)->getOrganisationMenuPosition() === 'inline'): ?>
      <div class="organisation-menu">
        <?=$this->render('record/record-organisation-menu.phtml') ?>
      </div>
    <?php endif; ?>

    <?=$this->record($this->driver)->renderTemplate('record-post-thumbnail.phtml');?>
  </div>
<?php
  $thumbnail = ob_get_contents();
  ob_end_clean();
  $summaries = $this->driver->getSummary();
  ob_start();
?>
<?php if (!empty($summaries)): ?>
  <div class="truncate-field wide summary recordSummary">
    <?php foreach ($summaries as $s): ?>
      <?= $this->recordFieldMarkdown()->toHtml($s) ?>
    <?php endforeach; ?>
  </div>
<?php endif; ?>
<?php
  $summaryContent = ob_get_contents();
  ob_end_clean();
?>
<?php $this->metadata()->generateMetatags($this->driver);?>
<div class="media" vocab="http://schema.org/" resource="#record" typeof="<?=$this->driver->getSchemaOrgFormats()?> Product">
  <h1 property="name" class="record-title visible-xs"><?=$this->escapeHtml($this->driver->getTitle())?></h1>
  <?php if ($summaryContent): ?>
    <div class="truncate-wrapper visible-xs">
      <?=$summaryContent?>
    </div>
  <?php endif; ?>
  <?php if ($thumbnail && $thumbnailAlignment == 'left'): ?>
    <?=$thumbnail ?>
  <?php endif; ?>
    <div class="media-body record-information">
      <h1 property="name" class="record-title hidden-xs"><?=$this->escapeHtml($this->driver->getTitle())?></h1>
      <?php if ($results = $this->driver->getAlternativeTitles()): ?>
        <div class="recordAltTitles record-alt-titles">
          <?=implode('<br>', array_map([$this, 'escapeHtml'], $results))?>
        </div>
      <?php endif; ?>

      <div class="record-core-metadata">
        <?php if ($results = $this->driver->getNonPresenterAuthors()): ?>
          <div class="truncate-field">
            <?php foreach($results as $index => $author): ?>
              <?=($index > 0 ? '; ' : '')?><a href="<?=$this->record($this->driver)->getLink('author', $author['name'])?>"><?=$this->escapeHtml($author['name'])?></a><?php if (!empty($author['date'])): ?><span class="author-date">, <?=$this->escapeHtml($author['date']) ?></span><?php endif; ?><?php if (!empty($author['role'])): ?><span class="author-role">, <?=$this->escapeHtml($author['role']) ?></span><?php endif; ?>
            <?php endforeach; ?>
            <?php if ($dates = $this->driver->getResultDateRange()): ?>
              <?=$this->escapeHtml($dates[0]);?><?php if (isset($dates[1]) && $dates[1] != $dates[0]): ?>&ndash;<?=$this->escapeHtml($dates[1])?><?php endif; ?>
            <?php endif; ?>
            <?php if (($results = $this->driver->getSubjectDates()) && !isset($dates[0])): ?>
              <?=implode('<br/>', array_map([$this, 'escapeHtml'], $results))?>
            <?php endif; ?>
          </div>
        <?php endif; ?>

        <?php if ($this->searchOptions($this->driver->getSourceIdentifier())->getVersionsAction()): ?>
          <?=$this->record($this->driver)->renderTemplate('versions-link.phtml')?>
        <?php endif; ?>
      </div>

      <?php if ($documents = $this->driver->getDocuments()): ?>
        <div class="record-links">
          <div class="recordURLs local-available-online-record">
            <ul class="truncate-field outer" data-rows="4">
              <?php foreach ($documents as $i => $document): ?>
                <?php
                  $description = $document['description'] ?: $this->translate('Download the file');
                ?>
                <li class="fulltextField">
                  <a href="<?=$this->escapeHtmlAttr($this->url('record-downloadfile', [], ['query' => ['id' => $this->driver->getUniqueID(), 'index' => $i, 'format' => $document['format'], 'type' => 'document']]))?>" target="_blank" download>
                    <i class="fa fa-download" aria-hidden="true"></i>
                    <?=$this->escapeHtml($description)?>
                  </a>
                  (<?=$this->escapeHtml($document['format'])?>)
                </li>
              <?php endforeach; ?>
            </ul>
          </div>
        </div>
      <?php endif; ?>

      <?php if ($summaryContent): ?>
        <div class="truncate-wrapper hidden-xs">
          <?=$summaryContent?>
        </div>
      <?php endif; ?>

      <?php if ($this->userlist()->getMode() !== 'disabled'): ?>
        <?php /* Display the lists that this record is saved to */ ?>
        <div class="savedLists" id="savedLists">
          <strong><?=$this->transEsc("Saved in")?>:</strong>
        </div>
      <?php endif; ?>

      <?/* Display Main Details */?>
      <?php
        $formatter = $this->recordDataFormatter();
        $coreFields = $formatter->filterLIDOFields($formatter->getDefaults('core'));
        // Note: groups contain also fields that come before the Context group:
        $coreFieldGroups = $formatter->getGroupedData($driver, $formatter->getGroupedFields([
          ['lines' => ['Genre']],
          ['lines' => ['Age Limit']],
          ['lines' => ['Original Work']],
          ['lines' => ['Published in']],
          ['lines' => ['New Title']],
          ['lines' => ['Previous Title']],
          ['lines' => ['Secondary Authors']],
          ['lines' => ['Actors']],
          ['lines' => ['Identifiers']],
          ['lines' => ['Press Reviews']],
          ['lines' => ['Music']],
          ['lines' => ['Projected Publication Date']],
          ['lines' => ['Dissertation Note']],
          ['lines' => ['Other Links']],
          ['lines' => ['Presenters']],
          ['lines' => ['Other Titles']],
          ['lines' => ['Format']],
          ['lines' => ['Collection']],
          ['label' => 'Context',
           'lines' => ['Parent Archive', 'Parent Collection', 'Parent Purchase Batch', 'Parent Series', 'Parent Works']
          ],
        ], $coreFields));
      ?>
      <?php if (!empty($coreFieldGroups)): ?>
        <table class="table table-finna-record record-details record-field-groups" role="presentation">
          <?=$this->record($this->driver)->renderTemplate('core-field-groups.phtml', ['data' => $coreFieldGroups]);?>
        </table>
      <?php endif; ?>
      <?/* End Main Details */?>

      <?php if ($template = $this->content()->findTemplateForLng("content/Additions/record-post-metadata")): ?>
      <div>
        <?=$this->render($template)?>
      </div>
      <?php endif; ?>
    </div>
  <?php if ($thumbnail && $thumbnailAlignment == 'right'): ?>
    <?=$thumbnail ?>
  <?php endif; ?>
</div>
<!-- END of: finna - RecordDriver/SolrLido/core.phtml -->
