<?php //Don't add START and END comments ?>
<?php if (!empty($data)): ?>
  <?php if (is_array($data)): ?>
    <div class="truncate-field" data-rows="5">
      <?php foreach ($data as $field): ?>
        <?php if (!is_array($field)): ?>
        <?=$this->record($this->driver)->getLinkedFieldElement($this->headingType ?? 'place', $field, ['name' => $field], ['class' => ['backlink'], 'description' => true])?><br>
        <?php else: ?>
          <?php
            $id = $field['id'] ?? null;
            $ids = $field['ids'] ?? null;
            $links = $field['externalLinks'] ?? null;
          ?>
          <?=$this->record($this->driver)->getLinkedFieldElement(
              $this->headingType ?? 'place',
              $field['placeName'],
              ['name' => $field['placeName'], 'id' => $id, 'ids' => $ids, 'externalLinks' => $links],
              ['class' => ['backlink'], 'description' => true]
          )?><br>
        <?php endif; ?>
      <?php endforeach; ?>
    </div>
  <?php else: ?>
    <?=$this->escapeHtml($data) ?><br>
  <?php endif; ?>
<?php endif; ?>
