<!-- START of: finna - holds/list.phtml -->
<?php
    // Set up page title:
    $this->headTitle($this->translate('My Holds'));
    // Set up breadcrumbs:
    $this->layout()->breadcrumbs = '<li><a href="' . $this->url('myresearch-home') . '">' . $this->transEsc('Your Account') . '</a></li> <li class="active">' . $this->transEsc('My Holds') . '</li>';
    $user = $this->auth()->isLoggedIn();
    // Add finna-holds.js
    $this->headScript()->appendFile('finna-holds.js');
    $patron = $user ? $this->auth()->getILSPatron() : false;
    $changePickupLocation = $this->ils()->checkFunction('changePickupLocation', [$patron]);
    $changeRequestStatus = $this->ils()->checkFunction('changeRequestStatus', [$patron]);
?>

<!-- Leftside navigationbar -->
<?= $this->context($this)->renderInContext("myresearch/menu.phtml", ['active' => 'holds']); ?>

<div class="<?=$this->layoutClass('mainbody-myresearch')?>">
  <div class="my-research-content">
    <div class="myresearch-grid-list">
      <?php if (!$this->translationEmpty('holds_instructions_html')): ?><p class="no-content-message"><?=$this->translate('holds_instructions_html')?></p><?php endif; ?>
      <?=$this->flashmessages()?>
      <?=$this->partial('myresearch/borrowing-block.phtml', ['blocks' => $this->blocks]); ?>
      <div class="useraccount-row">
        <?=$this->context($this)->renderInContext('librarycards/selectcard.phtml', ['user' => $user, 'label' => 'Library Card'])?>
      </div>
      <div class="useraccount-header">
        <h2><?=$this->transEsc('Your Holds and Recalls') ?> (<?=count($this->recordList ?? []);?>)</h2>
      </div>
      <?php if (isset($this->noSupport)): ?>
        <?php if ($user->getLibraryCards()->count() > 1): ?>
          <div class="support-notice">
            <p><?=$this->transEsc("no_ils_support_description") ?></p>
          </div>
        <?php endif; ?>
      <?php else: ?>
        <?php if ($template = $this->content()->findTemplateForLng("content/Additions/holds-pre-list")): ?>
          <div class="holds-pre-list"><?=$this->render($template)?></div>
        <?php endif; ?>
        <?php if (!empty($this->recordList)): ?>
          <?php if ($this->cancelForm || $this->updateForm): ?>
            <form name="cancelForm" class="inline" method="post" action="<?=$this->escapeHtmlAttr($this->url('holds-list'))?>" id="update_holds" data-clear-account-cache="holds" data-lightbox>
              <input type="hidden" id="submitType" name="cancelSelected" value="1"/>
              <input type="hidden" id="cancelConfirm" name="confirm" value="0"/>
              <table class="myresearch-table" role="presentation">
                <tr class="toolbar">
                  <td class="text-left checkbox-col">
                    <div class="checkboxFilter mylist-select-all">
                      <div class="checkbox">
                        <label>
                          <input type="checkbox" name="selectAll" class="checkbox-select-all"/>
                          <?=$this->transEsc('select_page')?>
                        </label>
                      </div>
                    </div>
                  </td>
                  <td>
                    <?php if ($this->updateForm): ?>
                      <div class="btn-group">
                        <input id="update_selected" name="updateSelected" type="submit" value="<?=$this->transEscAttr('hold_edit_selected') ?>" class="btn btn-primary hidden">
                      </div>
                    <?php endif; ?>
                    <?php if ($this->cancelForm): ?>
                      <div class="btn-group">
                        <input id="cancelSelected" name="cancelSelected" type="submit" value="<?=$this->transEscAttr("hold_cancel_selected") ?>" class="btn btn-primary dropdown-toggle" data-toggle="dropdown" data-lightbox-ignore>
                        <ul class="dropdown-menu useraccount-cancel">
                          <li class="disabled"><a><?=$this->transEsc("confirm_hold_cancel_selected_text") ?></a></li>
                          <li><a href="#" id="confirm_cancel_selected_yes"><?=$this->transEsc('confirm_dialog_yes') ?></a></li>
                          <li><a href="#" class="confirm_cancel_no"><?=$this->transEsc('confirm_dialog_no')?></a></li>
                        </ul>
                      </div>
                      <div class="btn-group">
                        <input id="cancelAll" name="cancelAll" type="submit" value="<?=$this->transEscAttr("hold_cancel_all") ?>" class="btn btn-primary dropdown-toggle" data-toggle="dropdown" data-lightbox-ignore>
                        <ul class="dropdown-menu useraccount-cancel">
                          <li class="disabled"><a><?=$this->transEsc("confirm_hold_cancel_all_text") ?></a></li>
                          <li><a href="#" id="confirm_cancel_all_yes"><?=$this->transEsc('confirm_dialog_yes') ?></a></li>
                          <li><a href="#" class="confirm_cancel_no"><?=$this->transEsc('confirm_dialog_no')?></a></li>
                        </ul>
                      </div>
                    <?php endif; ?>
                  </td>
                </tr>
              </table>
          <?php else: ?>
            <table class="myresearch-table" role="presentation">
              <tr class="toolbar">
                <th colspan="4" class="myresearch-notification"><?=$this->transEsc('Cannot update any of the holds')?></th>
              </tr>
            </table>
          <?php endif; ?>
          <table class="myresearch-table" aria-label="<?=$this->transEscAttr('Your Holds and Recalls');?>" tabindex="0">
            <tr class="sr-only myresearch-row" aria-hidden="true">
              <th id="label-select-column"><?=$this->transEsc('Select');?></th>
              <th class="hidden-xs"></th>
              <th id="label-title-column"><?=$this->transEsc('Hold Details');?></th>
            </tr>
            <?php $iteration = 0; ?>
            <?php foreach ($this->recordList as $resource): ?>
              <?php $iteration++; ?>
              <?php $ilsDetails = $resource->getExtraDetail('ils_details'); ?>
              <tr class="myresearch-row result">
                <td class="text-left checkbox-col">
                <?php if ($this->cancelForm && isset($ilsDetails['cancel_details'])): ?>
                  <input type="hidden" name="cancelAllIDS[]" value="<?=$this->escapeHtmlAttr($ilsDetails['cancel_details']) ?>" />
                  <div class="checkboxFilter">
                    <div class="checkbox">
                      <label>
                        <span class="sr-only"><?=$this->transEsc('Select');?></span>
                        <input type="checkbox" name="selectedIDS[]" class="checkbox-select-item" value="<?=$this->escapeHtmlAttr($ilsDetails['cancel_details']) ?>" />
                      </label>
                    </div>
                  </div>
                <?php else: ?>
                  <span class="no-checkbox"><?=$this->transEsc('Cannot update');?></span>
                <?php endif; ?>
                </td>
                <td class="text-left hidden-xs" aria-hidden="true">
                  <div class="cover-image">
                    <?php if ($summThumb = $this->record($resource)->getThumbnail()): ?>
                      <img src="<?=$this->escapeHtmlAttr($summThumb)?>" class="recordcover" alt="<?=$this->transEscAttr('Cover Image')?>"/>
                    <?php else: ?>
                      <img src="<?=$this->url('cover-unavailable')?>" class="recordcover" alt="<?=$this->transEscAttr('No Cover Image')?>"/>
                    <?php endif; ?>
                  </div>
                </td>
                <td headers="label-title-column" aria-labelledby="label-title-column">
                  <div class="half-table-column text-left">
                    <?php
                      // If this is a non-missing Solr record, we should display a link:
                      if (is_a($resource, 'VuFind\\RecordDriver\\SolrDefault') && !is_a($resource, 'VuFind\\RecordDriver\\Missing')) {
                        // Use ILS title if available since it may contain e.g. issue number
                        if (!empty($ilsDetails['title'])) {
                          $title = trim($ilsDetails['title'], '/: ');
                        } else {
                          $title = $resource->getTitle();
                          $title = empty($title) ? $this->transEsc('Title not available') : $this->escapeHtml($title);
                        }
                        echo '<a href="' . $this->recordLink()->getUrl($resource)
                          . '" class="record-title">' . $title . '</a>';
                      } elseif (isset($ilsDetails['title']) && !empty($ilsDetails['title'])){
                        // If the record is not available in Solr, perhaps the ILS driver sent us a title we can show...
                        echo '<span class="record-title">' . $this->escapeHtml($ilsDetails['title']) . '</span>';
                      } else {
                        // Last resort -- indicate that no title could be found.
                        echo '<span class="record-title">' . $this->transEsc('Title not available') . '</span>';
                      }
                    ?>
                    <div class="record-core-metadata">
                      <?php $formats = $resource->getFormats(); if (count($formats) > 0): ?>
                        <?=$this->record($resource)->getFormatList() ?>
                        <br/>
                      <?php endif; ?>
                      <?=$this->partial('myresearch/helpers/record-author.phtml', ['record' => $resource]);?>
                      <?php if (isset($ilsDetails['volume']) && !empty($ilsDetails['volume'])): ?>
                        <strong><?=$this->transEsc('Volume')?>:</strong> <?=$this->escapeHtml($ilsDetails['volume'])?>
                        <br />
                      <?php endif; ?>

                      <?php if (isset($ilsDetails['publication_year']) && !empty($ilsDetails['publication_year'])): ?>
                        <strong><?=$this->transEsc('Year of Publication')?>:</strong> <?=$this->escapeHtml($ilsDetails['publication_year'])?>
                        <br />
                      <?php endif; ?>
                    </div>
                  </div>
                  <div class="half-table-column holds-status-information">
                    <?php if (!empty($ilsDetails['requestGroup'])): ?>
                      <strong><?=$this->transEsc('hold_requested_group') ?>:</strong> <?=$this->transEsc('request_group_' . $ilsDetails['requestGroup'], [], $this->transEscWithPrefix('location_', $ilsDetails['requestGroup']))?>
                      <br />
                    <?php endif; ?>

                    <?php /* Depending on the ILS driver, the "location" value may be a string or an ID; figure out the best
                      value to display... */ ?>
                    <?php $pickupDisplay = ''; ?>
                    <?php $pickupTranslate = false; ?>
                    <?php if (isset($ilsDetails['location'])): ?>
                      <?php if ($this->pickup): ?>
                        <?php foreach ($this->pickup as $library): ?>
                          <?php if ($library['locationID'] == $ilsDetails['location']): ?>
                            <?php $pickupDisplay = $library['locationDisplay']; ?>
                            <?php $pickupTranslate = true; ?>
                          <?php endif; ?>
                        <?php endforeach; ?>
                      <?php endif; ?>
                      <?php if (empty($pickupDisplay)): ?>
                        <?php $pickupDisplay = $ilsDetails['location']; ?>
                      <?php endif; ?>
                    <?php endif; ?>

                    <?php $requestIsEditable = $ilsDetails['is_editable'] ?? true; ?>

                    <?php if (!empty($pickupDisplay)): ?>
                      <div class="pickup-location-container">
                        <strong><?=$this->transEsc('pick_up_location') ?>:</strong>
                        <?php if (isset($ilsDetails['available']) && !$ilsDetails['available'] && $changePickupLocation && $requestIsEditable): ?>
                          <div class="changeHolds" data-record-id="<?=$this->escapeHtmlAttr($resource->getUniqueId()) ?>" data-request-id="<?=$this->escapeHtml($ilsDetails['requestId']) ?>" data-item-id="<?=$this->escapeHtml($ilsDetails['item_id'] ?? '') ?>">
                            <span class="pickup-change-load-indicator hidden"><i class="fa fa-spinner fa-spin"></i></span>
                            <div class="view-button pickup-location">
                              <div class="dropdown">
                                <a href="" class="dropdown-toggle" data-toggle="dropdown">
                                  <span class="pickupLocationSelected"><?=$pickupTranslate ? $this->transEsc($pickupDisplay) : $this->escapeHtml($pickupDisplay)?></span> <i class="fa fa-arrow-down"></i>
                                </a>
                                <ul class="dropdown-menu pickup-locations" role="menu">
                                  <li role="menuitem" class="pickup-location-load-indicator hidden"><a><i class="fa fa-spinner fa-spin"></i> <?=$this->transEsc('Loading')?>...</a></li>
                                </ul>
                              </div>
                            </div>
                          </div>
                        <?php else:?>
                          <?=$pickupTranslate ? $this->transEsc($pickupDisplay) : $this->escapeHtml($pickupDisplay)?>
                        <?php endif; ?>
                      </div>
                    <?php endif; ?>

                    <?php if (!empty($ilsDetails['create'])): ?>
                      <strong><?=$this->transEsc('Created') ?>:</strong> <?=$this->escapeHtml($ilsDetails['create']) ?>
                      <?php if (!empty($ilsDetails['expire'])): ?>|<?php endif; ?>
                    <?php endif; ?>
                    <?php if (!empty($ilsDetails['expire'])): ?>
                      <strong><?=$this->transEsc('hold_expires') ?>:</strong> <?=$this->escapeHtml($ilsDetails['expire']) ?>
                    <?php endif; ?>
                    <br />

                    <?php if (isset($ilsDetails['available']) && $ilsDetails['available'] == true): ?>
                      <div class="alert alert-success">
                        <?php if (!empty($ilsDetails['last_pickup_date'])): ?>
                          <?=$this->transEsc('hold_available_until', ['%%date%%' => $ilsDetails['last_pickup_date']]) ?>
                        <?php else: ?>
                          <?=$this->transEsc('hold_available') ?>
                        <?php endif; ?>
                        <?php if (isset($ilsDetails['pickupnum'])):?>
                        <br />
                        <strong><?=$this->transEsc("Pickup number") ?>:</strong> <?=$this->escapeHtml($ilsDetails['pickupnum']) ?>
                        <?php endif;?>
                      </div>
                    <?php elseif (isset($ilsDetails['in_transit']) && $ilsDetails['in_transit']): ?>
                      <div class="text-success"><?=$this->transEsc('request_in_transit') . (is_string($ilsDetails['in_transit']) ? ': ' . $this->transEsc('institution_' . $ilsDetails['in_transit'], [], $ilsDetails['in_transit']) : '') ?></div>
                    <?php elseif (isset($ilsDetails['position'])): ?>
                      <p><strong><?=$this->transEsc("hold_queue_position") ?>:</strong> <?=$this->escapeHtml($ilsDetails['position']) ?></p>
                    <?php endif; ?>

                    <?php if (isset($this->cancelResults['items'])): ?>
                      <?php foreach ($this->cancelResults['items'] as $itemId => $cancelResult): ?>
                        <?php if (($itemId == $ilsDetails['item_id'] || $itemId == ($ilsDetails['requestId'] ?? '')) && $cancelResult['success'] == false): ?>
                          <div class="alert alert-danger"><?=$this->transEsc($cancelResult['status']) ?><?php if ($cancelResult['sysMessage']) echo ' : ' . $this->transEsc($cancelResult['sysMessage']); ?></div>
                        <?php endif; ?>
                      <?php endforeach; ?>
                    <?php endif; ?>

                    <?php if (isset($ilsDetails['reqnum']) && !empty($this->updateResults[$ilsDetails['reqnum']])): ?>
                      <?php $updateResult = $this->updateResults[$ilsDetails['reqnum']]; ?>
                      <?php if (!$updateResult['success']): ?>
                        <div class="alert alert-danger"><?=$this->transEsc($updateResult['status']) ?><?php if (!empty($updateResult['sysMessage'])) echo ': ' . $this->transEsc($updateResult['sysMessage']); ?></div>
                      <?php endif; ?>
                    <?php endif; ?>

                    <?php if (isset($ilsDetails['available']) && !$ilsDetails['available'] && $changeRequestStatus && $requestIsEditable): ?>
                      <div class="change-hold-status" data-record-id="<?=$this->escapeHtmlAttr($resource->getUniqueId()) ?>" data-request-id="<?=$this->escapeHtml($ilsDetails['requestId']) ?>" >
                        <span class="status-change-load-indicator hidden"><i class="fa fa-spinner fa-spin"></i></span>
                        <span class="hold-status-active<?=!empty($ilsDetails['frozen']) ? ' hidden' : '' ?>">
                          <a class="hold-status-freeze" href="#"><?=$this->transEsc('request_freeze') ?></a>
                        </span>
                        <span class="hold-status-frozen<?=!empty($ilsDetails['frozen']) ? '' : ' hidden' ?>">
                          <?=$this->transEsc('request_frozen') ?>&nbsp;-&nbsp;<a class="hold-status-release" href="#"><?=$this->transEsc('request_release') ?></a>
                        </span>
                      </div>
                    <?php elseif (!empty($ilsDetails['frozen'])): ?>
                      <strong>
                        <?php if (empty($ilsDetails['frozenThrough'])): ?>
                          <?=$this->transEsc('hold_frozen') ?>
                        <?php else: ?>
                          <?=$this->transEsc('hold_frozen_through', ['%%date%%' => $ilsDetails['frozenThrough']]) ?>
                        <?php endif; ?>
                      </strong>
                    <?php endif; ?>

                    <?php if (isset($ilsDetails['cancel_link'])): ?>
                      <p><a href="<?=$this->escapeHtmlAttr($ilsDetails['cancel_link']) ?>"><?=$this->transEsc("hold_cancel") ?></a></p>
                    <?php endif; ?>
                    <?php if (isset($ilsDetails['updateDetails'])): ?>
                      <p><a class="hold-edit" href="<?=$this->escapeHtmlAttr($this->url('holds-edit', [], ['query' => ['selectedIDS[]' => $ilsDetails['updateDetails']]])) ?>" data-lightbox><?=$this->transEsc('Edit') ?></a></p>
                    <?php endif; ?>
                  </div>
                </td>
              </tr>
            <?php endforeach; ?>
          </table>
          <?php if ($this->cancelForm): ?></form> <?php endif; ?>
          <?php if ($template = $this->content()->findTemplateForLng("content/Additions/holds-post-list")): ?>
            <div class="holds-post-list"><?=$this->render($template)?></div>
          <?php endif; ?>
        <?php else: ?>
          <div class="useraccount-header">
            <h3><?=$this->transEsc('You do not have any holds or recalls placed') ?>.</h3>
          </div>
        <?php endif; ?>
      <?php endif; ?>
    </div>
  </div>
</div>

<?=$this->render('myresearch/notify-account-status.phtml', ['method' => 'holds', 'accountStatus' => $this->accountStatus]); ?>
<!-- END of: finna - holds/list.phtml -->
