<div class="input-row">
  <div class="service-type-container">
    <select name="service_type" class="js-location-search-service-type">
      <option value=""><?=$this->transEsc('Select Service')?></option>
      <?php foreach ($serviceList as $service): ?>
        <option value="<?=$this->escapeHtmlAttr($service)?>"><?=$this->escapeHtml($service)?></option>
      <?php endforeach; ?>
    </select>
  </div>
  <select name="service_location" class="js-location-search-service-location">
    <option value=""><?=$this->transEsc('All Municipalities')?></option>
    <?php foreach ($cityList as $city): ?>
      <option value="<?=$this->escapeHtmlAttr($city)?>"><?=$this->escapeHtml($city)?></option>
    <?php endforeach; ?>
  </select>
</div>
<div class="input-row">
  <label>
    <input type="checkbox" name="service_nearest" value="1">
    <?=$this->transEsc('Sort Results by Distance')?>
  </label>
  <label>
    <input type="checkbox" name="service_open" value="1">
    <?=$this->transEsc('Limit to Open Libraries')?>
  </label>
</div>
