<?php
  $ilsDetails = $driver->getExtraDetail('ils_details');
  // If this is a non-missing Solr record, we should display a link:
  if (is_a($driver, 'VuFind\\RecordDriver\\SolrDefault') && !is_a($driver, 'VuFind\\RecordDriver\\Missing')) {
    // Use ILS title if available since it may contain e.g. issue number
    if (!empty($ilsDetails['title'])) {
      $title = trim($ilsDetails['title'], '/: ');
    } else {
      $title = $driver->getTitle();
      $title = empty($title) ? $this->transEsc('Title not available') : $this->escapeHtml($title);
    }
    echo '<a href="' . $this->escapeHtmlAttr($this->recordLinker()->getUrl($driver))
      . '" class="record-title">' . $title . '</a>';
  } elseif (isset($ilsDetails['title']) && !empty($ilsDetails['title'])) {
    // If the record is not available in Solr, perhaps the ILS driver sent us a title we can show...
    echo '<span class="record-title">' . $this->escapeHtml($ilsDetails['title']) . '</span>';
  } else {
    // Last resort -- indicate that no title could be found.
    echo '<span class="record-title">' . $this->transEsc('Title not available') . '</span>';
  }
?>
<div class="record-core-metadata">
  <?php $formats = $driver->getFormats();
  if (count($formats) > 0): ?>
    <?=$this->record($driver)->getFormatList() ?>
    <br>
  <?php endif; ?>
  <?=$this->partial('myresearch/helpers/record-author.phtml', ['record' => $driver]);?>
  <?php if (!empty($ilsDetails['volume'])): ?>
    <strong><?=$this->transEsc('Issue')?>:</strong> <?=$this->escapeHtml($ilsDetails['volume'])?>
    <br>
  <?php endif; ?>

  <?php if (!empty($ilsDetails['publication_year'])): ?>
    <strong><?=$this->transEsc('Year of Publication')?>:</strong> <?=$this->escapeHtml($ilsDetails['publication_year'])?>
    <br>
  <?php endif; ?>
  <?php if ($this->displayItemBarcode && !empty($ilsDetails['barcode'])): ?>
    <strong><?=$this->transEsc('Barcode')?>:</strong> <?=$this->escapeHtml($ilsDetails['barcode'])?>
    <br>
  <?php endif; ?>
</div>
