<?php
    $role = null;
    if (!empty($author['roleName'])) {
        $role = $this->escapeHtml($author['roleName']);
    } elseif (!empty($author['role'])) {
        $role = mb_strtolower($this->transEsc('CreatorRoles::' . $author['role']), 'UTF-8');
    }
?>
<a href="<?=$this->record($record)->getLink('author', $author['name'])?>"><?=$this->escapeHtml($author['name'])?></a><?php if (!empty($author['date'])): ?><span class="author-date">, <?=$this->escapeHtml($author['date']) ?></span><?php endif; ?><?php if (!empty($role)): ?><span class="author-role">, <?=$role?></span><?php endif; ?><?php if (!empty($author['description'])): ?> <span class="author-description">(<?=$this->escapeHtml($author['description'])?>)</span><?php endif; ?>
