<!-- START of: finna - RecordDriver/DefaultRecord/container-links.phtml -->
<?php $containerTitle = $this->driver->getContainerTitle(); ?>
<?php $hostRecords = $this->driver->tryMethod('getHostRecords'); ?>
<?php if ($containerTitle || $hostRecords): ?>
  <div class="recordContainerReference">
    <?php
      $containerSource = $this->driver->getSourceIdentifier();
      $containerID = $this->driver->getContainerRecordID();
    ?>
    <div class="truncate-field">
      <span class="recordPublished"><?=$this->transEsc('Published in')?>: </span>
      <?php if ($hostRecords): ?>
        <?php foreach ($hostRecords as $i => $hostRecord): ?>
          <?=$i > 0 ? '<br>' : ''?>
          <?php if ($hostRecord['id'] || $hostRecord['title']): ?>
            <?php $link = $hostRecord['id'] ? $this->recordLinker()->getUrl($hostRecord['sourceId'] . '|' . $hostRecord['id']) : $this->record($this->driver)->getLink('title', $hostRecord['title']); ?>
            <a href="<?=$this->escapeHtmlAttr($link)?>"><?=$hostRecord['title'] !== '' ? $hostRecord['title'] : $hostRecord['mainHeading']?></a>
          <?php endif; ?>
          <?=$this->escapeHtml($hostRecord['reference']); ?>
        <?php endforeach; ?>
      <?php else: ?>
        <?php $link = $containerID ? $this->recordLinker()->getUrl($containerSource . '|' . $containerID) : $this->record($this->driver)->getLink('title', $containerTitle); ?>
        <a href="<?=$this->escapeHtmlAttr($link)?>"><?=$this->escapeHtml($containerTitle)?></a>
        <?php $ref = $this->driver->getContainerReference(); if (!empty($ref)) { echo $this->escapeHtml($ref); } ?>
      <?php endif; ?>
    </div>
  </div>
<?php endif; ?>
<!-- END of: finna - RecordDriver/DefaultRecord/container-links.phtml -->
