<?php //Don't add START and END comments ?>
<?php if (!empty($data)): ?>
<div class="truncate-field" data-rows="5">
  <?php foreach ($data as $field): ?>
  <div class="subjectLine" property="keywords">
    <?php $subject = ''; ?>
    <?php
      if (count($field) == 1) {
          $field = explode('--', $field[0]);
      }
    ?>
    <?php $i = 0;
    foreach ($field as $subfield): ?>
      <?=($i++ == 0) ? '' : ' &#8594; '?>
      <?php $subject = trim($subject . ' ' . $subfield); ?>
      <?=$this->record($this->driver)->getLinkedFieldElement('subject', $subfield, ['name' => $subject], ['class' => ['backlink']])?>
    <?php endforeach; ?>
  </div>
  <?php endforeach; ?>
</div>
<?php endif; ?>
