<?php //Don't add START and END comments ?>
<?php if (!empty($data)): ?>
  <ul class="truncate-field">
    <?php foreach ($data as $index => $item): ?>
      <?php
        $additional = [];
        if (!empty($item['fundingType'])) {
          $additional['funding-type'] = $this->escapeHtml($item['fundingType']);
        }
        if (!empty($item['amount'])) {
          $additional['amount'] = $this->escapeHtml($item['amount']);
        }
        $additional = $this->record($this->driver)->getAuthorityLinkAdditionalData($additional);
      ?>
      <li><?=$this->record($this->driver)->getLinkedFieldElement('author', $item['name'], $item, ['authorityType' => $item['type'] ?? null, 'additionalData' => $additional])?></li>
    <?php endforeach; ?>
  </ul>
<?php endif; ?>
