<?php $originationExt = $this->driver->tryMethod('getOriginationExtended'); //Don't add START and END comments ?>
<?php foreach ($originationExt ?? [['name' => $data]] as $idx => $origination): ?>
  <?=$idx > 0 ? '<br/>' : ''?>
  <?=$this->record($this->driver)->getAuthorityLinkElement('author', $origination['name'], $origination, ['showInlineInfo' => true, 'authorityType' => $author['type'] ?? null, 'date' => true])?>
<?php endforeach; ?>
