<?php //Don't add START and END comments ?>
<?php if (!empty($data)): ?>
<div class="truncate-field" data-rows="5">
  <?php foreach ($data as $field): ?>
  <div class="subjectLine" property="keywords">
    <?php $subject = ''; ?>
    <?php
      if (count($field['heading']) == 1) {
          $field['heading'] = explode('--', $field['heading'][0]);
      }
    ?>
    <?php $i = 0;
    foreach ($field['heading'] as $subfield): ?>
      <?php
        $first = $i++ === 0;
        $id = $first && isset($field['id']) ? $field['id'] : null;
        $ids = $first && isset($field['ids']) ? $field['ids'] : null;
        $authType = $field['authType'] ?? null;
        $detail = $first ? ($field['detail'] ?? null) : null;
      ?>
      <?= $first ? '' : ' &#8594; '?>
      <?php $subject = trim($subject . ' ' . $subfield); ?>
      <?=$this->record($this->driver)->getLinkedFieldElement($this->headingType ?? 'subject', $subfield, ['name' => $subject, 'id' => $id, 'ids' => $ids, 'description' => $detail], ['authorityType' => $authType, 'class' => ['backlink'], 'description' => true])?>
    <?php endforeach; ?>
  </div>
  <?php endforeach; ?>
</div>
<?php endif; ?>
