<?php if (!empty($data)): ?>
  <div class="additional-information">
    <?php foreach ($data as $i => $item): ?>
      <?= $i > 0 ? '<br>' : '' ?>
      <?= $this->escapeHtml($item['text']) ?>
      <?php $url = $item['url'] ?? '';
      if (!empty($url)): ?>
        (<a target="_blank" href="<?=$this->escapeHtmlAttr($this->proxyUrl($url))?>"><?=$this->escapeHtml($this->truncateUrl($url))?></a>)
      <?php endif; ?>
    <?php endforeach; ?>
  </div>
<?php endif; ?>
