<?php //Don't add START and END comments ?>
<?php if (!empty($data)): ?>
  <div class="truncate-field" data-rows="5">
    <?php foreach ($data as $field): ?>
      <?=!empty($field['part']) ? $this->escapeHtml($field['part']) . ': ' : ''?>
      <?php foreach ($field['details'] ?? [] as $detail): ?>
        <?=$this->escapeHtml($detail)?>
      <?php endforeach; ?>
      <br>
    <?php endforeach; ?>
  </div>
<?php endif; ?>
