<?php //Don't add START and END comments ?>
<?php if (!empty($data)): ?>
  <?php foreach ($data as $field): ?>
    <span>
      <?php $pubPlace = $field->getPlace();
      if (!empty($pubPlace)): ?>
        <span><?=$this->escapeHtml($pubPlace)?></span>
      <?php endif; ?>
      <?php $pubName = $field->getName();
      $pubDate = $field->getDate();
      if (!empty($pubName)): ?>
        <span><?=$this->escapeHtml($pubName)?><?php if (!empty($pubDate)): ?>, <?php endif; ?></span>
      <?php endif; ?>
      <?php if (!empty($pubDate)): ?>
        <span><?=$this->escapeHtml($pubDate)?></span>
      <?php endif; ?>
      <br>
    </span>
  <?php endforeach; ?>
<?php endif; ?>
