<?php //Don't add START and END comments ?>
<?php foreach ($data as $idx => $origination): ?>
  <?php
    $description = $origination['detail'] ?? '';
    if ($date = $origination['date'] ?? '') {
      if (!empty($description)) {
        $description .= ', ';
      }
      $description .= $date;
    }
    $origination['description'] = $description;
    unset($origination['date']);
  ?>
  <?=$idx > 0 ? '<br/>' : ''?>
  <?=$this->record($this->driver)->getLinkedFieldElement('author', $origination['name'], $origination, ['authorityType' => $origination['type'] ?? null, 'description' => true])?>
<?php endforeach; ?>
