<?php //Don't add START and END comments ?>
<?php if (!empty($data)): ?>
  <div class="other-related-material">
    <?php foreach ($data as $i => $item): ?>
      <?= $i > 0 ? '<br>' : '' ?>
      <?php if (!empty($item['url'])): ?>
        <a href="<?=$this->escapeHtmlAttr($item['url'])?>" target="_blank" aria-label="<?=$this->escapeHtmlAttr($item['text'])?> (<?=$this->transEscAttr('external_link')?>; <?=$this->transEscAttr('Open in a new window')?>)">
          <?=$this->icon('external-link') ?>
          <?=$this->escapeHtml($item['text'])?>
        </a>
      <?php else: ?>
        <?=$this->escapeHtml($item['text'])?>
      <?php endif; ?>
    <?php endforeach; ?>
  </div>
<?php endif; ?>
