<?php //Don't add START and END comments ?>
<div class="truncate-field">
<?php foreach ($data as $event): ?>
  <?php if ($event != $data[0]): ?><br><?php endif; ?>
  <?php if (!empty($event['name'])): ?><?=$this->escapeHtml($event['name'])?><br><?php endif; ?>
  <?php if (!empty($event['date'])): ?><?=$this->escapeHtml($event['date'])?><br><?php endif; ?>
  <?php if (!empty($event['methods'])): ?>
    <?=implode('<br>', array_map([$this, 'escapeHtml'], $event['methods']))?><br>
  <?php endif; ?>
  <?php if (!empty($event['materials'])): ?>
    <?=implode('<br>', array_map([$this, 'escapeHtml'], $event['materials']))?><br>
  <?php endif; ?>
  <?php if (!empty($event['places'])): ?>
    <?php foreach ($event['places'] as $placeEvent): ?>
      <?php if (!is_array($placeEvent)): ?>
        <?=$this->record($this->driver)->getLinkedFieldElement($this->headingType ?? 'subject', $placeEvent, ['name' => $placeEvent], ['class' => ['backlink'], 'description' => true])?>
      <?php else: ?>
        <?php
          $id = $placeEvent['id'] ?? null;
          $ids = $placeEvent['ids'] ?? null;
          $authType = $placeEvent['authType'] ?? null;
          $detail = $placeEvent['details'] ?? null;
        ?>
        <?=$this->record($this->driver)->getLinkedFieldElement($this->headingType ?? 'subject', $placeEvent[0], ['name' => $placeEvent[0], 'id' => $id, 'ids' => $ids, 'description' => $detail], ['authorityType' => $authType, 'class' => ['backlink'], 'description' => true])?>
      <?php endif; ?>
    <?php endforeach; ?>
  <?php endif; ?>
  <?php if (!empty($event['culture'])): ?><?=$this->escapeHtml($event['culture'])?><br><?php endif; ?>
  <?php if (!empty($event['actors'])): ?>
    <?php
      $displayActors = [];
      foreach ($event['actors'] as $actor) {
        $str = $actor['name'];
        if (!empty($actor['role'])) {
            $str .= ', ' . $actor['role'];
        }
        if (!empty($actor['birth']) || !empty($actor['death'])) {
            $str .= ', ';
            $sep = !empty($actor['birth']) && !empty($actor['death']) ? ' - ' : '--';
            $str .= ($actor['birth'] ?? '') . $sep . ($actor['death'] ?? '');
        }
        $displayActors[] = $this->escapeHtml($str);
      }
    ?>
    <?=implode(' ; ', $displayActors); ?>
    <br>
  <?php endif; ?>
  <?php if (!empty($event['descriptions'])): ?>
    <?=$this->recordFieldMarkdown()->toHtml(implode("\n\n", $event['descriptions'])) ?>
  <?php endif; ?>
<?php endforeach; ?>
</div>
