<?php
    $documents = $this->driver->getDocuments();
    static $i = 1;
    foreach ($documents as $i => $document):
        $language = $this->layout()->userLang;
        $description = $document['description'] ?: $this->translate('Download the file');
        $rights = $this->driver->getAccessRestrictionsType($language);
        $rightsDescription = $this->driver->getAccessRestrictions($language);
        $hasLink = isset($rights['link']) && !empty($rights['link']);
    ?>
    <li class="fulltextField">
        <div class="link-wrapper">  
            <a href="<?=$this->escapeHtmlAttr($this->url('record-downloadfile', [], ['query' => ['id' => $this->driver->getUniqueID(), 'index' => $i, 'format' => $document['format'], 'type' => 'document']]))?>" target="_blank" download>
                <i class="fa fa-download" aria-hidden="true"></i>
                <?=$this->escapeHtml($description)?>
            </a>
            <div class="copyright-wrapper">
                <span>
                    (<?=$this->escapeHtml($document['format'])?><?php if ($rights) { ?>:<?php } ?>
                </span>
                <span class="copyright-icons">
                    <?=$this->partial('Helpers/copyright-icons.phtml', ['copyright' => $rights['copyright']])?>
                </span>
                <?php if ($hasLink): ?>
                    <a class="copyright-description" href="<?=$this->escapeHtmlAttr($rights['link'])?>" target="_blank"><?=$this->escapeHtmlAttr($rights['copyright'])?></a>
                <?php else: ?>
                <span>
                    <?=$this->escapeHtmlAttr($rights['copyright']);?>
                </span>
                <?php endif; ?>
                <button class="show-hide-button show-info more-link" data-toggle="collapse" data-target="#cc_info_<?= $i ?>" aria-expanded="false">
                    <?=$this->transEsc('Additional Information')?> <?=$this->icon('truncate-more')?>)
                </button>
            </div>
        </div>
        <div id="cc_info_<?= $i ?>" class="cc-info collapse">
            <p class="access-rights"><?=$this->escapeHtmlAttr(implode("<br/>", $rightsDescription));?></p>
            <button class="hide-info less-link" data-toggle="collapse" data-target="#cc_info_<?= $i ?>" aria-expanded="false">
                <?=$this->transEsc('more_info_hide')?> <?=$this->icon('truncate-less')?>)
            </button>
        </div>
        
    </li>
<?php
    endforeach;
    $i++;
?>
