<?php
    $i = 0;
    foreach ($documents as $document):
        $language = $this->layout()->userLang;
        $description = $document['description'] ?: $this->translate('Download the file');
        $rights = $this->driver->getAccessRestrictionsType($language);
        $rightsDescription = $this->driver->getAccessRestrictions($language);
        $format = $document['format'] ?? null;
        $hasLink = isset($rights['link']) && !empty($rights['link']);
        $showRights = $document['downloadOnly'] ?? true;
        $externalLink ??= false;
    ?>
    <li class="fulltextField">
    <?php if ($showRights): ?>
        <div class="link-wrapper<?php if ($rightsDescription):?> additional-info<?php endif; ?>">
    <?php endif; ?>
        <?php if (!$externalLink): ?>
            <a href="<?=$this->escapeHtmlAttr($this->url('record-downloadfile', [], ['query' => ['id' => $this->driver->getUniqueID(), 'index' => $i, 'format' => $format, 'type' => 'document']]))?>" download rel="nofollow">
                <?=$this->icon('download') ?>
                <?=$this->escapeHtml($description)?>
            </a>
        <?php else: ?>
            <a href="<?=$this->escapeHtmlAttr($this->proxyUrl($document['url']))?>" target="_blank" aria-label="<?=$this->transEscAttr('external_online_link')?>"
                <?php if (!empty($document['posterUrl'])): ?> data-poster-url="<?= $this->escapeHtmlAttr($url['posterUrl']) ?>"<?php endif; ?>
                <?php if ($document['downloadOnly']): ?> download=""<?php endif; ?>
            >
                <?=$this->icon('external-link') ?> <?=$this->escapeHtml($this->translate('link_' . $description, null, $description))?>
            </a>
        <?php endif; ?>
        <?php if ($showRights): ?>
            <div class="copyright-wrapper">
                <span>
                    (<?php if ($format):?><?=$this->escapeHtml($format) ?>:<?php endif; ?>
                </span>
                <span class="copyright-icons">
                    <?=$this->partial('Helpers/copyright-icons.phtml', ['copyright' => $rights['copyright']])?>
                </span>
                <?php if ($hasLink): ?>
                    <a class="copyright-description" href="<?=$this->escapeHtml($rights['link'])?>" target="_blank"><?=$this->escapeHtmlAttr($rights['copyright'])?></a>
                <?php else: ?>
                <span>
                    <?=$this->escapeHtml($rights['copyright']);?>
                </span>
                <?php endif; ?>
                <?php if ($rightsDescription): ?>
                    <button class="show-hide-button show-info more-link collapsed" data-toggle="collapse" data-target="#cc_info_<?= $i ?>" aria-expanded="false">
                        <?=$this->transEsc('copyright_info_show')?> <?=$this->icon('truncate-more')?>
                    </button><span>)</span>
                <?php else: ?>
                    <span>)</span>
                <?php endif; ?>
            </div>
        </div>
        <?php if ($rightsDescription): ?>
            <div id="cc_info_<?= $i ?>" class="cc-info collapse">
                <?php foreach ($rightsDescription as $item): ?>
                    <p class="access-rights"><?=$this->escapeHtml((string)$item);?></p>
                <?php endforeach; ?>
                <button class="hide-info less-link" data-toggle="collapse" data-target="#cc_info_<?= $i ?>" aria-expanded="false">
                    <?=$this->transEsc('copyright_info_hide')?> <?=$this->icon('truncate-less')?>
                </button>
            </div>
        <?php endif; ?>
    <?php endif; ?>
    </li>
<?php
    $i++;
    endforeach;
?>
