<?php $showDownloadLinks ??= true; ?>
<?php foreach (array_values($documents) as $i => $document): ?>
    <?php
        $language = $this->layout()->userLang;
        $description = ($document['description'] ?? $document['desc'] ?? null) ?: $this->translate('Download the file');
        $rights = $this->driver->getAccessRestrictionsType($language);
        $rightsDescription = $this->driver->getAccessRestrictions($language);
        $format = $document['format'] ?? null;
        $hasLink = isset($rights['link']) && !empty($rights['link']);
    ?>
    <?php ob_start(); ?>
    <?php if ($showDownloadLinks): ?>
        <?php $aAttrs = [
            'download' => '',
            'rel' => 'nofollow',
        ]; ?>
        <a href="<?=$this->url('record-downloadfile', [], ['query' => ['id' => $this->driver->getUniqueID(), 'index' => $i, 'format' => $document['format'], 'type' => 'document']])?>" <?=$this->htmlAttributes($aAttrs)?>>
            <?=$this->icon('download')?>
            <?=$this->escapeHtml($description)?>
        </a>
    <?php else: ?>
        <?php $aAttrs = [
            'href' => $this->proxyUrl($document['url']),
            'target' => '_blank',
            'aria-label' => $this->translate('external_online_link'),
        ];
        if ($posterUrl = $document['posterUrl'] ?? null) {
            $aAttrs['data-poster-url'] = $posterUrl;
        }
        if ($downloadOnly = $document['downloadOnly'] ?? null) {
            $aAttrs['download'] = $downloadOnly;
        } ?>
        <a <?=$this->htmlAttributes($aAttrs)?>>
            <?=$this->icon('external-link')?>
            <?=$this->transEscWithPrefix('link_', $description)?>
        </a>
    <?php endif; ?>
    <?php $linkToResource = trim(ob_get_clean()); ?>
    <li class="fulltextField">
        <div class="link-wrapper<?php if ($rightsDescription):?> additional-info<?php endif; ?>">
            <?=$linkToResource ?>
            <?php if ($rights): ?>
                <div class="copyright-wrapper">
                    <span>(<?php if ($format):?><?=$this->escapeHtml($format) ?>:<?php endif; ?></span>
                    <span class="copyright-icons">
                        <?=$this->partial('Helpers/copyright-icons.phtml', ['copyright' => $rights['copyright']])?>
                    </span>
                    <?php if ($hasLink): ?>
                        <a class="copyright-description" href="<?=$this->escapeHtml($rights['link'])?>" target="_blank"><?=$this->escapeHtmlAttr($rights['copyright'])?></a>
                    <?php else: ?>
                        <span>
                            <?=$this->escapeHtml($rights['copyright']);?>
                        </span>
                    <?php endif; ?>
                    <?php if ($rightsDescription): ?>
                        <button class="show-hide-button show-info more-link collapsed" data-toggle="collapse" data-target="#cc_info_<?= $i ?>" aria-expanded="false">
                            <?=$this->transEsc('copyright_info_show')?> <?=$this->icon('truncate-more')?>
                        </button><span>)</span>
                    <?php else: ?>
                        <span>)</span>
                    <?php endif; ?>
                </div>
            <?php endif; ?>
        </div>
        <?php if ($rightsDescription): ?>
            <div id="cc_info_<?= $i ?>" class="cc-info collapse">
                <?php foreach ($rightsDescription as $item): ?>
                    <p class="access-rights"><?=$this->escapeHtml((string)$item);?></p>
                <?php endforeach; ?>
                <button class="hide-info less-link" data-toggle="collapse" data-target="#cc_info_<?= $i ?>" aria-expanded="false">
                    <?=$this->transEsc('copyright_info_hide')?> <?=$this->icon('truncate-less')?>
                </button>
            </div>
        <?php endif; ?>
    </li>
<?php endforeach; ?>
