<?php
    $documents = $this->driver->getDocuments();
    foreach ($documents as $i => $document):
        $language = $this->layout()->userLang;
        $description = $document['description'] ?: $this->translate('Download the file');
        $rights = $this->driver->getAccessRestrictionsType($language);
        $rightsDescription = $this->driver->getAccessRestrictions($language);
        $hasLink = isset($rights['link']) && !empty($rights['link']);
    ?>
    <li class="fulltextField">
        <div class="link-wrapper">  
            <a href="<?=$this->escapeHtmlAttr($this->url('record-downloadfile', [], ['query' => ['id' => $this->driver->getUniqueID(), 'index' => $i, 'format' => $document['format'], 'type' => 'document']]))?>" target="_blank" download>
                <i class="fa fa-download" aria-hidden="true"></i>
                <?=$this->escapeHtml($description)?>
            </a>
            <div class="copyright-wrapper">
                <span>
                    (<?=$this->escapeHtml($document['format'])?><?php if ($rights) { ?>:<?php } ?>
                </span>
                <span class="copyright-icons">
                    <?=$this->partial('Helpers/copyright-icons.phtml', ['copyright' => $rights['copyright']])?>
                </span>
                <?php if ($hasLink): ?>
                    <a class="copyright-description" href="<?=$this->escapeHtmlAttr($rights['link'])?>" target="_blank"><?=$this->escapeHtmlAttr($rights['copyright'])?></a>
                <?php else: ?>
                <span>
                    <?=$this->escapeHtmlAttr($rights['copyright']);?>
                </span>
                <?php endif; ?>
                <button class="show-info cc-info more-link" aria-expanded="false">
                    <?=$this->transEsc('Additional Information')?> <?=$this->icon('truncate-more')?>)
                </button>
                <button class="hide-info cc-info hide less-link" aria-expanded="false">
                    <?=$this->transEsc('more_info_hide')?> <?=$this->icon('truncate-less')?>)
                </button>
            </div>
        </div>
        <div id="extra_cc_info" class="cc-info hide">
            <p class="access-rights"><?=$this->escapeHtmlAttr(implode("<br/>", $rightsDescription));?></p>
        </div>
        <button class="cc-info hide hide-info less-link" aria-expanded="false">
            <?=$this->transEsc('more_info_hide')?> <?=$this->icon('truncate-less')?>
        </button>        
    </li>
<?php endforeach; ?>