<?php
$searchRoute = $this->searchAction ?: $this->searchOptions($this->driver->getSearchBackendIdentifier())->getSearchAction();
if (!($id = $this->id ?: $this->localId)) {
    // Use echo to ensure we don't return a line feed
    echo $this->url($searchRoute, [], ['query' => ['lookfor' => '"' . $this->lookfor . '"', 'type' => 'Subject']]);
} else {
    // Use echo to ensure we don't return a line feed
    echo $this->url(
        $searchRoute,
        [],
        ['query' => ['lookfor' => sprintf('topic:("%s") OR %s:("%s")^100000', $this->lookfor, \Finna\Search\Solr\AuthorityHelper::TOPIC_ID_FACET, $id)]]
    );
}
