<?php
  if (!($id = $this->id ?: $this->localId)) {
    return;
  }

  $searchBackendId = $this->driver->getSearchBackendIdentifier();
  $options = $this->searchOptions($searchBackendId);
  $searchRoute = $this->searchAction ?: $options->getSearchAction();
  $query = ['filter[]' => sprintf('%s:"%s"', \Finna\Search\Solr\AuthorityHelper::TOPIC_ID_FACET, $id)];
  if (($limit = $this->searchMemory()->getLastLimit($searchBackendId))
    && $limit !== $options->getDefaultLimit()
  ) {
    $query['limit'] = $limit;
  }
  echo $this->url($searchRoute, [], compact('query'));
