<?php // No ending line feed
$searchRoute = $this->searchAction ?: $this->searchOptions($this->driver->getSearchBackendIdentifier())->getSearchAction();
if (!($id = $this->id ?: $this->localId)) {
    echo $this->url($searchRoute, [], ['query' => ['lookfor' => '"' . $this->lookfor . '"', 'type' => 'Subject']]);
} else {
    echo $this->url(
        $searchRoute,
        [],
        ['query' => ['lookfor' => sprintf('geographic:("%s") OR %s:("%s")^100000', $this->lookfor, \Finna\Search\Solr\AuthorityHelper::GEOGRAPHIC_ID_FACET, $id)]]
    );
}
