<?php
  $searchBackendId = $this->driver->getSearchBackendIdentifier();
  $options = $this->searchOptions($searchBackendId);
  $searchRoute = $this->searchAction ?: $options->getSearchAction();
  $query = ['lookfor' => '"' . $this->lookfor . '"', 'type' => 'Author'];
  if (($limit = $this->searchMemory()->getLastLimit($searchBackendId))
    && $limit !== $options->getDefaultLimit()
  ) {
    $query['limit'] = $limit;
  }
  echo $this->url($searchRoute, [], compact('query'));
