<?php
  $recordImage = $this->recordImage($this->record($this->driver));
  $highResolution = $recordImage->getHighResolutionImages((int)$this->index);
  $largeImage = $recordImage->getLargeImageWithInfo($this->index)['url'] ?? false;

  $allImages = $this->driver->tryMethod('getAllImages', [$this->layout()->userLang]);
  $imageDescription = $allImages[$this->index]['description'] ?? '';
  $rights = $recordImage->getImageRights($this->index);

  $formats = $this->driver->tryMethod('getFormats');
  $translatedFormat = $this->transEsc(end($formats));
  $recordType = $this->driver->tryMethod('getRecordFormat');
  $videoScripts = $this->partial('Helpers/videojs-urls.phtml');
?>
<div id="popup-content-collapse" class="content">
  <h3 id="popup-image-title" class="title"><?=$this->escapeHtml($this->driver->getTitle())?></h3>
<?php
$otherTitles = array_merge(
    $this->driver->tryMethod('getUniformTitles') ?? [],
    $this->driver->tryMethod('getAlternativeTitles') ?? []
);
if ($otherTitles):?>
    <div class="result-other-titles">
      <?=implode(' &ndash; ', array_map($this->escapeHtml, $otherTitles)) ?>
    </div>
  <?php endif; ?>
  <div class="author-and-dates">
    <?php if ('lido' !== $recordType): ?>
      <p>
        <?php if ($author = $this->driver->getPrimaryAuthor()): ?>
          <?=$this->escapeHtml($author) ?>
        <?php endif; ?>
        <?php if ($dates = $this->driver->tryMethod('getResultDateRange')): ?>
          <?=$this->escapeHtml($dates[0]);?><?php if (isset($dates[1]) && $dates[1] != $dates[0]): ?>&ndash;<?=$this->escapeHtml($dates[1])?><?php endif; ?>
        <?php else: ?>
          <?php foreach ($this->driver->getPublicationDates() as $date): ?>
            <?=$this->escapeHtml($date) ?>
          <?php endforeach ?>
        <?php endif; ?>
      </p>
    <?php else: ?>
      <?php if ($results = $this->driver->getNonPresenterAuthors()): ?>
        <div class="truncate-field">
        <?php foreach($results as $index => $author): ?>
          <?=($index > 0 ? '; ' : '')?><?=$this->escapeHtml($author['name'])?><?php if (!empty($author['role'])): ?>, <?=$this->escapeHtml($author['role'])?><?php endif; ?>
        <?php endforeach; ?>
        <?php if ($dates = $this->driver->getResultDateRange()): ?>
          <?=$this->escapeHtml($dates[0]);?><?php if (isset($dates[1]) && $dates[1] != $dates[0]): ?>&ndash;<?=$this->escapeHtml($dates[1])?><?php endif; ?>
        <?php endif; ?>
        <?php if (($results = $this->driver->getSubjectDates()) && !isset($dates[0])): ?>
          <?=implode('<br/>', array_map([$this, 'escapeHtml'], $results))?>
        <?php endif; ?>
        </div>
      <?php endif; ?>
    <?php endif; ?>
  </div>
  <div class="building">
    <?=$this->escapeHtml($this->organisationDisplayName($this->driver)) ?>
  </div>
  <div class="popup-link-buttons">
    <div class="record-link"><a href="<?=$this->escapeHtmlAttr($this->recordLinker()->getUrl($this->driver)) ?>"><i class="fa fa-arrow-circle-right"></i> <span><?=$this->transEsc('To the record') ?></span></a></div>
  </div>
  <div class="summary loading">
    <div data-rows="6" class="truncate-field">
      <?php if ('marc' === $recordType): ?>
        <p></p>
      <?php else: ?>
        <?php if ($imageDescription): ?>
          <div id="popup-image-description" class="image-description">
            <p><strong><?=$this->transEsc('Image') ?>:</strong> <?=$this->escapeHtml($imageDescription)?></p>
          </div>
        <?php endif; ?>
        <?php if ($summaries = $this->driver->tryMethod('getDescriptions') ?? $this->driver->tryMethod('getSummary')): ?>
          <?php if ('qdc' === $recordType): ?>
            <?= $this->recordFieldMarkdown()->toHTML(implode("\n\n", $summaries), "\n")?>
          <?php elseif (in_array($recordType, ['lido', 'ead'])): ?>
            <?php foreach ($summaries as $summary): ?>
              <?= $this->recordFieldMarkdown()->toHtml($summary) ?>
            <?php endforeach; ?>
          <?php elseif ('forward' === $recordType): ?>
            <?php foreach ($summaries as $summary): ?>
              <p><?=$this->cleanHtml($summary)?></p>
            <?php endforeach ?>
          <?php elseif ($summary = $summaries[0] ?? false): ?>
            <div class="truncate-field wide">
              <p class="summary"><?$this->cleanHtml($summary)?></p>
            </div>
          <?php endif; ?>
        <?php endif; ?>
      <?php endif ?>
    </div>
  </div>
  <?php if (!empty($listNotes)): ?>
    <div class="list-notes">
      <strong><?=$this->transEsc('Note')?>:</strong>
      <ul>
        <?php foreach ($listNotes as $note): ?>
          <li><?=$this->markdown()->toHtml($note) ?></li>
        <?php endforeach; ?>
      </ul>
    </div>
  <?php endif; ?>
  <div class="popup-link-buttons">
    <?php
      $urls = $this->driver->getURLs();
      $onlineURLs = $this->driver->getOnlineURLs();
      $mergedData = $this->driver->tryMethod('getMergedRecordData');
      $images = $this->record($this->driver)->getAllRecordImageUrls();
      $videoUrlElement = [
        'class' => 'videourl fulltext btn btn-primary',
        'data-scripts' => $videoScripts
      ];
      $this->htmlElement()->addAttributeTemplate('video-base', $videoUrlElement);
    ?>
    <?php if (!empty($urls) || !empty($onlineURLs) || !empty($mergedData['urls'])): ?>
      <?php $index = 0; ?>
      <?php $renderedURLs = []; ?>
      <?php if (!empty($urls)): ?>
        <?php foreach ($urls as $url): ?>
          <?php
            $renderedURLs[] = $url['url'];
            if (isset($images[$url['url']])) {
              continue;
            }
            $desc = $url['desc'] ?? $this->truncateUrl($url['url']);
            $current = [
              'title' => $url['url']
            ];
            $isVideo = !empty($url['videoSources']);
            $embed = $this->recordLinker()->getEmbeddedVideo($url['url']);
            if ($embed !== '') {
              $current[$embed] = '';
              $isVideo = true;
            }
            if ($isVideo) {
              if (isset($type) && $type === 'SolrEad') {
                $desc = $embeddedVideo === 'data-embed-iframe' ? $this->translate('format_Video') : $this->translate('link_' . $url['desc'], null, $url['desc']);
              } elseif (isset($type) && $type === 'SolrForward') {
                $desc = $this->translate('default::link_' . $desc, null, $desc);
              } else {
                $desc = $embeddedVideo === 'data-embed-iframe' ? $this->translate('format_Video') : $desc;
              }
              $desc = $this->escapeHtml($desc);
              $current['data-link'] = $this->proxyUrl($url['url']);
              $current['data-video-sources'] = json_encode($url['videoSources']);
            } else {
              $link = [
                'href' => $this->proxyUrl($url['url']),
                'target' => '_blank'
              ];
              $current = array_merge($current, $link);
            }
            if (!empty($url['embed']) && $url['embed'] === 'video') {
              $current['data-embed-video'] = '';
            }
          ?>
          <div class="record-online-link">
            <?php if ($isVideo): ?>
              <button <?= $this->htmlElement()->getAttributes($current, 'video-base') ?>>
                <i class="fa fa-external-link"></i> <?= $desc ?>
              </button>
            <?php else: ?>
              <a <?= $this->htmlElement()->getAttributes($current); ?>>
                <i class="fa fa-external-link"></i><?php if (count($urls) == 1): ?>  <?=$this->transEsc('open_online_link', ['%%format%%' => $translatedFormat])?><?php else: ?><?=$this->transEsc('default::link_' . $desc, null, $desc) ?><?php endif; ?>
              </a>
            <?php endif; ?>
          </div>
          <?php $index++; ?>
          <?php if ($index > 4): ?>
            <div>...</div>
            <?php break; ?>
          <?php endif; ?>
        <?php endforeach; ?>
      <?php endif; ?>
      <?php if (!empty($onlineURLs) || !empty($mergedData['urls'])): ?>
        <?php foreach (!empty($mergedData['urls']) ? $mergedData['urls'] : $onlineURLs as $url): ?>
          <?php if (isset($images[$url['url']]) || in_array($url['url'], $renderedURLs)) { continue; } ?>
          <div class="record-online-link"><a href="<?=$this->escapeHtmlAttr($this->proxyUrl($url['url'])) ?>"<?=!empty($url['embed']) && $url['embed'] == 'iframe' ? ' data-embed-iframe' : '' ?> target="_blank" title="<?=$this->escapeHtmlAttr($url['url']) ?>"><i class="fa fa-external-link"></i> <?php if (count($onlineURLs) == 1 || count($mergedData['urls'] ?? []) == 1): ?> <?=$this->transEsc('open_online_link', ['%%format%%' => $translatedFormat])?><?php else: ?><?=!empty($url['text']) ? $this->transEsc('default::link_' . $url['text'], null, $url['text']) : $this->escapeHtml($this->truncateUrl($url['url'])) ?><?php endif; ?></a>
          <?php if ($url['source']): ?>
            <span class="online-source"><?=is_array($url['source']) ? '(' . $this->transEsc('Multiple Organisations') . ')' : '';?></span>
          <?php endif; ?>
          </div>
        <?php endforeach; ?>
      <?php endif; ?>
    <?php endif; ?>
    <?php if ($this->userlist()->getMode() !== 'disabled'): ?><div class="save-record-link"><a href="<?=$this->escapeHtmlAttr($this->recordLinker()->getActionUrl($this->driver, 'Save'))?>" class="save-record" data-lightbox data-id="<?=$this->escapeHtmlAttr($this->driver->getUniqueId()) ?>" title="<?=$this->transEsc('Add to favorites')?>"><i class="fa fa-heart"></i> <span><?=$this->transEsc('Add to favorites')?></span></a></div><?php endif; ?>
    <?= $this->context($this)->renderInContext('RecordDriver/DefaultRecord/image-download.phtml', ['index' => $this->index, 'rights' => $rights, 'image' => ['urls' => ['large' => $largeImage]], 'hiRes' => $highResolution ?? false]) ?>
    <?= $this->record($this->driver)->renderTemplate('image-information.phtml', ['index' => 'popup', 'image' => $allImages[$this->index] ?? []]); ?>
  </div>
  <?php if ($this->driver->getSourceIdentifier() !== 'SolrAuth'): ?>
    <?= $this->context($this)->renderInContext('RecordDriver/DefaultRecord/image-rights.phtml', ['rights' => $rights, 'truncateLicense' => true]); ?>
  <?php endif ?>
  <?=$this->render('record/record-organisation-menu.phtml') ?>
  <div style="clear: both;"></div>
</div>
<?=
$this->matomo([
  'context' => 'lightbox',
  'record' => $this->driver,
  'action' => 'imagePopup',
  'recordUrl' => $this->recordLinker()->getUrl($this->driver)
]);
?>

<?php
  $script = <<<JS
finna.layout.initOrganisationPageLinks();
JS;
  echo $this->inlineScript(\Laminas\View\Helper\HeadScript::SCRIPT, $script, 'SET');
?>
