<!-- START of: finna - RecordDriver/DefaultRecord/record-image-paginator.phtml -->
<?php
  $isList = ($type === 'list' || $type === 'list grid');
?>
<?php if ($type === 'record' || !$this->userAgent()->isBot()): ?>
  <?php
    $ind = 0;
    $paginatedLinks = [];
    $recordImage = $this->recordImage($this->record($this->driver));
  ?>
  <?php foreach ($images as $img): ?>
    <?php
      $originalImageData = $recordImage->getMasterImageWithInfo($ind);
      $originalImage = $originalImageData['url'] ?? false;
      $obj = [
        'type' => 'image',
        'small' => $img['urls']['small'],
        'medium' => $img['urls']['medium'],
        'large' => $img['urls']['large'] ?? $img['urls']['medium'],
        'master' => $originalImage ?: null,
        'index' => $ind++,
        'alt' => $img['description'],
        'description' => $img['description'],
        'title' => $this->transEsc('Image') . ' ' . $ind
      ];
      $paginatedLinks[] = $obj;
    ?>
  <?php endforeach; ?>
  <?php if (!empty($models)) {
    $translations = $this->jsTranslations()->getJSONFromArray(
        [
            'Information of model' => 'Information of model',
            'Vertices' => 'Vertices',
            'Triangles' => 'Triangles',
            'model_help_pc_html' => 'model_help_pc_html',
            'model_help_mobile_html' => 'model_help_mobile_html',
            'model_loading_file' => 'model_loading_file'
        ]
    );
    echo $this->inlineScript(\Laminas\View\Helper\HeadScript::SCRIPT, "VuFind.addTranslations($translations);", 'SET');
    $modelScripts = $this->partial('Helpers/modeljs-urls.phtml');
    $settings = $this->driver->getModelSettings();
    $settings['texturePath'] = $this->imageSrc()->getSourceAddress('model_background.jpg', true);
    $previewImages = $this->driver->allowModelPreviewImages();
    foreach ($models as $index => $model):
      foreach ($model as $format => $data):
        $settings['modelload'] = [
          'id' => $this->driver->getUniqueId(),
          'index' => $index,
          'format' => $format,
          'source' => $this->driver->getSourceIdentifier()
        ];

        $tmp = [
          'type' => 'model',
          'modelsettings' => json_encode($settings ?? []),
          'scripts' => $modelScripts,
          'format' => $format
        ];

        $override = [
          'small' => null,
          'medium' => null,
          'large' => null,
          'master' => null,
          'index' => $index,
          'title' => $this->transEsc('Image') . ' ' . $ind++,
        ];

        if (!empty($paginatedLinks[$index])) {
          if ($previewImages) {
            $paginatedLinks[$index] = array_merge($paginatedLinks[$index], $tmp);
          } else {
            $paginatedLinks[$index] = array_merge($paginatedLinks[$index], $tmp, $override);
          }
        } else {
          $paginatedLinks[] = array_merge($tmp, $override);
        }
      endforeach;
    endforeach;
  } ?>
  <?php if (count($paginatedLinks) > 0): ?>
    <?php
      $settings = [
        'recordId' => $this->driver->getUniqueId(),
        'recordType' => $this->driver->tryMethod('getRecordFormat'),
        'recordSource' => $this->driver->tryMethod('getSourceIdentifier'),
        'enableImageZoom' => $this->record($this->driver)->getImagePopupZoom(),
        'maxRows' => 3,
        'iconlabelClass' => "format-" . $this->record($this->driver)->getFormatClass(end($formats)),
        'isList' => $type === 'list' || $type === 'list grid',
        'recordCovers' => 'recordcovers',
        'displayIcon' => $displayIcon,
        'triggerClick' => $this->imageClick ?? 'modal'
      ];
    ?>
  <?php endif; ?>
  <?php if (!$this->userAgent()->isBot()): ?>
    <?php if (!empty($images[0]['urls']['medium']) || !empty($images[0]['urls']['large']) || !empty($models)): ?>
      <div class="recordcover-container">
        <button class="next-image left" type="button"><i class="fa fa-chevron-left"></i><span class="sr-only"><?= $this->transEsc('previous_image') ?></span></button>
        <a class="image-popup-trigger init" href="<?=$this->escapeHtmlAttr($this->recordLinker()->getUrl($this->driver)) ?>" data-images="<?=htmlspecialchars(json_encode($paginatedLinks ?? []), ENT_QUOTES, 'UTF-8');?>" data-settings="<?=htmlspecialchars(json_encode($settings ?? []), ENT_QUOTES, 'UTF-8');?>">
          <div class="iconlabel format-<?=$this->record($this->driver)->getFormatClass(end($formats))?>"></div>
          <?php if (!$isList && !empty($models)): ?>
            <div class="iconlabel fa-finna-3d"></div>
            <div class="show-3d btn btn-primary"><?=$this->transEsc('Display 3D');?></div>
          <?php endif; ?>
          <div class="paginator-info"><span class="image-index"></span></div>
          <img src="<?=$this->imageSrc()->getDataPixel()?>" data-src="<?=$this->url('cover-unavailable')?>" class="recordcover<?= ($images[0]['pdf'] ?? false) ? ' pdf-cover' : ''?>" alt="<?=$this->transEsc('No Cover Image')?>"/>
          <?php if (!$isList): ?>
            <div id="inline-viewer"></div>
          <?php endif; ?>
        </a>
        <span class="hidden-trigger" hidden></span>
        <button class="next-image right" type="button"><i class="fa fa-chevron-right"></i><span class="sr-only"><?= $this->transEsc('next_image') ?></span></button>
      </div>
    <?php endif; ?>
  <?php else: ?>
    <a href="<?=$this->escapeHtmlAttr($img['urls']['large'] ?? $img['urls']['medium']) ?>"><?=($ind + 1)?></a>
  <?php endif; ?>
  <div class="recordcover-image-detail">
    <p class="image-description">
    </p>
  </div>
  <div class="recordcovers <?=$this->escapeHtmlAttr($type)?>">
    <button class="left-button" type="button" title="<?= $this->transEsc('previous_images') ?>"><i class="fa fa-handle-left"></i><span class="sr-only"><?= $this->transEsc('previous_images') ?></span></button>
    <div class="track-holder paginator-mask">
      <div class="finna-element-track"></div>
    </div>
    <button class="right-button" type="button" title="<?= $this->transEsc('next_images') ?>"><i class="fa fa-handle-right"><span class="sr-only"><?= $this->transEsc('next_images') ?></span></i></button>
    <div class="paginator-info"><span class="image-index"></span></div>
  </div>
  <div class="recordcovers-more more-area">
    <button type="button" class="show-more-images"><?= $this->transEsc('more') ?> <i class="fa fa-arrow-down"></i></button>
    <button type="button" class="show-less-images"><?= $this->transEsc('less') ?> <i class="fa fa-arrow-up"></i></button>
  </div>
<?php endif;?>
<!-- END of: finna - RecordDriver/DefaultRecord/record-image-paginator.phtml -->
