<!-- START of: finna - RecordDriver/DefaultRecord/record-video-player.phtml -->
<?php
  $inlineVideo = $this->config()->inlineVideoEnabled();
  if (empty($this->inlineVideo) && $this->config()->inlineVideoEnabled()) {
    return;
  }
  $this->partial('Helpers/videojs-translations.phtml');
?>
<div class="video-warnings">
  <?php
    $warningImageUrls = [];
  ?>
  <div class="warnings-wrapper">
    <?php foreach ($videoUrls as $index => $url): ?>
      <div class="video-warning hidden" data-index="<?=$index?>">
        <?php if (!empty($url['warnings'])): ?>
          <?php $lang = $this->layout()->userLang; ?>
          <?php foreach ($url['warnings'] as $warning): ?>
            <?php if (!isset($warningImageUrls[$warning])) {
              $extra = '';
              if ($warning === 'age_rating_for_all_ages') {
                $extra = $lang === 'sv' ? '_sv' : '_fi';
              }
              // Lets see if swedish version of image is needed
              $warningImageUrls[$warning] = $this->imageSrc()->getSourceAddress($warning . $extra, true);
            } ?>
            <?php if (!empty($warningImageUrls[$warning])): ?>
              <span class="video-warning-icon"><img title="<?=$this->transEscAttr($warning)?>" data-src="<?=$this->escapeHtmlAttr($warningImageUrls[$warning])?>"></span>
            <?php endif; ?>
          <?php endforeach; ?>
        <?php endif; ?>
      </div>
    <?php endforeach; ?>
  </div>
</div>
<div class="video-buttons<?=$inlineVideo && count($videoUrls) === 1 ? ' hidden' : ''?>">
  <div class="video-accordion <?= $inlineVideo ? 'container' : ''?>">
    <?php $i = 0; ?>
    <?php foreach ($videoUrls as $url): ?>
      <?php
      $embeddedVideo = $this->recordLinker()->getEmbeddedVideo($url['url']);
      $desc = $url['desc'] ?? $this->truncateUrl($url['url']);
      if (($type ?? '') === 'SolrEad') {
        $desc = $embeddedVideo === 'data-embed-iframe' ? $this->translate('format_Video') : $this->translate('link_' . $url['desc'], null, $url['desc']);
      } elseif (($type ?? '') === 'SolrForward') {
        $desc = $this->translate('default::link_' . $desc, null, $desc);
      } elseif (($type ?? '') === 'SolrLido') {
        $desc = $desc ?: $this->translate('format_Video');
      } else {
        $desc = $embeddedVideo === 'data-embed-iframe' ? $this->translate('format_Video') : $desc;
      }

      $popupId = ($embeddedVideo ?? '') === 'data-embed-iframe' ? 'finna-iframe' : 'finna-video';
      $type = ($embeddedVideo ?? '') === 'data-embed-iframe' ? 'iFrame' : 'video';
      ?>
      <finna-video
        class="video-link-container active-video"
        popup-id="<?=$popupId?>"
        type="<?=$type?>"
        index="<?=$i?>"
        source="<?=$this->escapeHtmlAttr($this->proxyUrl($url['url']))?>"
        title="<?=$this->escapeHtmlAttr($url['url'])?>"
        aria-label="<?=$this->transEscAttr('Link to video') . ' ' . $this->escapeHtmlAttr($desc)?>"
        consent-service="recordvideo"
        consent-categories="<?=$this->transEscAttr($this->plugin('cookieConsent')->getCategoryTitleForService('recordvideo'))?>"
        <?php if ($inlineVideo): ?>
          embed-parent="inline-video"
          active ="<?= $i === 0 ? 'true' : 'false'?>"
        <?php endif; ?>
        <?php if (!empty($url['videoSources'])): ?>
          video-sources="<?=htmlspecialchars(json_encode($url['videoSources']), ENT_QUOTES, 'UTF-8');?>"
        <?php endif; ?>
      >
        <?=$this->icon('video-play', 'video-play-icon') ?>
        <span class="video-desc"><?=$this->escapeHtml($this->truncate(ucfirst($desc), 30))?></span>
      </finna-video>
      <?php $i++; ?>
    <?php endforeach; ?>
  </div>
</div>
<!-- END of: finna - RecordDriver/DefaultRecord/record-video-player.phtml -->
