<!-- START of: finna - RecordDriver/DefaultRecord/record-image-paginator.phtml -->
<?php
  $isList = ($type === 'list' || $type === 'list grid');
?>
<?php if ($type === 'record' || !$this->userAgent()->isBot()): ?>
  <?php if (count($images) > 0): ?>
    <?php
      $settings = [
        'recordId' => $this->driver->getUniqueId(),
        'recordType' => $this->driver->tryMethod('getRecordFormat'),
        'recordSource' => $this->driver->tryMethod('getSourceIdentifier'),
        'enableImageZoom' => $this->record($this->driver)->getImagePopupZoom(),
        'maxRows' => 3,
        'iconlabelClass' => "format-" . $this->record($this->driver)->getFormatClass(end($formats)),
        'isList' => $type === 'list' || $type === 'list grid',
        'recordCovers' => 'recordcovers',
        'displayIcon' => $displayIcon,
        'triggerClick' => $this->imageClick ?? 'modal',
      ];
      if ($this->driver->tryMethod('getModels')) {
        $modelSettings = $this->driver->tryMethod('getModelSettings', [], []);
        $settings['modelTranslations'] = $this->partial('Helpers/modeljs-translations.phtml');
        $settings['viewerDebug'] = $modelSettings['debug'] ?? false;
      }
    ?>
  <?php endif; ?>
  <?php if (!$this->userAgent()->isBot()): ?>
    <?php if (!empty($images[0]['urls']['medium']) || !empty($images[0]['urls']['large'])): ?>
      <div class="recordcover-container">
        <button class="next-image left" type="button"><i class="fa fa-chevron-left"></i><span class="sr-only"><?= $this->transEsc('previous_image') ?></span></button>
        <a class="image-popup-trigger init" draggable="false" href="<?=$this->escapeHtmlAttr($this->recordLinker()->getUrl($this->driver)) ?>" data-images="<?=htmlspecialchars(json_encode($images ?? []), ENT_QUOTES, 'UTF-8');?>" data-settings="<?=htmlspecialchars(json_encode($settings ?? []), ENT_QUOTES, 'UTF-8');?>">
          <div class="iconlabel format-<?=$this->record($this->driver)->getFormatClass(end($formats))?>"></div>
          <div class="paginator-info"><span class="image-index"></span></div>
          <img src="<?=$this->imageSrc()->getDataPixel()?>" data-src="<?=$this->url('cover-unavailable')?>" class="recordcover<?= ($images[0]['pdf'] ?? false) ? ' pdf-cover' : ''?>" alt="<?=$this->transEsc('No Cover Image')?>"/>
        </a>
        <span class="hidden-trigger" hidden></span>
        <button class="next-image right" type="button"><i class="fa fa-chevron-right"></i><span class="sr-only"><?= $this->transEsc('next_image') ?></span></button>
      </div>
    <?php endif; ?>
  <?php else: ?>
    <a href="<?=$this->escapeHtmlAttr($img['urls']['large'] ?? $img['urls']['medium']) ?>">1</a>
  <?php endif; ?>
  <div class="recordcover-image-detail">
    <p class="image-description">
    </p>
  </div>
  <div class="recordcovers <?=$this->escapeHtmlAttr($type)?>">
    <button class="left-button" type="button" title="<?= $this->transEsc('previous_images') ?>"><i class="fa fa-handle-left"></i><span class="sr-only"><?= $this->transEsc('previous_images') ?></span></button>
    <div class="track-holder paginator-mask">
      <div class="finna-element-track"></div>
    </div>
    <button class="right-button" type="button" title="<?= $this->transEsc('next_images') ?>"><i class="fa fa-handle-right"><span class="sr-only"><?= $this->transEsc('next_images') ?></span></i></button>
    <div class="paginator-info"><span class="image-index"></span></div>
  </div>
  <div class="recordcovers-more more-area">
    <button type="button" class="show-more-images"><?= $this->transEsc('more') ?> <i class="fa fa-arrow-down"></i></button>
    <button type="button" class="show-less-images"><?= $this->transEsc('less') ?> <i class="fa fa-arrow-up"></i></button>
  </div>
<?php endif;?>
<!-- END of: finna - RecordDriver/DefaultRecord/record-image-paginator.phtml -->
