<!-- START of: finna - RecordDriver/DefaultRecord/record-video-player.phtml -->
<?php
  $videoElementBase = [
    'class' => 'video-link-container active-video',
    'type' => 'button'
  ];
  $this->htmlElement()->addAttributeTemplate('video-base', $videoElementBase);
  $videoScripts = $this->partial('Helpers/videojs-urls.phtml');
  $inlineVideo = $this->config()->inlineVideoEnabled();
?>
<?php if ($inlineVideo): ?>
  <div class="inline-video-container hidden">
    <div class="inline-video" id="inline-video"></div>
<?php endif; ?>
<div class="video-warnings">
  <?php
    $warningImageUrls = [];
  ?>
  <div class="container">
    <?php foreach ($videoUrls as $index => $url): ?>
      <div class="video-warning hidden" data-index="<?=$index?>">
        <?php if (!empty($url['warnings'])): ?>
          <?php $lang = $this->layout()->userLang; ?>
          <?php foreach ($url['warnings'] as $warning): ?>
            <?php if (!isset($warningImageUrls[$warning])) {
              $extra = '';
              if ($warning === 'age_rating_for_all_ages') {
                $extra = $lang === 'sv' ? '_sv' : '_fi';
              }
              // Lets see if swedish version of image is needed
              $warningImageUrls[$warning] = $this->imageSrc()->getSourceAddress($warning . $extra);
            } ?>
            <?php if (!empty($warningImageUrls[$warning])): ?>
              <span class="video-warning-icon"><img title="<?=$this->transEscAttr($translation)?>" data-src="<?=$this->this->escapeHtmlAttr($warningImageUrls[$warning])?>"/></span>
            <?php endif; ?>
          <?php endforeach; ?>
        <?php endif; ?>
      </div>
    <?php endforeach; ?>
  </div>
</div>
<div class="video-buttons">
  <div class="video-accordion <?= $inlineVideo ? 'container' : ''?>">
    <?php $i = 0; ?>
    <?php foreach ($videoUrls as $url): ?>
      <?php
      $embeddedVideo = $this->recordLink()->getEmbeddedVideo($url['url']);
      $desc = $url['desc'] ?? $this->truncateUrl($url['url']);

      if (isset($type) && $type === 'SolrEad') {
        $desc = $embeddedVideo === 'data-embed-iframe' ? $this->translate('format_Video') : $this->translate('link_' . $url['desc'], null, $url['desc']);
      } elseif (isset($type) && $type === 'SolrForward') {
        $desc = $this->translate('default::link_' . $desc, null, $desc);
      } else {
        $desc = $embeddedVideo === 'data-embed-iframe' ? $this->translate('format_Video') : $desc;
      }
      $description = $this->escapeHtml($desc);

      $currentVideo = [
        'data-link' => $this->proxyUrl($url['url']),
        'title' => $url['url'],
      ];

      if (!empty($embeddedVideo)) {
        if ($inlineVideo) {
          $currentVideo['data-inline-iframe'] = '';
        }
        $currentVideo['data-embed-url'] = $this->recordLink()->getEmbeddedVideoUrl($url['url']);
        $currentVideo[$embeddedVideo] = '';
      }

      if (!empty($url['videoSources'])) {
        $currentVideo['data-video-sources'] = json_encode($url['videoSources']);
        $currentVideo['data-scripts'] = $videoScripts;
      }

      if (!empty($url['embed']) && $url['embed'] === 'video') {
        if ($inlineVideo) {
          $currentVideo['data-inline'] = '';
        }
        $currentVideo['data-embed-video'] = '';
      }

      $currentVideo['data-index'] = $i++;
      ?>
      <button <?=$this->htmlElement()->getAttributes($currentVideo, 'video-base');?>
        aria-label="<?= $this->transEsc('Link to video') . ' ' . $description ?>" aria-haspopup="<?= $inlineVideo ? 'false' : 'true'?>"
      >
        <i class="fa fa-play-circle"></i>
        <span class="video-desc"><?=$this->truncate(ucfirst($description), 30)?></span>
      </button>
    <?php endforeach; ?>
  </div>
</div>
<?php if ($inlineVideo): ?></div><?php endif; ?>
<!-- END of: finna - RecordDriver/DefaultRecord/record-video-player.phtml -->
