<!-- START of: finna - RecordDriver/DefaultRecord/record-image.phtml -->
<?php
  $isList = $type == 'list' || $type === 'list grid';
  $formats = $this->driver->tryMethod('getFormats');
  $enableImagePopupZoom = $this->record($this->driver)->getImagePopupZoom();
  if (!$isList) {
    $models = $this->driver->tryMethod('getModels');
    $modelPreviewImages = $this->driver->tryMethod('allowModelPreviewImages');
  }
?>
<div class="record-image-container <?= empty($images[0]['urls']['large']) && empty($images[0]['urls']['medium']) ? 'hide-image' : ''?>">
  <div class="recordcover-holder paginate" aria-hidden="true" data-format="<?=$this->transEsc(end($formats))?>" data-noimage="<?=$this->transEsc('no_image')?>">
  <?= $this->record($this->driver)->renderTemplate(
    'record-image-paginator.phtml',
    ['images' => $images, 'type' => $type, 'formats' => $formats, 'enableImagePopupZoom' => $enableImagePopupZoom,
     'numOfImages' => $numOfImages ?? null, 'displayIcon' => $displayIcon ?? false, 'models' => $models ?? []
    ]
  ); ?>
  </div>
  <?php if (!$isList): ?>
    <?php $ind = 0; ?>
    <?php foreach ($images as $image): ?>
      <?php $rights = $image['rights']; ?>
      <div class="image-details-container<?=$ind > 0 ? ' hidden' : '' ?> text-left" data-img-index="<?=$ind?>">
        <?php if (empty($models[$ind]) || (!empty($models[$ind]) && !empty($modelPreviewImages))): ?>
          <?=$this->record($this->driver)->renderTemplate('image-download.phtml', ['index' => $ind, 'rights' => $rights, 'image' => $image, 'hiRes' => $image['highResolution'] ?? false, 'models' => $models ?? []])?>
          <?=$this->record($this->driver)->renderTemplate('image-information.phtml', ['index' => $ind, 'image' => $image]);?>
        <?php endif; ?>
        <?php if (!empty($models[$ind])): ?>
          <?=$this->record($this->driver)->renderTemplate('model-download.phtml', ['index' => $ind, 'rights' => $rights, 'model' => $models[$ind]]);?>
        <?php endif; ?>
        <?=$this->record($this->driver)->renderTemplate('image-rights.phtml', ['imageRightsLabel' => $imageRightsLabel, 'rights' => $rights, 'truncateLicense' => $ind === 0]);?>
      </div>
      <?php $ind++; ?>
    <?php endforeach; ?>
  <?php endif; ?>
</div>

<!-- END of: finna - RecordDriver/DefaultRecord/record-image.phtml -->
