<!-- START of: finna - RecordDriver/SolrEad/core-fields.phtml -->
<?php
  $formatter = $this->recordDataFormatter($this->driver);
  $coreFields = $formatter->getDefaults();
  $coreFields['Access Restrictions Extended']['hideSubheadings']
      = ['access_restrictions_general'];
  $coreFieldGroups = $formatter->getGroupedData($this->driver, $formatter->getGroupedFields([
    ['label' => 'Context',
      'lines' => ['Archive Origination', 'Archive', 'Archive Series', 'Archive File'],
    ],
    ['lines' => [
        'Format', 'Authors', 'Secondary Authors', 'Unit ID', 'Unit IDs','Subjects',
        'subjects_extended', 'Dates', 'Material Condition'],
    ],
    ['label' => 'access_restrictions_general',
      'lines' => ['Access Restrictions Extended'],
    ],
    [
      'lines' => ['Access Restrictions'],
    ],
  ], $coreFields));
?>
<?php if (!empty($coreFieldGroups)): ?>
  <table class="table table-finna-record record-details record-field-groups" role="presentation">
    <?=$this->record($this->driver)->renderTemplate('core-field-groups.phtml', ['data' => $coreFieldGroups]);?>
  </table>
<?php endif; ?>
<!-- END of: finna - RecordDriver/SolrEad/core-fields.phtml -->
