<?php
    $i = 0;
    foreach ($urls as $url):
        $language = $this->layout()->userLang;
        $description = $url['desc'] ?: $this->translate('Download the file');
        $rights = $this->driver->getAccessRestrictionsType($language);
        $rightsDescription = $this->driver->getAccessRestrictions($language);
        $hasLink = isset($rights['link']) && !empty($rights['link']);
    ?>
    <li class="fulltextField">
        <div class="link-wrapper">
            <a href="<?=$this->escapeHtmlAttr($this->proxyUrl($url['url']))?>" target="_blank" aria-label="<?=$this->transEscAttr('external_online_link')?>"
                <?php if (!empty($url['posterUrl'])): ?> data-poster-url="<?= $this->escapeHtmlAttr($url['posterUrl']) ?>"<?php endif; ?>
            >
                <?=$this->icon('external-link') ?> <?=$this->escapeHtml($this->translate('link_' . $url['desc'], null, $url['desc']))?>
            </a>
            <div class="copyright-wrapper">
                <span>
                    (<?=$this->escapeHtml($url['format'])?><?php if ($rights) { ?>:<?php } ?>
                </span>
                <span class="copyright-icons">
                    <?=$this->partial('Helpers/copyright-icons.phtml', ['copyright' => $rights['copyright']])?>
                </span>
                <?php if ($hasLink): ?>
                    <a class="copyright-description" href="<?=$this->escapeHtml($rights['link'])?>" target="_blank"><?=$this->escapeHtmlAttr($rights['copyright'])?></a><span>)</span>
                <?php else: ?>
                    <span><?=$this->escapeHtml($rights['copyright']);?>)</span>
                <?php endif; ?>
            </div>
        </div>

    </li>
<?php
    $i++;
    endforeach;
?>
