<!-- START of: finna - footer.phtml -->
<?=$this->section('FooterMenu')->render()?>
<hr>
<div class="footer-container">
  <div class="footer-column">
    <a href="<?=$this->url('content-page', ['page' => 'about_finna'])?>" title="<?=$this->transEscAttr('About Finna')?>">
      <?php
        if (!($finnaImage = $this->imageLink('powered-by-finna_' . $this->layout()->userLang . '-black.svg'))) {
          $finnaImage = $this->imageLink('powered-by-finna_en-gb-black.svg');
        }
        if ($finnaImage):
      ?>
        <img class="powered-by-finna" src="<?=$finnaImage?>" alt="">
      <?php endif; ?>
      <span class="visually-hidden"><?=$this->transEsc('About Finna')?></span>
    </a>
    <br><br>
  </div>
  <div class="footer-column">
    <a href="https://vufind.org/" title="<?=$this->transEscAttr('About VuFind')?>">
      <img class="vufind-logo" src="<?=$this->imageLink('vufind-logo-black.svg')?>" alt="">
      <span class="visually-hidden"><?=$this->transEsc('About VuFind')?></span>
    </a>
  </div>
  <div class="footer-column">
  </div>
</div>
<!-- END of: finna - footer.phtml -->
