<!-- START of: finna - navibar.phtml -->
<?php
    $user = $this->auth()->isLoggedIn();
    $patron = $user ? $this->auth()->getILSPatron() : false;
    $capabilityParams = $patron ? ['patron' => $patron] : [];
    $account = $this->auth()->getManager();
    $lang = $this->layout()->userLang;
    $selectedLang = $this->layout()->allLangs[$lang];
?>
<div role="navigation" aria-label="<?=$this->transEscAttr('Main Menu')?>" class="finna-navbar">
  <div class="navbar-header">
    <button class="navbar-toggle collapsed" data-toggle="collapse" data-target="#header-collapse" aria-label="<?=$this->transEscAttr('Mobile Menu') ?>" aria-expanded="false">
      <i class="fa fa-bars" aria-hidden="true"></i>
      <i class="fa fa-times" aria-hidden="true"></i>
    </button>
    <?php if ($this->resolver('navibar-logo.phtml')): ?><a class="navbar-brand" href="<?=$this->url('home')?>"><?=$this->render('navibar-logo.phtml')?></a><?php endif ?>
  </div>
  <?php if (!isset($this->layout()->renderingError)): ?>
    <div class="collapse navbar-collapse" id="header-collapse">
      <ul role="menubar" class="nav navbar-nav navbar-main">
        <?php foreach ($this->navibar()->getMenuItems($this->layout()->userLang) as $key => $val): ?>
          <?php if (count($val['items']) > 1): ?>
            <li role="none" class="dropdown" id="<?= $val['label'] ?>">
              <a href="#" role="menuitem" class="dropdown-toggle" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false"><i class="fa fa-nav-<?=$val['label'] ?>" aria-hidden="true"></i><?= $this->transEsc($val['label']) ?> <?=$this->icon('collapse-open', 'collapse-open-icon')?></a>
              <ul role="menu" class="dropdown-menu" aria-labelledby="<?= $val['label'] ?>">
                <?php foreach ($val['items'] as $itemKey => $itemVal): ?>
                <?php
                  if (!($itemUrl = $this->navibar()->getMenuItemUrl($itemVal))) {
                    continue;
                  }
                  $url = $itemUrl['url'];
                  $target = !empty($itemUrl['target']) ? $itemUrl['target'] : null;
                  $label = $itemVal['label'];
                  $desc = !empty($itemVal['desc']) ? $itemVal['desc'] : null;
                ?>
                  <li>
                    <a <?=$url === $_SERVER['REQUEST_URI'] ? 'aria-current="page"' : ''?> role="menuitem" <?= $target ? ' target="' . $this->escapeHtmlAttr($target) . '"' : ''?> href="<?=$this->escapeHtmlAttr($url)?>">
                      <div><?= $this->transEsc($label) ?></div>
                      <?php if ($desc): ?>
                        <div class="description" role="note"><?= $this->transEsc($desc) ?></div>
                      <?php endif; ?>
                    </a>
                  </li>
                <?php endforeach; ?>
              </ul>
            </li>
          <?php else:
            $itemVal = $val['items'][0];
            if (!($itemUrl = $this->navibar()->getMenuItemUrl($itemVal))) {
              continue;
            }
            $url = $itemUrl['url'];
            $target = $itemUrl['target'] ?? null;
            $label = $itemVal['label'];
          ?>
            <li role="none"><a <?=$url === $_SERVER['REQUEST_URI'] ? 'aria-current="page"' : ''?> role="menuitem" <?= $target ? ' target="' . $this->escapeHtmlAttr($target) . '"' : ''?> href="<?= $url ?>"><i class="fa fa-nav-<?=$label ?>" aria-hidden="true"></i><?= $this->transEsc($label) ?></a></li>
          <?php endif; ?>
        <?php endforeach; ?>
        <?php $cart = $this->cart();
        if ($cart->isActive()): ?>
          <li role="none" id="cartSummary">
            <a <?=$this->url('cart-home') === $_SERVER['REQUEST_URI'] ? 'aria-current="page"' : ''?> role="menuitem" id="cartItems" data-lightbox title="<?=$this->transEsc('View Book Bag')?>" href="<?=$this->url('cart-home')?>"><?=$this->icon('cart') ?> <strong><?=count($cart->getItems())?></strong> <span class="sr-only"><?=$this->transEsc('items')?></span></a>
          </li>
        <?php endif; ?>
        <?php if ($this->feedback()->tabEnabled()): ?>
          <li role="none">
            <a <?=$this->url('feedback-home') === $_SERVER['REQUEST_URI'] ? 'aria-current="page"' : ''?> role="menuitem" id="feedback-link" href="<?=$this->url('feedback-home') ?>"><?=$this->transEsc("Feedback")?></a>
          </li>
        <?php endif; ?>

        <?php if (isset($this->layout()->themeOptions) && count($this->layout()->themeOptions) > 1): ?>
          <li class="theme dropdown">
            <a role="menuitem" href="#" class="dropdown-toggle" data-toggle="dropdown"><?=$this->transEsc("Theme")?> <?=$this->icon('collapse-open', 'collapse-open-icon')?></a>
            <ul role="menu" class="dropdown-menu">
              <?php foreach ($this->layout()->themeOptions as $current): ?>
                <li <?=$current['selected'] ? ' class="active"' : '' ?>>
                  <a role="menuitem" href="<?=$this->escapeHtmlAttr($this->url()->addQueryParameters(['ui' => $current['name']])) ?>" rel="nofollow">
                    <?=$this->transEsc($current['desc']) ?>
                  </a>
                </li>
              <?php endforeach; ?>
            </ul>
          </li>
        <?php endif; ?>

        <?php if ($template = $this->content()->findTemplateForLng("content/Additions/header-navibar")): ?>
          <?=$this->render($template)?>
        <?php endif; ?>
      </ul>
    </div>
  <?php endif; ?>
  <ul class="nav navbar-nav header-navbar-right">
    <li id="language_menu" class="dropdown">
      <a href="#" id="language_menu_dropdown_button" class="btn dropdown-toggle" role="button" data-toggle="dropdown" aria-label="<?=$this->transEscAttr('Language')?>" aria-haspopup="true" aria-expanded="false">
        <?=$this->icon('language', 'lang-icon') ?>
        <span class="hidden-xs"><?=$this->displayLanguageOption($selectedLang)?></span>
        <?=$this->icon('collapse-open', 'collapse-open-icon') ?>
      </a>
      <ul class="dropdown-menu dropdown-menu-right" role="menu" aria-labelledby="language_menu_dropdown_button" >
        <?php if (isset($this->layout()->allLangs) && count($this->layout()->allLangs) > 1): ?>
          <?php foreach ($this->layout()->allLangs as $langCode => $langName): ?>
            <?php if ($this->layout()->userLang == $langCode): ?>
              <li class="dropdown-item" role="none">
                <a class="preserve-anchor active" role="menuitem" lang="<?=$this->escapeHtmlAttr($langCode)?>"> <?=$this->displayLanguageOption($langName)?></a>
              </li>
              <?php break; ?>
            <?php endif ?>
          <?php endforeach; ?>
          <?php foreach ($this->layout()->allLangs as $langCode => $langName): ?>
            <?php if ($this->layout()->userLang != $langCode): ?>
              <li class="dropdown-item" role="none">
                <a class="preserve-anchor" role="menuitem" lang="<?=$this->escapeHtmlAttr($langCode)?>" href="<?=$this->escapeHtmlAttr($this->navibar()->getLanguageUrl($langCode))?>"><?=$this->displayLanguageOption($langName)?></a>
              </li>
            <?php endif ?>
          <?php endforeach; ?>
        <?php endif; ?>
      </ul>
    </li>
    <?php if (is_object($account) && $account->loginEnabled()): ?>
      <?php if ($user): ?>
        <li class="logoutOptions">
          <a href="#" class="btn" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false"><span id="account-icon"></span><?=$this->icon('my-account', 'my-account-icon') ?> <span class="username login-text"><?=$this->transEsc("Your Account")?></span> <?=$this->icon('collapse-open', 'collapse-open-icon')?></a>
          <ul role="menu" id="my-info-dropdown-menu" class="dropdown-menu dropdown-menu-right">
            <?php if ($user->getLibraryCards()->count() > 0): ?>
              <li role="none">
                <a <?=$this->url('myresearch-checkedout') === $_SERVER['REQUEST_URI'] ? 'aria-current="page"' : ''?> role="menuitem" href="<?=$this->url('myresearch-checkedout')?>">
                  <?=$this->transEsc('Checked Out Items')?>
                  <span class="checkedout-status status hidden"><?=$this->icon('spinner') ?></span>
                </a>
              </li>
              <?php if ($this->ils()->checkCapability('getMyTransactionHistory', $capabilityParams)): ?>
                <li role="none">
                  <a <?=$this->url('checkouts-history') === $_SERVER['REQUEST_URI'] ? 'aria-current="page"' : ''?> role="menuitem" href="<?=$this->url('myresearch-historicloans')?>">
                    <?=$this->transEsc('Loan History')?>
                  </a>
                </li>
              <?php endif; ?>
              <li role="none">
                <a <?=$this->url('holds-list') === $_SERVER['REQUEST_URI'] ? 'aria-current="page"' : ''?> role="menuitem" href="<?=$this->url('holds-list')?>">
                  <?=$this->transEsc('Holds and Recalls')?>
                  <span class="holds-status status hidden"><?=$this->icon('spinner') ?></span>
                </a>
              </li>
              <li role="none">
                <a <?=$this->url('myresearch-fines') === $_SERVER['REQUEST_URI'] ? 'aria-current="page"' : ''?> role="menuitem" href="<?=$this->url('myresearch-fines')?>">
                  <?=$this->transEsc('Fines')?>
                  <span class="fines-status status hidden"><?=$this->icon('spinner') ?></span>
                </a>
              </li>
            <?php endif; ?>
            <?=$this->context($this)->renderInContext('librarycards/selectcard.phtml', ['user' => $user, 'loginMenu' => 'true', 'label' => 'Library Cards','limit' => 0]);?>
            <li role="none">
              <a <?=$this->url('myresearch-profile') === $_SERVER['REQUEST_URI'] ? 'aria-current="page"' : ''?> role="menuitem" href="<?=$this->url('myresearch-profile')?>">
                <?=$this->transEsc('Profile')?>
                <span class="profile-status status hidden"><?=$this->icon('spinner') ?></span>
              </a>
            </li>
            <?php if ($this->R2()->isAvailable()): ?>
            <?php $registered = $this->R2()->isRegistered(); ?>
              <li role="none">
                <a <?=$this->url('myresearch-r2accessrights') === $_SERVER['REQUEST_URI'] ? 'aria-current="page"' : ''?> role="menuitem" href="<?=$this->url('myresearch-r2accessrights')?>">
                  <?=$this->transEsc($registered ? 'R2_accessrights_title' : 'R2_menu_heading_register')?>
                  <?php if (!$registered): ?>
                    <?=$this->icon('research', 'pull-right') ?>
                  <?php endif; ?>
                </a>
              </li>
            <?php endif; ?>
            <li role="none">
              <a <?=$this->url('search-history') === $_SERVER['REQUEST_URI'] ? 'aria-current="page"' : ''?> role="menuitem" href="<?=$this->url('search-history')?>?require_login">
                <?=$this->transEsc('history_saved_searches')?>
              </a>
            </li>
            <?php if ($this->userlist()->getMode() !== 'disabled'): ?>
              <li role="none">
                <a <?=$this->url('myresearch-favorites') === $_SERVER['REQUEST_URI'] ? 'aria-current="page"' : ''?> role ="menuitem" href="<?=$this->url('myresearch-favorites')?>">
                  <?=$this->transEsc('Favorites')?>
                </a>
              </li>
            <?php endif; ?>
            <li role="none">
              <a <?=$this->url('myresearch-logout') === $_SERVER['REQUEST_URI'] ? 'aria-current="page"' : ''?> role="menuitem" href="<?=$this->url('myresearch-logout')?>" title="<?=$this->transEsc("Log Out")?>"><?=$this->transEsc("Log Out")?><?=$this->icon('sign-out', 'sign-out-icon pull-right') ?></a>
            </li>
          </ul>
        </li>
      <?php endif; ?>
      <li id="loginOptions"<?= $account->isLoggedIn() ? " class='hidden'" : '';?>>
        <?php if ($sessionInitiator = $account->getSessionInitiator($this->serverUrl($this->url('myresearch-home')))): ?>
          <a <?=$this->url('myresearch-userlogin') === $_SERVER['REQUEST_URI'] ? 'aria-current="page"' : ''?> href="<?=$this->url('myresearch-userlogin')?>"><?=$this->icon('login', 'login-icon') ?> <?=$this->transEsc("Institutional Login")?></a>
        <?php else: ?>
          <?php if ($this->templateDir === 'myresearch' && $this->templateName === 'login'): ?>
            <div>
              <a class="btn btn-primary btn-uppercase"><?=$this->icon('login', 'login-icon') ?> <span class="login-text"><?=$this->transEsc("Login")?></span></a>
            </div>
          <?php else: ?>
            <div>
              <a <?=$this->url('myresearch-userlogin') === $_SERVER['REQUEST_URI'] ? 'aria-current="page"' : ''?> href="<?=$this->url('myresearch-userlogin')?>" class="btn btn-primary btn-uppercase" data-lightbox data-lightbox-onclose="window.location.href='<?=$this->escapeHtmlAttr($this->url('myresearch-home')) ?>'"><?=$this->icon('login', 'login-icon') ?> <span class="login-text"><?=$this->transEsc("Login")?></span></a>
            </div>
          <?php endif; ?>
        <?php endif; ?>
      </li>
    <?php endif; ?>
  </ul>
</div>
<!-- END of: finna - navibar.phtml -->
