<h2><?=$this->transEsc('Report inappropriate') ?></h2>

<?=$this->flashmessages() ?>

<form class="comment-inappropriate-form" method="post" name="commentInappropriateForm"  data-lightbox-onclose="finna.comments.requestRefreshComments">
  <input type="hidden" name="id" value="<?=$this->escapeHtmlAttr($this->id)?>"/>
  <div class="form-group">
    <p><?=$this->transEsc('Select') ?>:</p>
    <ul>
      <?php $reasons = [1, 2, 3, 4, 6, 5]; ?>
      <?php foreach ($reasons as $i): ?>
      <li><label for="inapp<?=$i?>"><input id="inapp<?=$i?>" type="radio" name="reason" <?= $i == 1 ? 'checked="checked"' : ''?> value="<?=$this->transEscAttr('inappropriate_reason_' . $i)?>" /> <?=$this->translate('inappropriate_reason_' . $i)?></label></li>
      <?php endforeach; ?>
    </ul>
  </div>
  <p>Tarkennus miksi on asiaton:</p>
  <textarea id="message" class="form-control" name="message" rows="3" maxlength="1000"></textarea>
  <input class="btn btn-primary" name="submit" type="submit" value="<?=$this->transEscAttr('Submit')?>" />
</form>
