<!-- START of: finna - collection/view.phtml -->
<?php
  // Set up standard record scripts:
  $this->assetManager()->appendScriptLink('record.js');
  $this->assetManager()->appendScriptLink('check_save_statuses.js');
  // Add any extra scripts the tabs require:
  foreach ($this->tabsExtraScripts as $script) {
    $this->assetManager()->appendScriptLink($script);
  }

  // Add RDF header link if applicable:
  if ($this->export()->recordSupportsFormat($this->driver, 'RDF')) {
    $this->headLink()->appendAlternate($this->recordLinker()->getActionUrl($this->driver, 'RDF'), 'application/rdf+xml', 'RDF Representation');
  }

  // Set flag for special cases relating to full-width hierarchy tree tab:
  $tree = (strtolower($this->activeTab) == 'hierarchytree');

  // Set up breadcrumbs:
  $this->breadcrumbs()->reset();
  if ($url = $this->searchMemory()->getLastSearchUrl()) {
    $this->breadcrumbs()->add($this->translate('Search'), $url);
  } else {
    $this->breadcrumbs()->add($this->translate('Collections'), $this->url('collections-home'));
  }
  $this->breadcrumbs()->add(...$this->recordLinker()->getBreadcrumbParams($this->driver), active: true);

  // Set up search box:
  $this->layout()->searchbox = $this->context($this)->renderInContext(
      'search/searchbox.phtml',
      [
        'ignoreHiddenFiltersInRequest' => true,
      ]
  );

  // Set page title.
  $dataSource = $this->driver->tryMethod('getDataSource');
  $headText = $this->driver->getBreadcrumb() . ' | ' . $this->translate('Collection') . (isset($dataSource) ? ' | ' . $this->transEsc('default::source_' . $dataSource, null, $dataSource) : '');
  $this->headTitle($headText);

  // Ead3 records with images and all LIDO records are displayed like on the record page:
  $displayAsFullRecord =
    $this->driver instanceof \Finna\RecordDriver\SolrLido
    || ($this->driver instanceof \Finna\RecordDriver\SolrEad3 && $this->driver->getAllImages(includePdf: true));
  $largeImageLayout = $displayAsFullRecord && $this->record($this->driver)->hasLargeImageLayout();

  if ($oldRecordId = $this->driver->getExtraDetail('redirectedFromId')) {
    echo $this->assetManager()->outputInlineScriptString(
        'finna.record.handleRedirect(' . json_encode($oldRecordId) . ', ' . json_encode($this->driver->getUniqueID()) . ');'
    );
  }
?>
<?php if (!empty($this->searchMemory()->getLastSearchUrl())) : ?>
</div>
<div class="container">
<?php endif; ?>
<div class="record source<?=$this->escapeHtmlAttr($this->driver->getSourceIdentifier())?><?=$largeImageLayout ? ' large-image-layout' : '' ?>">
  <div>
    <?=$this->record($this->driver)->getToolbar()?>
  </div>
  <input type="hidden" value="<?=$this->escapeHtmlAttr($this->driver->getUniqueId())?>" class="hiddenId" id="record_id">
  <input type="hidden" value="<?=$this->escapeHtmlAttr($this->driver->getSourceIdentifier())?>" class="hiddenSource">
  <div class="record-main<?=!$largeImageLayout ? ' mainbody left' : ''?>">
    <?=$this->flashmessages()?>
    <?php if ($displayAsFullRecord): ?>
      <?=$this->record($this->driver)->getMetaTags();?>
      <?=$this->record($this->driver)->getCoreMetadata()?>
    <?php else: ?>
      <h2 class="collection-title"><?=$this->driver->getTitle();?></h2>
      <?php $formats = $this->driver->getFormats();
      if (!empty($formats)): ?>
        <div class="recordFormat collection-format">
          <?=$this->record($this->driver)->getFormatList()?><br>
        </div>
      <?php endif; ?>
      <?php if ($summary = $this->driver->tryMethod('getSummaryExtended')): ?>
        <div class="truncate-field wide summary recordSummary">
          <?php foreach ($summary as $i => $item): ?>
            <?php
              $html = $this->recordFieldMarkdown()->toHtml($item['text']);
              if (!empty($url = $item['url'] ?? '')) {
                $link = ' (<a target="_blank" href="'
                  . $this->escapeHtmlAttr($this->proxyUrl($url))
                  . '">' . $this->escapeHtml($this->truncateUrl($url)) . '</a>)';
                $html = trim($html);
                if ('</p>' === substr($html, -4)) {
                  $html = substr($html, 0, strlen($html) - 4) . $link . '</p>';
                } else {
                  $html .= $link;
                }
              }
            ?>
            <?= $html ?>
          <?php endforeach; ?>
        </div>
      <?php elseif ($summary = $this->driver->tryMethod('getSummary')): ?>
        <div class="truncate-field wide summary recordSummary">
          <?php foreach ($summary as $field): ?>
            <?= $this->recordFieldMarkdown()->toHtml($field) ?>
          <?php endforeach; ?>
        </div>
      <?php endif; ?>
      <?php /* Display Main Details from records */?>
      <?php
        $formatter = $this->recordDataFormatter($driver);
        $coreFields = $formatter->getDefaults();
        if ($driver instanceof \Finna\RecordDriver\SolrEad3) {
          // Do not display sub label in access restrictions for EAD3 to avoid duplicate for general
          $coreFields['Access Restrictions Extended']['hideSubheadings'] = ['access_restrictions_general'];
        }
        $coreFieldGroups = $formatter->getGroupedData($driver, $formatter->getGroupedFields([
          ['label' => 'Context',
            'lines' => ['Archive Origination', 'Archive', 'Archive Series', 'Archive File'],
          ],
          [
            'lines' => ['Format', 'Unit ID', 'Unit IDs'],
          ],
          ['label' => 'archive_authors',
          'lines' => ['archive_authors', 'Archive Relations', 'archive_other_authors'],
          ],
          ['lines' => [
              'Authors', 'Secondary Authors', 'Subject Actor', 'Subjects',
              'subjects_extended', 'Dates', 'Material Condition'],
          ],
          ['label' => 'access_restrictions_general',
            'lines' => ['Access Restrictions Extended']],
          ], $coreFields));
        ?>
        <?php if (!empty($coreFieldGroups)): ?>
          <table class="table table-finna-record record-details record-field-groups">
            <?=$this->record($this->driver)->renderTemplate('core-field-groups.phtml', ['data' => $coreFieldGroups]);?>
          </table>
        <?php endif; ?>
      <?php /* End Main Details */?>
    <?php endif; ?>
  </div>
  <?php if (!$largeImageLayout): ?>
    <div class="sidebar right smaller-image-sidebar hidden-xs hidden-sm">
      <?= $this->render('record/sidebar-contents.phtml'); ?>
    </div>
  <?php endif; ?>

  <?=$this->driver->supportsCoinsOpenURL() ? '<span class="Z3988" aria-hidden="true" title="' . $this->escapeHtmlAttr($this->driver->getCoinsOpenURL()) . '"></span>' : ''?>

  <div class="clearfix hidden-lg hidden-md"></div>
  <nav class="record-tabs">
    <?php if ($this->tabs): ?>
      <a id="tabnav"><h2 class="visually-hidden"><?=$this->transEsc('Additional Information')?></h2></a>
      <?=$this->component(
        'tabs',
        [
          'tabs' => $this->recordTabs()->getTabs($this->driver, $this->tabs, $this->activeTab),
          'activeTab' => $this->activeTab,
          'tabNavClasses' => ['recordTabs'],
          'tabContentClasses' => ['collectionDetails' . ($tree ? 'Tree' : '')],
          'scrollable' => true,
        ]
      )?>
    <?php endif; ?>
  </nav>

</div>
  <div class="sidebar large-image-sidebar <?php if (!$largeImageLayout):?>visible-xs visible-sm <?php endif;?>">
    <?= $this->render('record/sidebar-contents.phtml'); ?>
  </div>
</div>
<div>
<!-- END of: finna - collection/view.phtml -->
