<!-- START of: finna - collection/view.phtml -->
<?php
  // Set up standard record scripts:
  $this->headScript()->appendFile("record.js");
  $this->headScript()->appendFile("check_save_statuses.js");
  // Activate Syndetics Plus if necessary:
  if ($this->syndeticsPlus()->isActive()) {
    $this->headScript()->appendFile($this->syndeticsPlus()->getScript());
  }
  // Add any extra scripts the tabs require:
  foreach ($this->tabsExtraScripts as $script) {
    $this->headScript()->appendFile($script);
  }

  // Add RDF header link if applicable:
  if ($this->export()->recordSupportsFormat($this->driver, 'RDF')) {
    $this->headLink()->appendAlternate($this->recordLinker()->getActionUrl($this->driver, 'RDF'), 'application/rdf+xml', 'RDF Representation');
  }

  // Set flag for special cases relating to full-width hierarchy tree tab:
  $tree = (strtolower($this->activeTab) == 'hierarchytree');

  // Set up breadcrumbs:
  $lastSearch = $this->searchMemory()->getLastSearchLink($this->transEsc('Search'));
  if (!empty($lastSearch)) {
      $this->layout()->breadcrumbs = '<li>' . $lastSearch . '</li> ';
  } else {
      $this->layout()->breadcrumbs = '';
  }
  $this->layout()->breadcrumbs .= '<li class="active" aria-current="page">' . $this->recordLinker()->getBreadcrumbHtml($this->driver) . '</li>';

  // Set page title.
  $dataSource = $this->driver->tryMethod('getDataSource');
  $headText = $this->driver->getBreadcrumb() . ' | ' . $this->translate('Collection') . (isset($dataSource) ? ' | ' . $this->transEsc('default::source_' . $dataSource, null, $dataSource) : '');
  $this->headTitle($headText);

  if ($lastUrl = $this->searchMemory()->getLastSearchUrl()) {
      $params = $this->searchMemory()->getLastSearchParams($this->searchClassId);
      $filterList = $params->getFilterList(true);

      if (!empty($params->getFilterList(false))) {
          $checkboxFilters = $params->getCheckboxFacets();
          $lastSort = $this->searchMemory()->getLastSort($this->searchClassId);
          $options = $this->searchOptions($this->searchClassId);
          $defaultSortApplied = !isset($params) || $lastSort == $options->getDefaultSortByHandler($params->getSearchHandler());
          // Set up filters
          $this->layout()->finnaFilters = $this->context($this)->renderInContext(
              'search/filters.phtml',
              [
                  'filterList' => $filterList,
                  'checkboxFilters' => $checkboxFilters,
                  'defaultSortApplied' => $defaultSortApplied,
                  'options' => $options,
                  'params' => $params
              ]
          );
      }
  }

?>
<?php if (!empty($lastSearch)) : ?>
</div>
<div class="container">
<?php endif; ?>
<div class="record record-row source<?=$this->escapeHtmlAttr($this->driver->getSourceIdentifier())?>">
  <?= $this->R2()->registeredInfo($this->driver) ?>
  <div>
    <?=$this->record($this->driver)->getToolbar()?>
  </div>
  <input type="hidden" value="<?=$this->escapeHtmlAttr($this->driver->getUniqueId())?>" class="hiddenId" id="record_id" />
  <input type="hidden" value="<?=$this->escapeHtmlAttr($this->driver->getSourceIdentifier())?>" class="hiddenSource" />
  <div class="record-main mainbody left">
    <?=$this->flashmessages()?>
    <h2 class="collection-title"><?=$this->driver->getTitle();?></h2>
    <?= $this->R2()->register($this->driver, ['brief' => true])?>
    <?php $formats = $this->driver->getFormats(); if (!empty($formats)): ?>
       <div class="recordFormat collection-format">
         <?=$this->record($this->driver)->getFormatList()?><br/>
       </div>
    <?php endif; ?>
    <?php if ($summary = $this->driver->tryMethod('getSummaryExtended')): ?>
      <div class="truncate-field wide summary recordSummary">
        <?php foreach ($summary as $i => $item): ?>
          <?php
            $html = $this->recordFieldMarkdown()->toHtml($item['text']);
            if (!empty($url = $item['url'] ?? '')) {
              $link = ' (<a target="_blank" href="'
                . $this->escapeHtmlAttr($this->proxyUrl($url))
                . '">' . $this->escapeHtml($this->truncateUrl($url)) . '</a>)';
              $html = trim($html);
              if ('</p>' === substr($html, -4)) {
                $html = substr($html, 0, strlen($html) - 4) . $link . '</p>';
              } else {
                $html .= $link;
              }
            }
          ?>
          <?= $html ?>
        <?php endforeach; ?>
      </div>
    <?php elseif ($summary = $this->driver->tryMethod('getSummary')): ?>
      <div class="truncate-field wide summary recordSummary">
        <?php foreach ($summary as $field): ?>
          <?= $this->recordFieldMarkdown()->toHtml($field) ?>
        <?php endforeach; ?>
      </div>
    <?php endif; ?>
    <?/* Display Main Details from records */?>
    <?php
      $formatter = $this->recordDataFormatter();
      $coreFields = $formatter->filterCollectionFields($formatter->getDefaults('core'), $driver->getRecordFormat());
      $coreFieldGroups = $formatter->getGroupedData($driver, $formatter->getGroupedFields([
        ['label' => 'Context',
          'lines' => ['Archive Origination', 'Archive', 'Archive Series', 'Archive File']
        ],
        ['lines' => [
            'Format', 'Authors', 'Secondary Authors', 'Unit ID', 'Unit IDs','Subjects',
            'subjects_extended', 'Dates', 'Material Condition']
        ],
        ['label' => 'access_restrictions_general',
          'lines' => ['Access Restrictions Extended']]
        ], $coreFields));
      ?>
      <?php if (!empty($coreFieldGroups)): ?>
        <table class="table table-finna-record record-details record-field-groups">
          <?=$this->record($this->driver)->renderTemplate('core-field-groups.phtml', ['data' => $coreFieldGroups]);?>
        </table>
      <?php endif; ?>
    <?/* End Main Details */?>
  </div>
  <?php ob_start(); ?>
    <?php if ($this->record($this->driver)->getOrganisationMenuPosition() === 'sidebar'): ?>
      <div class="organisation-menu">
          <?=$this->render('record/record-organisation-menu.phtml') ?>
      </div>
    <?php endif; ?>
    <?php foreach ($this->related()->getList($this->driver) as $current): ?>
        <?=$this->related()->render($current)?>
    <?php endforeach; ?>
  <?php $sidebar = ob_get_contents(); ?>
  <?php ob_end_clean(); ?>
  <div class="sidebar right smaller-image-sidebar hidden-xs hidden-sm">
    <?php if ($sidebar):?>
        <?=$sidebar ?>
    <?php endif; ?>
  </div>

  <div class="clearfix hidden-lg hidden-md"></div>
  <?php // N.B. The element/class structure here is important for the ajax tabs to work properly ?>
  <div class="record-tabs record-accordions">
    <?php if (count($this->tabs) > 0): ?>
      <a id="tabnav"></a>
        <?php if (count($this->tabs) > 3): ?>
        <div class="tabs-responsive">
        <?php endif; ?>
        <ul class="recordTabs nav nav-tabs visible-md visible-lg">
          <?php foreach ($this->tabs as $tab => $obj): ?>
            <?php
              $desc = $obj->getDescription();
              $tabName = preg_replace("/\W/", "-", strtolower($tab));
              $tabClasses = [ 'record-tab', $tabName ];
              if (0 === strcasecmp($this->activeTab, $tab)) {
                if (!$this->loadInitialTabWithAjax || !$obj->supportsAjax()) {
                    $tabClasses[] = 'active';
                }
                $tabClasses[] = 'initiallyActive';
                $activeTabObj = $obj;
              }
              if (!$obj->isVisible()) { $tabClasses[] = 'hidden'; }
              if (!$obj->supportsAjax()) { $tabClasses[] = 'noajax'; }
              if (strtolower($tab) == 'details') { $tabClasses[] = 'hidden-xs tab-right'; }
            ?>
            <li class="<?=implode(' ', $tabClasses)?>" data-tab="<?=$tabName?>">
            <a class="<?=$this->escapeHtmlAttr(strtolower($tab)) ?>" aria-label="<?=$this->escapeHtmlAttr($this->transEsc($desc))?>"
              href="<?=$this->escapeHtmlAttr($this->recordLinker()->getTabUrl($this->driver, $tab))?>#tabnav" data-lightbox-ignore<?php if ($obj->supportsAjax() && in_array($tab, $this->backgroundTabs)):?>
              data-background<?php endif ?>>
              <?php if (strtolower($tab) == 'details'): ?><i class="fa fa-lg fa-<?=$this->escapeHtmlAttr($tab)?>"></i><?php endif; ?>
              <?php if (strtolower($tab) != 'details'): ?><?=$this->transEsc($desc)?><?php endif; ?><?php if (strtolower($tab) == 'usercomments') : ?> (<span class="count"><?= count($this->driver->getComments()) ?></span>)<?php endif; ?>
            </a>
            </li>
          <?php endforeach; ?>
        </ul>
        <?php if (count($this->tabs) > 3): ?>
        </div>
        <?php endif; ?>
    <?php endif; ?>

    <div class="tab-content collectionDetails<?=$tree ? 'Tree' : ''?>">
      <?php if (!$this->loadInitialTabWithAjax || !isset($activeTabObj) || !$activeTabObj->supportsAjax()): ?>
        <div class="tab-pane active <?=$this->escapeHtmlAttr($this->activeTab) ?>-tab">
          <?=isset($activeTabObj) ? $this->record($this->driver)->getTab($activeTabObj) : '' ?>
        </div>
      <?php endif; ?>
    </div>

    <div class="record-accordions">
     <?php foreach ($this->tabs as $accordion => $obj): ?>
       <?php
         $desc = $obj->getDescription();
         $accordion_classes = [
           'accordion',
           'accordion-' . preg_replace("/\W/", "-", strtolower($accordion))
         ];
         if (0 === strcasecmp($this->activeTab, $accordion)) {
           if (!$this->loadInitialTabWithAjax || !$obj->supportsAjax()) {
             $accordion_classes[] = 'active';
           }
           $accordion_classes[] = 'initiallyActive';
         }
         if (!$obj->isVisible()) { $accordion_classes[] = 'hidden'; }
         if (!$obj->supportsAjax()) { $accordion_classes[] = 'noajax'; }
       ?>
       <div class="<?=implode(' ', $accordion_classes)?>">
         <div class="accordion-toggle">
           <a data-tab="<?=$this->escapeHtmlAttr(strtolower($accordion)) ?>" class="accordion-title"
             href="<?=$this->escapeHtmlAttr($this->recordLinker()->getTabUrl($this->driver, $accordion))?>#tabnav"<?php if ($obj->supportsAjax() && in_array($accordion, $this->backgroundTabs)):?>
             data-background<?php endif ?>
           >
             <span class="title"><?=$this->transEsc($desc)?><?php if (strtolower($accordion) == 'usercomments') : ?> (<span class="count"><?= count($this->driver->getComments()) ?></span>)<?php endif; ?></span>
             <i class="icon"></i>
           </a>
         </div>
       </div>
     <?php endforeach; ?>
    </div>

    <?=$this->driver->supportsCoinsOpenURL()?'<span class="Z3988" title="' . $this->escapeHtmlAttr($this->driver->getCoinsOpenURL()) . '"></span>':''?>
  </div>

</div>
</div>
<?=$this->record($this->driver)->renderTemplate('toolbar_mobile.phtml') ?>
<div>
<?=$this->inlineScript(\Laminas\View\Helper\HeadScript::SCRIPT, '$(document).ready(recordDocReady);', 'SET') ?>
<!-- END of: finna - collection/view.phtml -->
