<!-- START of: finna - search/advanced/map.phtml -->
<?php
$this->jsTranslations()->addStrings(
    [
        'radiusPrefix' => 'Radius',
        'circleCaption' => 'Select Area',
        'clearCaption' => 'Clear Selections',
        'removeCaption' => 'Clear',
        'map_zoom_in' => 'map_zoom_in',
        'map_zoom_out' => 'map_zoom_out',
    ]
);
  $items = [];
  if ($saved && ($filters = $saved->getParams()->getGeographicFilters($saved->getParams()->getFilterList()))) {
    foreach ($filters as $filter) {
      foreach (preg_split('/\s+OR\s+/', $filter) as $item) {
        $items[] = $item;
      }
    }
  }
?>
<div aria-hidden="true" class="search-map-container">
  <button class="list-group-item title collapsed" type="button" data-toggle="collapse" data-target="#advanced-search-map" controls="advanced-search-map" aria-expanded="false">
    <span class="facet-title">
      <?=$this->transEsc('Geographical Area') ?>
      <?=$this->icon('collapse', 'facet-title-icon') ?>
    </span>
  </button>
  <div id="advanced-search-map" class="map-container collapse">
    <fieldset class="well map">
      <legend class="sr-only"><?=$this->transEsc('Geographical Area') ?></legend>
      <div class="selection-map-canvas"></div>
      <div class="information information-geo bg-info"><p class="information-text"><?=$this->transEsc('advanced_search_information_text_map')?></p></div>
    </fieldset>
  </div>
</div>

<?php
  $jsItems = json_encode($items);
  $script = <<<JS
      function setMapFacet() {
        var options = {
          items: $jsItems
        };
        finna.advSearch.initMap(options);
      };
      $('#advanced-search-map').one('shown.bs.collapse', function openMapFacet() {
        setMapFacet();
      });
      JS;
  echo $this->inlineScript(\Laminas\View\Helper\HeadScript::SCRIPT, $script, 'SET');
?>
<!-- END of: finna - search/advanced/map.phtml -->
