<!-- START of: finna - search/advanced/multiselect.phtml -->
<?php
  $filenameHeader = 'advanced/' . $field . '-facet-information-header.phtml';
  $filenameFooter = 'advanced/' . $field . '-facet-information-footer.phtml';
?>
  <?php ob_start(); ?>
    <div class="list-group-item facet">
    <div id="<?=$this->escapeHtmlAttr(str_replace(' ', '', $this->field))?>" class="solr-adv-filter <?=$this->escapeHtmlAttr(str_replace(' ', '', $this->field))?>-container">
      <?php if ($this->resolver($filenameHeader)): ?>
        <?=$this->render($filenameHeader) ?>
      <?php endif; ?> 
      <select class="finna-multiselect init" aria-labelledby="limit_<?=$this->escapeHtmlAttr(str_replace(' ', '', $this->field))?>" name="filter[]"  multiple="multiple">
        <?php if (is_array($this->hierarchicalFacets) && in_array($this->field, $this->hierarchicalFacets)): ?>
          <?php foreach ($this->list['list'] as $key => $value): ?>
            <?php
              $isParent = isset($value['opt_group_start']) && $value['opt_group_start'];
              $isChild = $value['level'] !== '0';
              $display = str_pad('', 4 * $value['level'] * 6, '&nbsp;', STR_PAD_LEFT) . $this->escapeHtml($value['displayText']);
            ?>
            <option class="<?= $isParent ? 'option-parent' : ''; ?> <?= $isChild ? 'option-child child-width-' . $value['level'] : ''?>" value="<?=$this->escapeHtmlAttr(($value['operator'] == 'OR' ? '~' : '') . $this->field . ':"' . $value['value'] . '"')?>"<?=(isset($value['selected']) && $value['selected']) ? ' selected="selected"' : ''?>><?=$display?></option>
          <?php endforeach; ?>
        <?php else: ?>
          <?php foreach ($this->list['list'] as $value): ?>
            <option value="<?=$this->escapeHtmlAttr(($value['operator'] == 'OR' ? '~' : '') . $this->field . ':"' . $value['value'] . '"')?>"<?=(isset($value['selected']) && $value['selected']) ? ' selected="selected"' : ''?>><?=$this->escapeHtml($value['displayText'])?></option>
          <?php endforeach; ?>
        <?php endif; ?>
      </select>
      <input aria-labelledby="limit_<?=$this->escapeHtmlAttr(str_replace(' ', '', $this->field))?>" class="finna-multiselect search form-control" type="text" placeholder="<?= $this->transEsc('search_placeholder') ?>">
      <ul aria-multiselectable="true" role="listbox" aria-label="<?= $this->transEsc('Add filter') . ' ' . $this->transEsc($this->list['label']) ?>" tabindex="0" class="finna-multiselect done" aria-activedescendant=""></ul>
      <button type="button" class="finna-multiselect clear btn btn-link"><?= $this->transEsc('Clear Selections') ?></button> 
      <?php if ($this->resolver($filenameFooter)): ?>
        <?=$this->render($filenameFooter) ?>
      <?php endif; ?>  
    </div>
  </div>
  <?php $content = ob_get_clean(); ?>
        <?= $this->render('components/molecules/containers/finna-panel', [
          'attributes' => ['class' => ['finna-panel-borderless', 'title', 'list-group']],
          'heading' => $this->transEsc($this->list['label']),
          'headingLevel' => 4,
          'content' => $content,
          'headingId' => $this->transEsc($this->list['label'] . '-title'),
          'collapseId' => $this->transEsc($this->list['label']),
          'collapsed' => false,
  ]); ?>
<!-- END of: finna - search/advanced/multiselect.phtml -->
