<!-- START of: finna - search/advanced/solr.phtml -->
<?=$this->render('search/advanced/solr-facets.phtml')?>
<?php if ($this->config()->isGeographicMapVisible()): ?>
  <?=$this->render('search/advanced/map.phtml', ['searchClassId' => $this->searchClassId, 'saved' => $this->saved])?>
<?php endif; ?>
<?php if (isset($this->illustratedLimit)): ?>
  <fieldset>
    <legend><?=$this->transEsc('Illustrated')?>:</legend>
    <?php foreach ($this->illustratedLimit as $current): ?>
      <input id="illustrated_<?=$this->escapeHtmlAttr($current['value'])?>" type="radio" name="illustration" value="<?=$this->escapeHtmlAttr($current['value'])?>"<?=$current['selected'] ? ' checked="checked"' : ''?>>
      <label for="illustrated_<?=$this->escapeHtmlAttr($current['value'])?>"><?=$this->transEsc($current['text'])?></label><br>
    <?php endforeach; ?>
  </fieldset>
<?php endif; ?>
<!-- END of: finna - search/advanced/solr.phtml -->
