<!-- START of: finna - search/advanced/usage_rights_ext_str_mv-facet-information-footer.phtml -->
<div class="information additional-info alert-info">  
    <p class="information-text"><?=$this->transEsc('usage_rights_ext_info')?></p>
    <a class="information-text" href="<?=$this->url('content-page', ['page' => 'terms'])?>#terms"><?=$this->transEsc('usage_rights_ext_info_more_link')?></a>
</div>
    <!-- END of: finna - search/advanced/usage_rights_ext_str_mv-facet-information-footer.phtml -->
