<!-- START of: finna - search/advanced/usage_rights_ext_str_mv-facet-information.phtml -->
<div class="information additional-info">
    <p class="information-text"><?=$this->translate('usage_rights_ext_header')?></p>
</div>
<div class="information additional-info">  
    <p class="information-text"><?=$this->translate('usage_rights_ext_info')?></p>
    <a class="additional-info additional-info-link" href="<?=$this->url('content-page', ['page' => 'terms'])?>#terms"><?=$this->transEsc('usage_rights_ext_info_more_link')?></a>
</div>
<!-- END of: finna - search/advanced/usage_rights_ext_str_mv-facet-information.phtml -->
