<?php // This template is a text fragment of a complete OpenAPI specification ?>
Return a single record or multiple records. POST method may also be used if sending a long request.

See https://www.kiwi.fi/display/Finna/Finna+API+Terms+of+Use for Finna API Terms of Use.

Note: The CC0 metadata licence does not pertain to the resources linked to the metadata, such as images relating to the entries.

See https://www.kiwi.fi/pages/viewpage.action?pageId=53839221 for more information and examples.
