<?php
  // Only retrieve counts here as needed:
  $id = $this->driver->getUniqueID();
?>
<div class="authority-record-summary-container">
  <?php if ($count = $this->authority()->getCountAsAuthor($id)): ?>
    <?= $this->record($this->driver)->renderTemplate('record-summary.phtml', ['driver' => $this->driver, 'type' => 'author', 'count' => $count, 'summary' => $this->summary['author']]) ?>
  <?php endif; ?>

  <?php if ($count = $this->authority()->getCountAsTopic($id)): ?>
    <?= $this->record($this->driver)->renderTemplate('record-summary.phtml', ['driver' => $this->driver, 'type' => 'topic', 'count' => $count, 'summary' => $this->summary['topic']]) ?>
  <?php endif; ?>
</div>
