<?php
/**
 * Dropdown menu for IIIF functions
 *
 * @param array     manifestUrls   URLs of IIIF manifest to work with
 * @param ?string   uniqueID       Any unique string to be appended to the id
 *                                 attribute of a span containing the manifest
 *                                 URL for copying to the clipboard
 * @param ?bool     alignRight     Align the menu to the trigger button on the
 *                                 right-hand edge
 */
$manifest = $this->manifestUrls[0]['url'];
$encodedManifest = urlencode($manifest);
$r = $this->alignRight ? 'dropdown-menu-end' : '';
$urlContainerId = 'iiif-manifest-url__' . ($this->uniqueID ?? 'container');
$viewers = $this->config()->get('config')->IIIF->externalViewers ?? [];
if ($iiifHelp = $this->content()->findTemplateForLng('content/iiif')) {
  $dropHeaderExtraClasses = ' hstack gap-2';
}
?>
<span class="iiif-manifest-url-container hidden"
      id="<?=$this->escapeHtmlAttr($urlContainerId)?>"
      aria-hidden="true">
  <?=$this->escapeHtml($manifest)?>
</span>
<ul class="dropdown-menu <?=$r?>">
  <li>
    <span class="dropdown-header fs-4<?=$dropHeaderExtraClasses ?? ''?>">
      <?=$this->transEsc('iiif_tools_dropdown_header')?>
    </span>
  </li>
  <?php if ($iiifHelp): ?>
    <li>
      <a class="icon-link"
        href="<?=$this->url('content-page', ['page' => 'iiif']) ?>"
      >
        <?=$this->icon('help', 'icon-link__icon')?>
        <?=$this->transEsc('what does iiif mean')?>
      </a>
    </li>
  <?php endif; ?>
  <li>
    <span class="dropdown-header fs-5<?=$dropHeaderExtraClasses ?? ''?>">
      <?=$this->transEsc('iiif_manifest_link')?>
    </span>
  </li>
  <li>
    <a class="dropdown-item"
       href="<?=$this->escapeHtmlAttr($manifest)?>"
      target="_blank" rel="nofollow" class="iiif-manifest-url-link">
      <?=$this->icon('external-link', 'icon-link__icon')?>
      <span class="icon-link__label">
        <?=$this->transEsc('Open in a new window')?>
      </span>
    </a>
  </li>
  <li class="iiif-manifest-url-list-item">
    <span>
      <?=$this->copyToClipboardButton("#$urlContainerId", false);?>
    </span>
  </li>
  <?php if ($viewers):?>
    <li>
      <span class="dropdown-header fs-5">
        <?=$this->transEsc('open_in_external_viewer')?>
      </span>
    </li>
    <?php
    foreach ($viewers as $viewer):
      [$viewerName, $viewerHref] = explode('|', "$viewer|");
      $viewerHref = str_replace('{manifest}', $encodedManifest, $viewerHref);
      ?>
      <li>
        <a class="dropdown-item btn toolbar-btn icon-link"
           href="<?=$this->escapeHtmlAttr($viewerHref)?>"
           target="_blank"
           rel="nofollow noreferrer">
        <?=$this->icon('external-link', 'icon-link__icon')?>
        <span class="icon-link__label">
          <?=$this->escapeHtml($viewerName)?>
        </span>
        </a>
      </li>
    <?php
    endforeach;
  endif; ?>
</ul>
