<?php
/**
 *
 * @param string    title           Visible title for list (optional).
 * @param int       headingLevel    Level of heading element, h2 as default.
 * @param string    attributes      Attributes applied to the container of scrollable list element.
 * @param array     items           Items (links) in scrollable list.
 *  @param string    type            'link' or 'dropdown' for dropdown menu button, 'link' as default.
 *  @param string    href            'href' attribute.
 *  @param string    label           Link text.
 *  @param string    icon            Icon on the left side of link text, using iconHelper (optional).
 *  @param string    iconElement     Icon on the left side of link text, using i-element (optional).
 *  @param array     dropdownItems   Items (links) in a dropdown menu, only applicable for type 'dropdown'.
 *
 * Params available for dropdownItems:
 * - href
 * - label
 * - icon
 * - iconElement
 */
  $__title = $title ?? '';
  $__headingLevel = $headingLevel ?: 2;
?>
<?php $__attributes = $this->htmlAttributes($attributes ?? []); ?>
<div<?= $__attributes->add('class', ['scrollable-list-container']) ?>>
  <?php if ($__title): ?>
    <h<?=$__headingLevel?> class="scrollable-list-title"><?=$this->transEsc($__title)?></h<?=$__headingLevel?>>
  <?php endif; ?>
  <div class="link-list list-scrollable">
    <button class="list-scrollable__scroll-prev-btn js-scroll-prev hidden" aria-label="<?=$this->transEscAttr('Scroll backward') ?>">
      <?=$this->icon('scrollable-prev')?>
    </button>
    <ul class="list-scrollable__list flex-row flex-nowrap overflow-x-auto">
      <?php foreach ($items ?? [] as $__item): ?>
        <li class="list-scrollable__list-item js-list-item scrollable-list-item">
          <?php $__type = $__item['type'] ?? 'link'; ?>
          <?php if ($__type === 'dropdown'): ?>
            <a class="dropdown-toggle" data-bs-toggle="dropdown" href="#" role="button">
              <?php if (isset($__item['icon'])): ?>
                <?= $this->icon($__item['icon']) ?>
              <?php elseif (isset($__item['iconElement'])): ?>
                <span><i class="icon icon--font <?= $__item['iconElement'] ?>" aria-hidden="true"></i></span>
              <?php endif; ?>
              <?= $this->transEsc($__item['label'] ?? ''); ?>
              <?= $this->icon('collapse'); ?>
            </a>
            <ul class="dropdown-menu">
              <?php foreach ($__item['dropdownItems'] ?? [] as $__dropdownItem): ?>
                <li>
                  <a class="dropdown-item" href="<?=$__dropdownItem['href'] ?? ''?>" >
                    <?php if (isset($__dropdownItem['icon'])): ?>
                      <?= $this->icon($__dropdownItem['icon']) ?>
                    <?php elseif (isset($__dropdownItem['iconElement'])): ?>
                      <span><i class="icon icon--font <?= $__dropdownItem['iconElement'] ?>" aria-hidden="true"></i></span>
                    <?php endif; ?>
                    <?= $this->transEsc($__dropdownItem['label'] ?? ''); ?>
                  </a>
                </li>
              <?php endforeach; ?>
            </ul>
          <?php else: ?>
            <a href="<?=$__item['href'] ?? ''?>">
              <?php if (isset($__item['icon'])): ?>
                <?= $this->icon($__item['icon']) ?>
              <?php elseif (isset($__item['iconElement'])): ?>
                <span><i class="icon icon--font <?= $__item['iconElement'] ?>" aria-hidden="true"></i></span>
              <?php endif; ?>
              <?= $this->transEsc($__item['label'] ?? ''); ?>
            </a>
          <?php endif; ?>
        </li>
      <?php endforeach; ?>
    </ul>
    <button class="list-scrollable__scroll-next-btn js-scroll-next hidden" aria-label="<?=$this->transEscAttr('Scroll forward') ?>">
      <?=$this->icon('scrollable-next')?>
    </button>
  </div>
</div>
<?php
  $script = <<<JS
      finna.scrollableList.initScrollableList();
      JS;
?>
<?=$this->assetManager()->outputInlineScriptString($script);?>
