<!-- START of: finna - search/bulk-action-buttons.phtml -->
<?php if (isset($this->showCheckboxes) && $this->showCheckboxes): ?>
  <div class="bulkActionButtons hidden-print">
    <div class="checkbox">
      <fieldset>
        <legend class="sr-only"><?=$this->transEsc('select_page')?></legend>
        <label>
          <input type="checkbox" class="checkbox-select-all" name="selectAll" id="<?=$this->idPrefix?>addFormCheckboxSelectAll"<?php if($this->formAttr):?> form="<?=$this->escapeHtmlAttr($this->formAttr) ?>"<?php endif; ?>> <?=$this->transEsc('select_page')?>
        </label>
      </fieldset>
    </div>
    <div class="btn-group">
      <?php if (isset($this->showBulkOptions) && $this->showBulkOptions): ?>
        <input id="<?=$this->idPrefix?>ribbon-email" class="btn btn-primary" type="submit" name="email" title="<?=$this->transEscAttr('bookbag_email_selected')?>" value="<?=$this->transEscAttr('Email')?>"<?php if($this->formAttr):?> form="<?=$this->escapeHtmlAttr($this->formAttr) ?>"<?php endif; ?>>
        <?php $exportOptions = $this->export()->getActiveFormats('bulk');
        if (count($exportOptions) > 0): ?>
          <input id="<?=$this->idPrefix?>ribbon-export" class="btn btn-primary" type="submit" name="export" title="<?=$this->transEscAttr('bookbag_export_selected')?>" value="<?=$this->transEscAttr('Export')?>"<?php if($this->formAttr):?> form="<?=$this->escapeHtmlAttr($this->formAttr) ?>"<?php endif; ?>>
        <?php endif; ?>
        <input id="<?=$this->idPrefix?>ribbon-print" class="btn btn-primary" type="submit" name="print" title="<?=$this->transEscAttr('bookbag_print_selected')?>" value="<?=$this->transEscAttr('Print')?>"<?php if($this->formAttr):?> form="<?=$this->escapeHtmlAttr($this->formAttr) ?>"<?php endif; ?>>
        <?php if ($this->userlist()->getMode() !== 'disabled'): ?>
          <input id="<?=$this->idPrefix?>ribbon-save" class="btn btn-primary" type="submit" name="saveCart" title="<?=$this->transEscAttr('bookbag_save_selected')?>" value="<?=$this->transEscAttr('Save')?>"<?php if($this->formAttr):?> form="<?=$this->escapeHtmlAttr($this->formAttr) ?>"<?php endif; ?>>
        <?php endif; ?>
      <?php endif; ?>
      <?php if (isset($this->showCartControls) && $this->showCartControls): ?>
        <input id="<?=$this->idPrefix?>updateCart" type="submit" class="btn btn-primary" name="add" value="<?=$this->transEscAttr('Add to Book Bag')?>"<?php if($this->formAttr):?> form="<?=$this->escapeHtmlAttr($this->formAttr) ?>"<?php endif; ?>>
      <?php endif; ?>
    </div>
  </div>
<?php endif; ?>
<!-- END of: finna - search/bulk-action-buttons.phtml -->
