<!-- START of: finna - search/filters.phtml -->
<?php
  if (!isset($this->params)) {
    // No current search, use last search in memory
    $params = $this->searchMemory()->getLastSearchParams($this->searchClassId);
  } else {
    // clone params so that the manipulation doesn't cause trouble e.g. for facets
    $params = clone $this->params;
  }

  $filterList = $params->getFilterList(true);
  $checkboxFilters = $params->getCheckboxFacets();
  $lastSort = $this->searchMemory()->getLastSort($params->getSearchClassId());
  $options = $this->searchOptions($params->getSearchClassId());
  $hasDefaultsApplied = $params->hasDefaultsApplied();
  $filterCount = $this->searchbox()->getFilterCount($checkboxFilters, $filterList);
  $fromSearchMemory ??= false;

  // Determine whether the only filters applied are the default ones; this controls
  // when we display or hide the reset button:
  $defaultFilters = $options->getDefaultFilters();
  $onlyDefaultsApplied = count($defaultFilters) == $filterCount;
  foreach ($defaultFilters as $currentDefault) {
    if (!$params->hasFilter($currentDefault)) {
      $onlyDefaultsApplied = false;
      break;
    }
  }

  $collectionFilters = isset($isCollectionTab) && $isCollectionTab;
  $advancedSearch = $params->getSearchType() === 'advanced';
?>
<?php ob_start(); ?>
  <?php foreach ($checkboxFilters as $filter): ?>
    <?php if ($filter['selected']): ?>
      <?php
        $removeLink = isset($urlQuery) && !$fromSearchMemory
          ? $urlQuery->removeFilter($filter['filter'])
          : null;
        $desc = $this->translate($filter['desc']);
        $ariaLabel = $this->escapeHtmlAttr($this->translate('Remove filter') . ' ' . $desc);
      ?>
      <?php if ($removeLink): ?>
        <a class="filter-value js-list-link" aria-label="<?=$ariaLabel?>" href="<?=$removeLink?>" data-filter="<?=$this->escapeHtmlAttr($filter['filter'])?>">
          <span class="visually-hidden">
            <?=$this->translate('Remove filter') ?>
          </span>
          <span class="text"><?=$desc // HTML ?></span>
          <?=$this->icon('search-filter-remove') ?>
        </a>
      <?php else: ?>
        <span class="filter-value js-list-link" data-filter="<?=$this->escapeHtmlAttr($filter['filter'])?>">
          <span class="text"><?=$desc // HTML ?></span>
        </span>
      <?php endif; ?>
    <?php endif ?>
  <?php endforeach; ?>

  <?php foreach ($filterList as $field => $data): ?>
    <div class="title-value-pair js-list-link">
      <?php if (is_callable([$params, 'isGeographicFilter']) && $params->isGeographicFilter($data)): ?>
        <?php
          $removeLink = isset($urlQuery) ? $urlQuery->removeFacet($data[0]['field'], $data[0]['value'], $data[0]['operator']) : null;
          $desc = $this->transEsc($field);
          $ariaLabel = $this->escapeHtmlAttr($this->translate('Remove filter') . ' ' . $desc);
        ?>
        <?php if ($removeLink): ?>
          <a
            class="filter-value"
            aria-label="<?=$ariaLabel?>"
            href="<?=$removeLink?>"
            <?php if (isset($urlQuery)): ?>
              data-filter="<?=$this->escapeHtmlAttr($urlQuery->formatFilterString($data[0]['field'], $data[0]['value'], $data[0]['operator']))?>"
            <?php endif; ?>
          >
            <span class="visually-hidden">
              <?=$this->translate('Remove filter') ?>
            </span>
            <span class="text"><?=$this->transEsc($field)?></span>
            <?=$this->icon('search-filter-remove') ?>
          </a>
        <?php else: ?>
          <a class="filter-value" aria-label="<?=$ariaLabel?>" href="<?=$removeLink?>">
            <span class="text"><?=$this->transEsc($field)?></span>
          </a>
        <?php endif; ?>
      <?php else: ?>
        <div class="filter-title-group">
          <span class="filters-title"><?=$this->transEsc($field)?>:</span>
          <?php if (count($data) > 3 && ($this->dropdown ?? true)): ?>
            <div class="search-filter-dropdown dropdown">
              <?php $dropdown = true; ?>
              <?php $safeId = preg_replace('/[^a-zA-Z0-9]/', '', $field); ?>
              <button id="dropdown-toggle-<?=$safeId?>" class="btn btn-primary dropdown-toggle" data-bs-toggle="dropdown" aria-expanded="false">
                <?=$this->transEsc('filter_toggle_entries', ['%%count%%' => count($data)])?>
                <?=$this->icon('dropdown-open')?>
              </button>
              <ul class="dropdown-menu" role="menu" aria-labelledby="dropdown-toggle-<?=$safeId?>">
          <?php else: ?>
            <?php $dropdown = false; ?>
          <?php endif; ?>
          <?php foreach ($data as $index => $value): ?>
            <?php if ($dropdown): ?>
              <li>
            <?php endif; ?>
            <?php
              switch ($value['operator']) {
              case 'NOT':
                $join = $this->transEsc('NOT');
                break;
              case 'OR':
                $join = $this->transEsc('OR');
                break;
              case 'AND':
                $join = $this->transEsc('AND');
                break;
              default:
                $join = '';
              }
              $operatorClass = $this->escapeHtmlAttr(strtolower($value['operator']));

              $isOnlineFacet = ('unrecognized_facet_label' === $field && in_array($value['field'], ['online_boolean', 'free_online_boolean']));
              $desc = $this->escapeHtml($value['displayText']);
            ?>
            <span class="operator-and-term">
              <span class="filters-term filters-<?=$operatorClass?>">
                <?=($index > 0 || 'NOT' === $value['operator']) ? $join : '' ?>
              </span>
              <?php
                $removeLink = isset($this->urlQuery) && !$fromSearchMemory
                  ? $urlQuery->removeFacet($value['field'], $value['value'], $value['operator'])
                  : null;
              ?>
              <?php if ($removeLink): ?>
                <a
                  class="<?=$dropdown ? 'dropdown-item ' : ''?>filter-value filters-<?=$operatorClass?>"
                  href="<?=$removeLink?>"
                  <?php if (isset($urlQuery)): ?>
                    data-filter="<?=$this->escapeHtmlAttr($urlQuery->formatFilterString($value['field'], $value['value'], $value['operator']))?>"
                  <?php endif; ?>
                >
                  <span class="text">
                    <?php // Always handle online_boolean and free_online_boolean even if not configured ?>
                    <?php if ($isOnlineFacet): ?>
                      <?=$this->translate('online_boolean' === $value['field'] ? 'online_material_facet_html' : 'free_online_material_facet_html') ?>
                    <?php else: ?>
                      <?=$desc // HTML ?>
                    <?php endif; ?>
                  </span>
                  <?php if ($removeLink): ?>
                    <?=$this->icon('search-filter-remove') ?>
                  <?php endif; ?>
                </a>
              <?php else: ?>
                <span
                  class="filter-value filters-<?=$operatorClass?>"
                  <?php if (isset($urlQuery)): ?>
                    data-filter="<?=$this->escapeHtmlAttr($urlQuery->formatFilterString($value['field'], $value['value'], $value['operator']))?>"
                  <?php endif; ?>
                >
                  <span class="text">
                    <?php // Always handle online_boolean and free_online_boolean even if not configured ?>
                    <?php if ($isOnlineFacet): ?>
                      <?=$this->translate('online_boolean' === $value['field'] ? 'online_material_facet_html' : 'free_online_material_facet_html') ?>
                    <?php else: ?>
                      <?=$desc // HTML ?>
                    <?php endif; ?>
                  </span>
                </span>
              <?php endif; ?>
            </span>
            <?php if ($dropdown): ?>
              </li>
            <?php endif; ?>
          <?php endforeach; ?>
          <?php if ($dropdown): ?>
              </ul>
            </div>
          <?php endif; ?>
        </div>
      <?php endif; ?>
    </div>
  <?php endforeach; ?>
<?php $filters = trim(ob_get_contents()); ?>
<?php ob_end_clean(); ?>

<?php if ($filters): ?>
  <div class="active-filters finna-filters" role="region" aria-label="<?=$this->transEscAttr('Search Filters')?>">
    <div>
      <?php if (!$collectionFilters || ($collectionFilters && $this->params instanceof Finna\Search\SolrCollection\Params)): ?>
        <?=$filters ?>
      <?php endif; ?>
      <?php if (!$collectionFilters): ?>
        <?php $defaultFilterState = $hasDefaultsApplied || $options->getRetainFilterSetting() || !($defaultSortApplied ?? true) ? ' checked="checked"' : ''; ?>
        <?php
          $resetLink = !$onlyDefaultsApplied && isset($urlQuery)
            ? $urlQuery->removeAllFilters()->resetDefaultFilters() : false;
        ?>
        <div class="filter-options">
          <?php if ($resetLink && $options->shouldDisplayResetFilters()): ?>
            <a class="reset-filters-btn" href="<?=$resetLink?>"><?=$this->transEsc('reset_filters_button')?> (<?=$filterCount?>)</a>
          <?php endif; ?>
        </div>
      <?php endif; ?>
    </div>
  </div>
<?php endif; ?>
<!-- END of: finna - search/filters.phtml -->
