<!-- START of: finna - search/pagination_simple.phtml -->
<?php if ($this->pageCount): ?>
  <?php
    $ulAttrs = $this->htmlAttributes(['class' => 'pagination-simple']);
    if ($this->results->getOptions()->loadResultsWithJsEnabled()) {
      $ulAttrs->add('class', 'js-pagination-simple');
    }
  ?>
  <ul role="presentation" <?=$ulAttrs?>>
    <?php if (isset($this->previous)): ?>
      <li><a href="<?=$this->currentPath() . $this->results->getUrlQuery()->setPage($this->previous)?>"><span class="sr-only"><?=$this->transEsc('page_prev')?></span><?=$this->icon('page-prev') ?></a></li>
    <?php endif; ?>
    <?php // Note: search-stats class is the scroll target for loading results with JS: ?>
    <li class="pagination-text search-stats js-search-stats" data-key="showing_results_of_html">
      <?=
        $this->label ?: $this->translate(
            'showing_results_of_html',
            [
                '%%start%%' => $this->results->getStartRecord(),
                '%%end%%' => $this->results->getEndRecord(),
                '%%total%%' => $this->localizedNumber($this->results->getResultTotal()),
            ]
        )
      ?>
    </li>
    <?php if (isset($this->next)): ?>
      <li><a href="<?=$this->currentPath() . $this->results->getUrlQuery()->setPage($this->next)?>"><span class="sr-only"><?=$this->transEsc('page_next')?></span><?=$this->icon('page-next') ?></a></li>
    <?php endif; ?>
  </ul>
<?php endif; ?>
<!-- END of: finna - search/pagination_simple.phtml -->
