<!-- START of: finna - search/pagination.phtml -->
<?php if ($this->pageCount && (isset($this->previous) || isset($this->next))): ?>
<nav aria-label="<?=$this->transEsc('pagination_label')?>">
  <ul class="pagination hidden-print">
    <?php if (isset($this->previous)): ?>
      <li class="pagination-button">
        <a href="<?=$this->currentPath() . $this->results->getUrlQuery()->setPage(1)?>"><?=$this->icon('pagination-first') ?><span class="sr-only"><?=$this->transEsc('First')?></span></a>
      </li>
      <li class="pagination-button">
        <a href="<?=$this->currentPath() . $this->results->getUrlQuery()->setPage($this->previous)?>"><?=$this->icon('pagination-prev') ?><span class="sr-only"><?=$this->transEsc('Prev')?></span></a>
      </li>
    <?php endif; ?>
    <?php if (count($this->pagesInRange) > 1): ?>
      <?php foreach ($this->pagesInRange as $page): ?>
        <?php if ($page != $this->current): ?>
          <li><a href="<?=$this->currentPath() . $this->results->getUrlQuery()->setPage($page)?>"><?=$page?></a></li>
        <?php else: ?>
          <li class="active" aria-current="true"><span><?=$page?></span></li>
        <?php endif; ?>
      <?php endforeach; ?>
    <?php endif; ?>
    <?php if (isset($this->next)): ?>
      <li class="pagination-button">
        <a href="<?=$this->currentPath() . $this->results->getUrlQuery()->setPage($this->next)?>"><?=$this->icon('pagination-next') ?><span class="sr-only"><?=$this->transEsc('Next');?></span></a>
      </li>
      <li class="pagination-button">
        <a href="<?=$this->currentPath() . $this->results->getUrlQuery()->setPage($this->pageCount)?>"><?=$this->icon('pagination-last') ?><span class="sr-only"><?=$this->transEsc('Last')?></span></a>
      </li>
    <?php endif; ?>
  </ul>
</nav>
<?php endif; ?>
<!-- END of: finna - search/pagination.phtml -->
