<!-- START of: finna - search/searchTabs.phtml -->
<?php
  $module = $this->layout()->templateDir;
  $selectedTabLabel = 'default_empty_label';
  $searchTabArray = [];
?>
<?php if (!empty($searchTabs)): ?>
  <div role="navigation" aria-label="<?=$this->transEscAttr('Search Tabs')?>">
    <?php foreach ($searchTabs as $tab): ?>
      <?php if ($tab['selected']) {
        $this->layout()->currentTabId = $tab['id'];
        $selectedTab = $tab['id'];
      }
      $toggletipKeyHtml = 'tooltip_' . $tab['label'] . '_html';
      if ($this->layout()->templateName !== 'advanced' && !$this->translationEmpty($toggletipKeyHtml)) {
        $toggletip = [
          'icon' => 'help',
          'ariaLabel' => $this->translate('Help') . ' - ' . $this->translate($tab['label']),
          'contentHtml' => $this->translate($toggletipKeyHtml),
          'class' => 'tooltip-' . $tab['label'], // for back-compatibility
        ];
      } else {
        $toggletip = null;
      }
      $searchTabArray[$tab['id']] = [
        'description' => $tab['label'],
        'data-tab-url' => $tab['url'],
        'toggletip' => $toggletip,
      ];
      ?>
    <?php endforeach; ?>
    <?php if (!$this->translationEmpty("search_tab_tip_{$selectedTabLabel}_html")) :?>
      <div class="search-tab-tip">
        <?=$this->translate("search_tab_tip_{$selectedTabLabel}_html");?>
      </div>
    <?php elseif (!$this->translationEmpty("search_tab_tip_{$module}_html")) :?>
      <div class="search-tab-tip">
        <?=$this->translate("search_tab_tip_{$module}_html");?>
      </div>
    <?php endif; ?>
  </div>
  <?=$this->component(
      'tabs',
      [
        'tabs' => $searchTabArray,
        'activeTab' => $selectedTab ?? '',
        'tabNavClasses' => ['nav-tabs'],
        'scrollable' => true,
        'links' => true,
      ]
  )?>
<?php endif; ?>
<!-- END of: finna - search/searchTabs.phtml -->
