<?php
    $options = $this->searchOptions($this->searchClassId);
    $searchHome = $options->getSearchHomeAction();
    $advSearch = $options->getAdvancedSearchAction();
?>
<div class="adv-search-header versions-search-header">
  <div class="adv_search_links">
    <?php if ($advSearch): ?>
      <a href="<?=$this->url($advSearch)?>"><?=$this->icon('search-advanced') ?> <?=$this->transEsc("Start a new Advanced Search")?></a>
    <?php endif; ?>
    <a href="<?=$this->url($searchHome)?>"><?=$this->icon('search') ?> <?=$this->transEsc("Start a new Basic Search")?></a>
  </div>
</div>
