<?php
$data = $this->driver->getExternalData();
$digitized = $data['digitized'];
$items = $data['items'] ?? [];
$fullResImages = $items['fullResImages'] ?? null;
$ocrImages = $items['OCRImages'] ?? null;
$physicalItems = $items['physicalItems'] ?? null;
?>
<?php if (!$digitized): ?>
  <p><?= $this->translate('external_data_not_digitized_html', ['%%url%%' => $this->recordLink()->getActionUrl($this->driver, 'Feedback')]) ?></p>
<?php endif ?>

<?php if ($fullResImages): ?>
  <?= $this->partial('RecordTab/external_data_table.phtml', ['type' => 'fullres_images', 'data' => $fullResImages]); ?>
<?php endif; ?>

<?php if ($ocrImages): ?>
  <?= $this->partial('RecordTab/external_data_table.phtml', ['type' => 'ocr', 'data' => $ocrImages]); ?>
<?php endif; ?>


<?php if ($physicalItems): ?>
  <div role="table" class="external-data physical-items" aria-label="<?= $this->transEscAttr('external_data_tab_physical_items')?>">
    <div role="row" class="tbl-row headers">
      <div role="cell" class="tbl-cell tbl-left"><span role="columnheader"><?= $this->transEsc('external_data_tab_physical_item')?></span></div>
      <div role="cell" class="tbl-cell tbl-right"><span role="columnheader"><?= $this->transEsc('external_data_tab_physical_location')?></span></div>
    </div>
    <?php foreach ($physicalItems as $item): ?>
      <div role="row" class="tbl-row">
        <div class="tbl-cell tbl-left" role="cell">
          <?php $format = $item['format'] ?? $item['type'] ?? ''; if (!empty($format)): ?>
            <?= $this->escapeHtml($format) ?>
          <?php endif; ?>
          <?php $info = $item['info'] ?? ''; if (!empty($info)): ?>
            <span class="info">(<?=$this->escapeHtml($info) ?>)</span>
          <?php endif ?>
          <?php if (!empty($item['physicalLocation'])): ?>
            <?php if (!empty($format) || !empty($info)): ?><br /><?php endif; ?>
            <span class="physical-location"><?=$this->escapeHtml($item['physicalLocation']) ?></span>
          <?php endif ?>
          <?php if (!empty($item['accessRestriction'])): ?>
            <p class="restriction small">(<?=$this->escapeHtml($item['accessRestriction']) ?>)</p>
          <?php endif ?>
        </div>
        <div class="tbl-cell tbl-right location" role="cell">
          <?php if (!empty($item['location'])): ?>
            <span class="location-name"><?=$this->escapeHtml($item['location'])?></span>
          <?php endif; ?>
          <?php if (!empty($item['service'])): ?>
            <span class="service alert alert-info"><?= $this->transEsc('external_data_tab_physical_service')?></span>
          <?php endif; ?>
        </div>
      </div>
    <?php endforeach; ?>
  </div>
<?php endif; ?>
