<!-- START of: finna - RecordTab/hierarchytree.phtml -->
<?php
  $hierarchyTreeList = $this->tab->getTreeList();
  $activeTree = $this->tab->getActiveTree();

  $this->inlineScript(
      \Laminas\View\Helper\HeadScript::SCRIPT,
      "var hierarchySettings = {\n"
      . '    lightboxMode: ' . ($this->layout()->getTemplate() == 'layout/lightbox' ? 'true' : 'false') . ",\n"
      . '    fullHierarchy: ' . ($this->tab->isFullHierarchyVisible() ? 'true' : 'false') . "\n"
      . "};\n",
      'SET'
  );
  $this->jsTranslations()->addStrings(
      ['showTree' => 'hierarchy_show_tree', 'hideTree' => 'hierarchy_hide_tree']
  );
  $this->inlineScript(\Laminas\View\Helper\HeadScript::FILE, 'vendor/jsTree/jstree.min.js');
  $this->inlineScript(\Laminas\View\Helper\HeadScript::FILE, 'hierarchyTree.js');
  echo $this->inlineScript();
?>
<?php if ($this->layout()->getTemplate() == 'layout/lightbox'): ?>
  <h2><?=$this->transEsc($this->tab->getDescription())?></h2>
<?php endif; ?>
<?php if (count($hierarchyTreeList) > 1): ?>
  <div id="treeSelector">
    <?php foreach ($hierarchyTreeList as $hierarchy => $hierarchyTitle): ?>
      <?php if($activeTree == $hierarchy): ?>
        <?=$this->icon('hierarchy') ?> <?=$this->escapeHtml($hierarchyTitle)?>
      <?php else: ?>
        <?=$this->icon('hierarchy', 'text-muted') ?> <a href="<?=$this->escapeHtmlAttr($this->recordLinker()->getTabUrl($this->driver, 'HierarchyTree', ['hierarchy' => $hierarchyID]))?>"><?=$this->escapeHtml($hierarchyTitle)?></a>
      <?php endif; ?>
    <?php endforeach; ?>
  </div>
<?php endif; ?>
<?php if ($activeTree): ?>
  <div id="hierarchyTreeHolder">
    <div id="hierarchyLoading" class="hide"><?=$this->icon('spinner') ?> <?=$this->transEsc('loading_ellipsis')?></div>
    <div id="hierarchyTree" class="hierarchy-tree">
      <input type="hidden" value="<?=$this->escapeHtmlAttr($this->driver->getUniqueId())?>" class="hiddenRecordId">
      <input type="hidden" value="<?=$this->escapeHtmlAttr($activeTree)?>" class="hiddenHierarchyId">
      <input type="hidden" value="<?=$this->escapeHtmlAttr($this->driver->getSourceIdentifier())?>" class="hiddenRecordSource">
      <input type="hidden" value="<?=$this->escapeHtmlAttr($this->treeContext ?? 'Record')?>" class="hiddenContext">
    </div>
    <div class="back-to-up hidden"><?=$this->transEsc('Back to top')?> <?=$this->icon('back-to-up') ?></div>
  </div>
<?php endif; ?>
<!-- END of: finna - RecordTab/hierarchytree.phtml -->
