<!-- START of: finna - RecordTab/holdings-record-urls.phtml -->
<?php
  $openUrl = $this->openUrl($this->driver, 'holdings');
  $openUrlActive = $openUrl->isActive();
  $doi = $this->doi($this->driver, 'holdings');
  $doiActive = $doi->isActive();
  // Account for replace_other_urls setting
  $urls = $this->record($this->driver)->getLinkDetails($openUrlActive);
?>

<?php
  if (empty($urls) && !$openUrlActive && !$doiActive) {
    return;
  }
?>

<div class="table record-holdings-url-table">
  <div class="headers">
    <span class="holdings-url-title"><?=$this->transEsc('Links')?></span>
  </div>
  <div class="holdings-urls">
    <?php foreach ($urls ?? [] as $current): ?>
      <?php if (!$this->driver->tryMethod('urlBlocked', [$current['url'], $current['desc']])): ?>
        <a class="holdings-url-link" href="<?=$this->escapeHtmlAttr($this->proxyUrl($current['url']))?>" target="_blank" aria-label="<?=$this->transEscAttr('external_online_link')?>"><?=$this->icon('external-link') ?> <?=$this->transEsc('default::link_' . $current['desc'], null, $current['desc'])?> <?=$current['part'] ?? ''?></a>
      <?php endif; ?>
    <?php endforeach; ?>
    <?php if ($doiActive): ?>
      <?=$doi->renderTemplate()?>
    <?php endif; ?>
    <?php if ($openUrlActive): ?>
      <?=$openUrl->renderTemplate()?>
      <?php
        $loadOpenURLs = "finna.openUrl.initLinks($('.holdings-urls'));";
        echo $this->inlineScript(\Laminas\View\Helper\HeadScript::SCRIPT, $loadOpenURLs, 'SET')
      ?>
    <?php endif; ?>
  </div>
</div>
<!-- END of: finna - RecordTab/holdings-record-urls.phtml -->
