<div role="table" class="external-data <?= $this->escapeHtmlAttr($this->type) ?>" aria-label="<?= $this->transEscAttr("holdings_archive_tab_{$this->type}", [], $this->type)?>">
  <div role="row" class="tbl-col headers"><span role="columnheader"><?= $this->transEsc("holdings_archive_tab_{$this->type}", [], $this->type)?></span></div>
  <?php if ($info = $data['info'] ?? null): ?>
    <div role="row" class="tbl-row info">
      <div role="cell">
        <span><?=$this->translate('More Information')?></span>
        <ul>
          <?php foreach ($info as $infoItem): ?>
            <li><?= $this->escapeHtml($infoItem) ?></li>
          <?php endforeach; ?>
        </ul>
      </div>
    </div>
  <?php endif; ?>
  <div role="rowgroup" class="items">
    <?php foreach ($data['items'] as $item): ?>
      <div role="row" class="tbl-row">
        <div role="cell">
          <a target="_blank" href="<?=$this->escapeHtmlAttr($item['url'])?>" aria-label="<?=$this->transEscAttr('external_online_link')?>"><?=$this->icon('external-link') ?> <?=$this->escapeHtml($item['label'])?></a>
        </div>
      </div>
    <?php endforeach; ?>
  </div>
</div>
