<?php
  $images = $item->getAllImages();
  $driver = $this->record($this->item)->getDriver();
  $formats = $driver->tryMethod('getFormats');
  $noImage = empty($images[0]['urls']['medium']);
?>
<div class="similar-carousel-item">
  <div class="similar-carousel-image <?= $noImage ? 'no-image' : ''?>">
    <?php if ($noImage): ?>
      <div class="iconlabel format-<?=$this->record($driver)->getFormatClass(end($formats))?>"></div>
    <?php else: ?>
      <img data-src="<?=$images[0]['urls']['medium']?>" alt="">
    <?php endif; ?>
  </div>
  <div class="similar-carousel-text">
    <span class="similar-carousel-item-title" data-toggle="tooltip-hover" data-original-title=<?=$this->escapeHtmlAttr($this->item->getTitle())?>><?=$this->escapeHtml($this->item->getTitle())?></span>
    <?php $authors = $item->getPrimaryAuthors();
    if (!empty($authors)): ?>
      <span class="similar-carousel-item-author" data-toggle="tooltip-hover" data-original-title=<?=$this->escapeHtmlAttr($authors[0])?>><?=$this->escapeHtml($authors[0])?></span>
    <?php endif; ?>
    <div>
      <span class="similar-carousel-format"><?=$this->record($driver)->getFormatList()?></span>
    </div>
  </div>
</div>
