<?php
  if ($externalRatingLink = $this->record($this->driver)->getExternalRatingLink()) {
    echo $externalRatingLink;
    return;
  }
  $user = $this->auth()->getUserObject();
  $ratings = $this->driver->isRatingAllowed();
?>
<!-- START of: finna - RecordTab/usercomments.phtml -->
<div class="comment-list">
  <?=$this->render('record/comments-list.phtml', ['driver' => $this->driver])?>
</div>

<?php if ($user): ?>
  <div class="comment-form-wrapper <?=count($this->record($this->driver)->getComments()) % 2 ? 'even' : 'odd'?>">
    <form class="comment-form" action="<?=$this->escapeHtmlAttr($this->recordLinker()->getActionUrl($this->driver, 'AddComment'))?>" method="post">
      <div class="comment-col">
        <div>
          <input type="hidden" name="id" value="<?=$this->escapeHtmlAttr($this->driver->getUniqueId())?>">
          <input type="hidden" name="source" value="<?=$this->escapeHtmlAttr($this->driver->getSourceIdentifier())?>">
          <input type="hidden" name="commentId">
        </div>
        <div>
          <?php if ($ratings): ?>
            <div class="comment-rating">
              <?=$this->transEsc('Rating by stars')?>:
              <?php $ratingData = $this->ratings()->getRatingData($this->driver, $user->getId()); ?>
              <?=$this->component('star-rating', ['ratingData' => $ratingData, 'allowClear' => 0 === $ratingData['count'] || $this->accountCapabilities()->isRatingRemovalAllowed()]);?>
            </div>
          <?php endif; ?>
          <?php if ($nickname = $this->escapeHtml(trim($this->userPublicName($user)))): ?>
            <div class="nickname-holder">
              <div>
                <b><?= $nickname ?>:</b>
              </div>
            </div>
          <?php endif; ?>
          <textarea name="comment" class="form-control" rows="4" cols="37" maxlength="8000" required></textarea><br>
          <?php if (null !== ($maximumCount = $this->config()->getMaximumDailyCommentCount($user))): ?>
            <div class="alert alert-info">
              <?=$this->transEsc('comment_daily_limit', ['count' => $maximumCount], useIcuFormatter: true) ?>
            </div>
          <?php endif; ?>
        </div>
        <?php if ($this->tab->isCaptchaActive()): ?>
          <?=$this->captcha()->html(true, false) ?>
        <?php endif; ?>
        <input class="btn btn-primary save" data-label-new="<?=$this->transEscAttr('Add your comment') ?>" data-label-edit="<?=$this->transEscAttr('Save') ?>" data-loading-text="<?=$this->transEscAttr('Submitting') ?><?=$this->transEscAttr('eol_ellipsis')?>" type="submit" value="<?=$this->transEscAttr('Add your comment')?>">
        <input class="btn btn-primary cancel hide" type="submit" value="<?=$this->transEscAttr('Reset')?>">
        <div class="loading-spinner js-loading-spinner hidden"><?=$this->icon('spinner') ?> <?=$this->translate('loading_ellipsis')?></div>
      </div>
      <div class="comment-col">
        <?=$this->icon('info', 'comment-info-icon') ?>
        <div class="comment-description">
          <?=$this->translate('user_comment_description_html', ['%%url%%' => $this->url('content-page', ['page' => 'help-comments-ratings'])]);?>
        </div>
      </div>
      <div class="clearfix"></div>
    </form>
  </div>
<?php else: ?>
  <div>
    <?php $singleSignOn = $this->auth()->hasSessionInitiator(); ?>
    <a href="?login=true&amp;catalogLogin=true" class="btn btn-primary login-link"<?php if (!$singleSignOn): ?> data-lightbox<?php endif; ?> title="<?=$this->transEscAttr('Login')?>"><?= $this->transEsc('Login'); ?></a> <?= $this->transEsc('comment_login') ?>
  </div>
<?php endif; ?>
<!-- END of: finna - RecordTab/usercomments.phtml -->
