<?php // Do not add start and end comments ?>
<?php foreach ($orgInfo['accessibilityInfo'] ?? [] as $accessibilityGroup): ?>
  <h5 class="accessibility-group-heading"><?=$this->escapeHtml($accessibilityGroup['heading'])?></h5>
  <div class="accessibility-group-statements">
    <?php foreach ($accessibilityGroup['statements'] as $statement): ?>
      <p><?=$this->escapeHtml($statement)?>
    <?php endforeach; ?>
  </div>
<?php endforeach; ?>
