<?php
  // Render the new cookie consent initialization script if necessary:
 if (!empty($this->consentDialogConfig)) {
  $this->headScript()->appendFile('vendor/cookieconsent.umd.js');
  $this->headScript()->appendFile('cookie.js');

  // Quick fix for null domain:
  $consentDialogConfig = $this->consentDialogConfig;
  if (array_key_exists('domain', $consentDialogConfig['cookie']) && $consentDialogConfig['cookie']['domain'] === null) {
    unset($consentDialogConfig['cookie']['domain']);
  }
  $configJson = json_encode(
      [
          'consentDialog' => $consentDialogConfig,
          'controlledVuFindServices' => $this->controlledVuFindServices,
      ]
  );
  $this->headScript()->appendScript("window.addEventListener('load', function() { VuFind.cookie.setupConsent($configJson); });");
  return;
}
?>
<!-- END of: finna - Helpers/cookie-consent.phtml -->
