<!-- START of: finna - Helpers/holding-callnumber.phtml -->
<div class="location-link-text">
  <?php if (isset($this->locationServiceUrl)): ?>
    <a class="location-service <?=$this->locationServiceModal ? ' location-service-modal' : ''?>" href="<?=$this->locationServiceUrl?>"<?=$this->locationServiceModal ? ' data-lightbox-href="' . $this->url('locationservice-modal') . '?callnumber=' . urlencode(($this->callnumber instanceof \VuFind\I18n\TranslatableString) ? $this->callnumber->getDisplayString() : $this->callnumber) . '&amp;collection=' . urlencode($this->collection ?? '') . '&amp;location=' . urlencode($this->location ?? '') . '&amp;title=' . urlencode($this->title) . '&amp;source=' . urlencode($this->source) : '' ?>" target="location-service"><?=$this->icon('map-marker') ?> <?=$this->transEsc($this->callnumber)?></a>
  <?php elseif ($this->callnumber): ?>
    <?php if ($this->page === 'results'): ?>
      (<span><?=$this->transEsc("shelf_location"); ?>: </span><?=$this->transEsc($this->callnumber)?>)
    <?php else: ?>
      <?=$this->transEsc($this->callnumber)?>
    <?php endif; ?>
  <?php endif; ?>
  <?php if ($this->qrCode): ?>
    <div class="dropdown location-service-qrcode">
      <a href="#" class="dropdown-toggle qrcodeLink" data-toggle="dropdown" title="<?=$this->transEsc('QR Code')?>" rel="nofollow">
        <?=$this->icon('qrcode')?><span class="sr-only"><?=$this->transEsc('QR Code')?></span>
      </a>
      <ul class="dropdown-menu qrcode" role="menu">
        <li>
          <script type="text/template" class="qrCodeImgTag">
            <img alt="" src="<?=$this->url('qrcode-show', [], ['query' => ['text' => $this->locationServiceUrl]])?>" rel="nofollow">
          </script>
        </li>
      </ul>
    </div>
  <?php endif; ?>
</div>
<!-- END of: finna - Helpers/holding-callnumber.phtml -->
