<?php if ($embed): ?>
  <?php
    $attrs = $this->attributes;
    $attrs['src'] = $this->src;
    if ($this->title) {
        $attrs['title'] = $this->title;
    }
    if ($this->style && empty($attrs['style'])) {
        $attrs['style'] = $this->style;
    }
    $attrs['frameborder'] = '0';
  ?>
  <?=$this->makeTag('iframe', '', $attrs)?>
<?php else: ?>
  <?php
    $attrs = [
        'class' => 'embedded-content-placeholder',
        'style' => $this->style,
    ];
  ?>
  <div <?=$this->htmlAttributes($attrs)?>>
    <div class="embedded-content-cookie-info">
      <div class="embedded-content-heading">
        <?=$this->transEsc('embedded_content_heading')?>
      </div>
      <div class="embedded-content-description">
        <?php
          $placeholders = [
            '%%serviceBaseUrl%%' => $this->serviceBaseUrl,
            '%%consentCategories%%' => implode(', ', $this->consentCategoriesTranslated),
          ];
        ?>
        <?=$this->translate('embedded_content_description', $placeholders)?>
      </div>
      <div class="embedded-content-actions">
        <a class="btn btn-primary" href="<?=$this->escapeHtmlAttr($this->serviceUrl)?>" target="_blank">
          <?=$this->translate('embedded_content_external_link')?> <i class="fa fa-new-window" aria-hidden="true"></i> <span class="sr-only">(<?=$this->transEsc('Open in a new window')?>)</span>
        </a>
        <a class="btn btn-default" href="#" data-cc="show-preferencesModal" aria-haspopup="dialog"><?=$this->transEsc('Cookie Settings')?></a>
      </div>
    </div>
  </div>
<?php endif; ?>
