<?php if (!$this->translationEmpty('finna rating')): ?>
  <div class="<?=!empty($this->disabled) ? '' : 'hidden'?>"><?=$this->transEsc('finna rating') ?></div>
<?php endif; ?>
<input type="hidden" class="rating" data-fractions="2" value="<?=$this->escapeHtmlAttr(str_replace(',', '.', $this->value ?? 5))?>" <?= !empty($this->disabled) ? 'disabled="disabled" ' : ''?>data-filled="fa fa-star" data-empty="fa fa-star-empty"/>
