<?php // No start or end tags
echo json_encode([
    'js-videojs' => $this->headScript()->itemToString(
        $this->headScript()->createData('text/javascript', ['src' => 'vendor/video.min.js', 'id' => 'js-videojs']),
        '',
        '',
        ''
    ),
    'js-videojs-hotkeys' => $this->headScript()->itemToString(
        $this->headScript()->createData('text/javascript', ['src' => 'vendor/videojs.hotkeys.min.js', 'id' => 'js-videojs-hotkeys']),
        '',
        '',
        ''
    ),
    'js-videojs-quality' => $this->headScript()->itemToString(
        $this->headScript()->createData('text/javascript', ['src' => 'vendor/videojs-contrib-quality-levels.js', 'id' => 'js-videojs-quality']),
        '',
        '',
        ''
    ),
    'js-videojs-chromecast' => $this->headScript()->itemToString(
        $this->headScript()->createData('text/javascript', ['src' => 'vendor/silvermine-videojs-chromecast.min.js', 'id' => 'js-videojs-chromecast']),
        '',
        '',
        ''
    ),
    'js-videojs-airplay' => $this->headScript()->itemToString(
        $this->headScript()->createData('text/javascript', ['src' => 'vendor/silvermine-videojs-airplay.min.js', 'id' => 'js-videojs-airplay']),
        '',
        '',
        ''
    ),
    'js-cast-sender' => $this->headScript()->itemToString(
        $this->headScript()->createData('text/javascript', ['src' => 'https://www.gstatic.com/cv/js/sender/v1/cast_sender.js?loadCastFramework=1', 'id' => 'js-cast-sender']),
        '',
        '',
        ''
    ),
]);
