<?php // No start or end tags
$files = [
    'js-videojs' => 'vendor/video.min.js',
    'js-videojs-hotkeys' => 'vendor/videojs.hotkeys.min.js',
    'js-videojs-quality' => 'vendor/videojs-contrib-quality-levels.js',
    'js-videojs-airplay' => 'vendor/silvermine-videojs-airplay.min.js',
];
$scripts = [];
foreach ($files as $id => $file) {
    $scripts[$id] = $this->headScript()->itemToString(
        $this->headScript()->createData('text/javascript', ['src' => $file, 'id' => $id]),
        '',
        '',
        ''
    );
}
echo json_encode($scripts);
