<div class="login-description-terms">
  <p>Go sisačálihuvvo girjerádjogoartta nummiriin, de vurkejuvvo girjerádjogoartta dovddaldat, PIN-koda, sisačáliheaddji namma, šleađgapoastačujuhus ja ruoktogirjerádju neahttabálvalussii.</p>
  <p>Go sisačálihuvvo šleađgapoasttain, de vurkejuvvo sisačáliheaddji namma, šleađgapoastačujuhus ja ruoktogirjerádju.</p>
  <p>Lassedieđut persovdnadieđuid gieđahallamis <a href="<?=$this->url('content-page', ['page' => 'privacy'])?>" data-lightbox-ignore target="_blank"><?=$this->transEsc('Privacy')?>-siiddus</a>.</p>
</div>
