<div class="login-description-terms">
  <p>Girjerádjokoartta nummiriin sisačálidettiin vurkejuvvo neahttabálvalussii girjerádjokoartta dovddaldat, PIN-koda, sisačáliheaddji namma, šleađgapoastačujuhus ja ruovttugirjerádju.</p>
  <p>Šleađgapoastačujuhusain sisačáledettiin vurkejuvvo sisačáliheaddji namma, šleađgapoastačujuhus ja ruovttugirjerádju.</p>
  <p>Lassidiehtu persovdnadieđuid gieđahallamis <a href="<?=$this->url('content-page', ['page' => 'privacy'])?>" data-lightbox-ignore target="_blank"><?=$this->transEsc('Privacy')?>-siiddus</a>.</p>
</div>
