<?php //Don't add START and END comments ?>
<?php
  $formatter = $this->recordDataFormatter();
  $coreFields = $formatter->getData($driver, $formatter->getDefaults('authority'));
?>

<?php $summ = $this->driver->getSummary(); if (!empty($summ)): ?>
<div class="truncate-field description">
  <p class="summary">
    <?php foreach ($summ as $field): ?>
      <?=$this->cleanHtml($field)?><br/>
    <?php endforeach; ?>
  </p>
</div>
<?php endif; ?>

<?php if (!empty($coreFields)): ?>
<table class="table table-finna-record record-details">
  <?php foreach ($coreFields as $current): ?>
    <tr class="<?=$current['context']['class'];?>"><th><?=$this->transEsc($current['label'])?>:</th><td><?=$current['value']?></td></tr>
  <?php endforeach; ?>
</table>
<?php endif; ?>
