<!-- START of: finna - ajax/feed-grid-item.phtml -->
<?php if (isset($item['image']['url'])): ?>
  <span class="grid-image <?= empty($item['image']['url']) ? 'no-image' : ''; ?>">
    <?php if (!empty($item['image']['url'])): ?>
      <img data-src="<?=$this->escapeHtmlAttr($item['image']['url']) ?>" alt="" />
    <?php else: ?>
      <i class="fa fa-calendar-o image-placeholder"></i>
    <?php endif; ?>
  </span>
<?php endif; ?>
<span class="grid-info">
  <?php if (isset($item['dateFull'])): ?>
    <div><?=$this->escapeHtml($item['dateFull']) ?></div>
  <?php endif; ?>
  <div class="title"><?=$this->escapeHtml($this->truncate($item['title'], 40)) ?></div>
  <?php $xcal = $item['xcal'] ?? []; ?>
  <?php if ($xcal): ?>
    <?php if ($xcal['singleDay']): ?>
      <div class="xcal"><i class="fa fa-calendar" aria-label="<?=$this->transEscAttr('xcal_date') ?>"></i> <?=$this->escapeHtml($xcal['startDate']) ?></div>
      <div class="xcal"><i class="fa fa-clock-o" aria-label="<?=$this->transEscAttr('xcal_time') ?>"></i> <?=$this->escapeHtml($xcal['startTime']) ?>&nbsp;&ndash;&nbsp;<?=$this->escapeHtml($xcal['endTime']) ?></div>
    <?php else: ?>
      <div class="xcal"><i class="fa fa-calendar" aria-label="<?=$this->transEscAttr('xcal_date') ?>"></i> <?=$this->escapeHtml($xcal['startDate']) ?> &ndash;&nbsp;<?=$this->escapeHtml($xcal['endDate'])?></div>
    <?php endif; ?>
    <?php if (!empty($xcal['location'])): ?>
      <div class="xcal"><i class="fa fa-map-marker" aria-label="<?=$this->transEscAttr('Location') ?>"></i> <?=$this->escapeHtml($xcal['location']) ?></div>
    <?php endif; ?>
  <?php endif; ?>
  <?php if (isset($item['text'])): ?>
    <div class="feed-text"><?=$this->escapeHtml($this->truncate($item['text'], 80)) ?></div>
  <?php endif; ?>
</span>
<!-- END of: finna - ajax/feed-grid-item.phtml -->
