<!-- START of: finna - ajax/feed-list.phtml -->
<div class="list-feed<?= $this->images ? ' with-image' : ''; ?>">
<?php if ($this->title || $this->translateTitle): ?><h2 class="feed-header"><?= $this->translateTitle ? $this->transEsc($this->translateTitle) : $this->escapeHtml($this->title) ?></h2><?php endif; ?>
<?php if (isset($this->description)): ?><p class="additional-description"><?= $this->translate($this->description) // HTML, intentionally left unescaped ?></p><?php endif; ?>
  <ul>
    <?php $items = isset($this->visualItems) ? array_splice($this->items, 0, $this->visualItems) : $this->items; ?>
    <?php foreach ($items as $item): ?>
      <li>
        <?php if (isset($item['date'])): ?>
          <span class="date"<?php if (isset($item['dateFull'])):?> title="<?=$this->escapeHtmlAttr($item['dateFull'])?>"<?php endif; ?>></span>
        <?php endif; ?>
        <?php if (isset($item['link'])):?>
          <?php
            $linkElement = [
              'href' => $item['link']
            ];
            if ($this->linkTarget) {
              $linkElement['target'] = $this->linkTarget;
            }
            if ($item['modal']) {
              $linkElement['data-lightbox'] = '';
              $linkElement['data-lightbox-title'] = $item['title'];
            }
          ?>
          <a <?=$this->htmlElement()->getAttributes($linkElement)?> data-feed="<?=$this->escapeHtmlAttr($this->feedUrl)?>">
            <?=$this->partial('ajax/feed-list-item.phtml', compact('item'))?>
          </a>
        <?php else: ?>
          <?=$this->partial('ajax/feed-list-item.phtml', compact('item'))?>
        <?php endif; ?>
      </li>
    <?php endforeach; ?>

    <?php if ($this->moreLink): ?>
      <li class="more-link">
        <a<?= $this->linkTarget ? ' target="' . $this->escapeHtmlAttr($this->linkTarget) . '"' : '' ?> href="<?= $this->escapeHtmlAttr($this->moreLink); ?>"><?= $this->transEsc('More'); ?>&hellip;</a>
      </li>
    <?php endif; ?>
  </ul>
</div>
<!-- END of: finna - ajax/feed-list.phtml -->
