<!-- START of: finna - ajax/feed-grid.phtml -->
<div class="feed-grid<?= $this->images ? ' with-image' : ''; ?>">
  <?php
    $itemCount = 0;
  ?>
  <?php foreach ($items as $item): ?>
    <div class="grid-item <?= isset($this->visualItems) ? ($itemCount++ >= $this->visualItems ? 'hidden truncate' : '') : ''; ?> ">
      <?php if (isset($item['link'])):?>
        <?php
          $linkElement = [
            'href' => $item['link'],
          ];
          if ($this->linkTarget) {
            $linkElement['target'] = $this->linkTarget;
          }
          if ($item['modal']) {
            $linkElement['data-lightbox'] = '';
            $linkElement['data-lightbox-title'] = $item['title'];
          }
        ?>
        <a class="grid-link" <?= $this->htmlElement()->getAttributes($linkElement);?>>
          <?=$this->partial('ajax/feed-grid-item.phtml', compact('item'))?>
        </a>
      <?php else: ?>
        <?=$this->partial('ajax/feed-grid-item.phtml', compact('item'))?>
      <?php endif; ?>
    </div>
  <?php endforeach; ?>
</div>
<button class="btn btn-primary show-more-feeds hidden"><?= $this->translate('show_more') ?></button>
<button class="btn btn-primary show-less-feeds hidden"><?= $this->translate('show_less') ?></button>
<!-- END of: finna - ajax/feed-grid.phtml -->
