<!-- START of: finna - ajax/feed-list-item.phtml -->
<?php
  $hasIcon = !empty($item['icon']['name']);
  $hasImg = !empty($item['image']['url']);
?>
<?php if ($hasImg): ?>
  <img src="<?=$this->escapeHtmlAttr($item['image']['url']) ?>" alt="">
  <?php if ($hasIcon && $hasImg): ?>
    <?=$this->partial('Helpers/feed-icon.phtml', ['icon' => $item['icon'], 'wrapper' => true]);?>
  <?php endif; ?>
<?php endif; ?>
<span class="title"><?php if ($hasIcon && !$hasImg): ?><?=$this->partial('Helpers/feed-icon.phtml', ['icon' => $item['icon']]);?><?php endif; ?> <?=$this->escapeHtml($item['title']) ?></span>
<?php if ($item['xcal'] ?? []): ?>
  <div class="xcal-fields">
    <?php if (!empty($xcal['startDate'])): ?>
      <?php if ($xcal['singleDay']): ?>
        <p class="xcal"><i class="fa fa-calendar" aria-label="<?=$this->transEscAttr('xcal_date') ?>"></i> <?=$this->escapeHtml($xcal['startDate']) ?></p>
        <?php if (!empty($xcal['startTime'])): ?>
          <p class="xcal"><i class="fa fa-clock-o" aria-label="<?=$this->transEscAttr('xcal_time') ?>"></i> <?=$this->escapeHtml($xcal['startTime']) ?>&nbsp;&ndash;&nbsp;<?=$this->escapeHtml($xcal['endTime'] ?? '') ?></p>
        <?php endif; ?>
      <?php else: ?>
        <p class="xcal"><i class="fa fa-calendar" aria-label="<?=$this->transEscAttr('xcal_date') ?>"></i> <?=$this->escapeHtml($xcal['startDate']) ?> &ndash;&nbsp;<?=$this->escapeHtml($xcal['endDate'])?></p>
      <?php endif; ?>
    <?php endif; ?>
    <?php if (!empty($xcal['location'])): ?>
      <p class="xcal"><i class="fa fa-map-marker" aria-label="<?=$this->transEscAttr('Location') ?>"></i> <?=$this->escapeHtml($xcal['location']) ?></p>
    <?php endif; ?>
  </div>
<?php endif; ?>
<?php if (isset($item['text'])): ?><span class="text"><?=$this->escapeHtml($item['text']) ?></span><?php endif; ?>
<!-- END of: finna - ajax/feed-list-item.phtml -->
