<!-- START of: finna - ajax/feed-grid-item.phtml -->
<?php
  $hasIcon = !empty($item['icon']['name']);
  $hasImg = !empty($item['image']['url']);
?>
<?php if (isset($item['image']['url'])): ?>
  <span class="grid-image <?= empty($item['image']['url']) ? 'no-image' : ''; ?>">
    <?php if (!empty($item['image']['url'])): ?>
      <img data-src="<?=$this->escapeHtmlAttr($item['image']['url']) ?>" alt="">
    <?php else: ?>
      <i class="fa fa-calendar-o image-placeholder"></i>
    <?php endif; ?>
  </span>
  <?php if ($hasIcon && $hasImg): ?>
    <?=$this->partial('Helpers/feed-icon.phtml', ['class' => 'smaller', 'icon' => $item['icon'], 'wrapper' => true]);?>
  <?php endif; ?>
<?php endif; ?>
<span class="grid-info">
  <?php if (isset($item['dateFull'])): ?>
    <div><?=$this->escapeHtml($item['dateFull']) ?></div>
  <?php endif; ?>
  <div class="title">
    <p><?php if ($hasIcon && !$hasImg): ?><?=$this->partial('Helpers/feed-icon.phtml', ['icon' => $item['icon']]);?><?php endif; ?> <?=$this->escapeHtml($this->truncate($item['title'], 40)) ?></p>
  </div>
  <?php if ($xcal = $item['xcal'] ?? []): ?>
    <?php if (!empty($xcal['startDate'])): ?>
      <?php if ($xcal['singleDay']): ?>
        <div class="xcal"><i class="fa fa-calendar" aria-label="<?=$this->transEscAttr('xcal_date') ?>"></i> <?=$this->escapeHtml($xcal['startDate']) ?></div>
        <?php if (!empty($xcal['startTime'])): ?>
          <div class="xcal"><i class="fa fa-clock-o" aria-label="<?=$this->transEscAttr('xcal_time') ?>"></i> <?=$this->escapeHtml($xcal['startTime']) ?>&nbsp;&ndash;&nbsp;<?=$this->escapeHtml($xcal['endTime'] ?? '') ?></div>
        <?php endif; ?>
      <?php else: ?>
        <div class="xcal"><i class="fa fa-calendar" aria-label="<?=$this->transEscAttr('xcal_date') ?>"></i> <?=$this->escapeHtml($xcal['startDate']) ?> &ndash;&nbsp;<?=$this->escapeHtml($xcal['endDate'])?></div>
      <?php endif; ?>
    <?php endif; ?>
    <?php if (!empty($xcal['location'])): ?>
      <div class="xcal"><i class="fa fa-map-marker" aria-label="<?=$this->transEscAttr('Location') ?>"></i> <?=$this->escapeHtml($xcal['location']) ?></div>
    <?php endif; ?>
  <?php endif; ?>
  <?php if (isset($item['text'])): ?>
    <div class="feed-text"><?=$this->escapeHtml($this->truncate($item['text'], 80)) ?></div>
  <?php endif; ?>
</span>
<!-- END of: finna - ajax/feed-grid-item.phtml -->
