<!-- START of: finna - ajax/feed-carousel.phtml -->
<?php if ($this->title || $this->translateTitle): ?>
  <h2 class="carousel-header"><?=$this->translateTitle ? $this->transEsc($this->translateTitle) : $this->escapeHtml($this->title); ?></h2>
<?php endif; ?>
<?php if (isset($this->description)): ?>
  <p class="additional-description"><?=$this->translate($this->description) // HTML, intentionally left unescaped ?></p>
<?php endif; ?>
<div class="feed-content-container">
  <div class="splide__arrows">
    <button class="splide__arrow splide__arrow--prev">
      <?=$this->icon('chevron-right')?>
    </button>
    <button class="splide__arrow splide__arrow--next">
      <?=$this->icon('chevron-right')?>
    </button>
  </div>
  <div class="splide__track carousel">
    <ul class="splide__list carousel-feed">
      <?php $items = isset($this->visualItems) ? array_splice($this->items, 0, $this->visualItems) : $this->items; ?>
      <?php foreach ($items as $item): ?>
        <li class="splide__slide feed-item-holder">
          <?php if (isset($item['link'])): ?>
            <?php
              $linkElement = [];
              $ariaLabel = '';
              if (isset($item['link'])) {
                $linkElement['href'] = $item['link'];
              }
              if (isset($item['isExternal']) ?? false) {
                $ariaLabel = $this->transEsc('external_link') . ' ';
              }
              if ($this->linkTarget) {
                $linkElement['target'] = $this->linkTarget;
                if ($linkElement['target'] === '_blank') {
                  $ariaLabel .= $this->transEsc('Open in a new window');
                }
              }
              if ($ariaLabel) {
                $linkElement['aria-label'] = $ariaLabel;
              }
              if ($item['modal']) {
                $linkElement['data-lightbox'] = '';
                $linkElement['data-lightbox-title'] = $item['title'];
              }
              $linkTextEsc = $this->transEsc($this->linkText ? $this->linkText : 'To the record');
            ?>
            <a class="feed-link" <?=$this->htmlElement()->getAttributes($linkElement)?>>
              <?=$this->partial("ajax/feed-$this->type-item.phtml", compact('item', 'linkTextEsc'))?>
            </a>
          <?php else: ?>
            <?=$this->partial("ajax/feed-$this->type-item.phtml", compact('item', 'linkTextEsc'))?>
          <?php endif; ?>
        </li>
      <?php endforeach; ?>
    </ul>
  </div>
</div>
<div class="carousel-pagination-wrapper">
  <div class="carousel-autoplay"></div>
  <ul class="splide__pagination"></ul>
  <div class="carousel-block"></div>
</div>
<!-- END of: finna - ajax/feed-carousel.phtml -->
