<!-- START of: finna - ajax/feed-carousel-item.phtml -->
<?php
  $clickableElement = !$this->touchDevice && !isset($this->linkText);
  $clickableLink = !$clickableElement;
  $hasIcon = !empty($item['icon']['name']);
  $hasImg = !empty($item['image']['url']);
?>
<?php if ($hasIcon && $hasImg): ?>
  <?=$this->partial('Helpers/feed-icon.phtml', ['icon' => $item['icon'], 'wrapper' => true]);?>
<?php endif; ?>
<?php if (isset($item['title'])): ?>
  <div class="sr-only">
    <p><?=$this->escapeHtml($item['title'])?></p>
  </div>
<?php endif; ?>
<div class="carousel-text" aria-hidden="true" tabindex="-1">
  <?php if (isset($item['title'])): ?>
    <div class="carousel-hover-title">
      <p><?=$this->escapeHtml($this->truncate($item['title'], 70))?></p>
      <p class="carousel-more show-link"><?=$this->icon('carousel-follow-link')?></p>
    </div>
    <p class="carousel-more carousel-close hidden"><?=$this->icon('carousel-close')?></p>
  <?php endif; ?>
  <?php if (isset($item['dateFull'])): ?>
    <span class="carousel-date carousel-hover-date"><?=$this->transEsc('Published')?> <?=$this->escapeHtml($item['dateFull'])?></span>
  <?php endif; ?>
  <div class="text">
    <?php if ($xcal = $item['xcal'] ?? []): ?>
      <?php if (!empty($xcal['startDate'])): ?>
        <?php if ($xcal['singleDay']): ?>
          <p class="xcal"><?=$this->icon('feed-xcal-date') ?><span class="sr-only"><?=$this->transEscAttr('xcal_date') ?></span> <?=$this->escapeHtml($xcal['startDate']) ?></div>
          <?php if (!empty($xcal['startTime'])): ?>
            <p class="xcal"><?=$this->icon('feed-xcal-time') ?><span class="sr-only"><?=$this->transEscAttr('xcal_time') ?></span> <?=$this->escapeHtml($xcal['startTime']) ?>&nbsp;&ndash;&nbsp;<?=$this->escapeHtml($xcal['endTime'] ?? '') ?></p>
          <?php endif; ?>
        <?php else: ?>
          <p class="xcal"><?=$this->icon('feed-xcal-date') ?><span class="sr-only"><?=$this->transEscAttr('xcal_date') ?></span> <?=$this->escapeHtml($xcal['startDate']) ?> &ndash;&nbsp;<?=$this->escapeHtml($xcal['endDate'])?></p>
        <?php endif; ?>
      <?php endif; ?>
      <?php if (!empty($xcal['location'])): ?>
        <p class="xcal"><?=$this->icon('feed-xcal-location') ?><span class="sr-only"><?=$this->transEscAttr('Location') ?></span> <?=$this->escapeHtml($xcal['location']) ?></p>
      <?php endif; ?>
    <?php endif; ?>
    <p><?=$this->escapeHtml($item['text']) ?></p>
  </div>
  <div class="carousel-text-shadow"></div>
  <?php if ($clickableLink): ?>
    <span class="carousel-description"><?= $linkTextEsc ?></span>
  <?php endif; ?>
</div>
<?php if ($hasImg): ?>
  <div class="wrapper" aria-hidden="true">
    <img data-src="<?=$this->escapeHtmlAttr($item['image']['url']) ?>" alt="<?=$this->transEsc('Image');?><?php if (isset($item['title'])): ?>: <?=$this->escapeHtml($item['title']) ?><?php endif; ?>">
  </div>
<?php endif; ?>
<?php if (isset($item['title']) || isset($item['dateFull'])): ?>
  <div class="carousel-slide-header" aria-hidden="true">
    <p>
      <?php if ($hasIcon && !$hasImg): ?><?=$this->partial('Helpers/feed-icon.phtml', ['icon' => $item['icon']]);?><?php endif; ?>
      <?php if (isset($item['title'])): ?>
        <?=$this->escapeHtml($this->truncate($item['title'], 70));?>
      <?php endif; ?>
      <?php if (isset($item['dateFull'])): ?>
        <span class="carousel-header-date carousel-date"><?=$this->transEsc('Published')?> <?=$this->escapeHtml($item['dateFull'])?></span>
      <?php endif; ?>
      <span class="carousel-slide-more carousel-show hidden"><?=$this->icon('carousel-show')?></span>
      <span class="carousel-slide-more carousel-close hidden"><?=$this->icon('carousel-close')?></span>
    </p>
  </div>
<?php endif; ?>
<!-- END of: finna - ajax/feed-carousel-item.phtml -->
