<!-- START of: finna - ajax/feed-carousel-item.phtml -->
<?php
  $clickableElement = !$this->touchDevice && !isset($this->linkText);
  $clickableLink = !$clickableElement;
  $hasIcon = !empty($item['icon']['name']);
  $hasImg = !empty($item['image']['url']);
?>
<?php if ($hasIcon && $hasImg): ?>
  <?=$this->partial('Helpers/feed-icon.phtml', ['icon' => $item['icon'], 'wrapper' => true]);?>
<?php endif; ?>
<?php if (isset($item['text']) || $clickableLink): ?>
  <div class="sr-only">
    <p><?=$this->escapeHtml($item['text'])?></p>
    <?php if ($clickableLink): ?>
      <span class="carousel-description"><?= $linkTextEsc ?></span>
    <?php endif; ?>
  </div>
<?php endif; ?>
<div class="carousel-text" aria-hidden="true">
  <?php if (isset($item['title'])): ?>
    <div class="carousel-hover-title">
      <p><?=$this->escapeHtml($this->truncate($item['title'], 70))?></p>
      <p class="carousel-more"><?=$this->icon('carousel-more')?></p>
    </div>
  <?php endif; ?>
  <?php if (isset($item['dateFull'])): ?>
    <span class="carousel-date carousel-hover-date"><?=$this->transEsc('Published')?> <?=$this->escapeHtml($item['dateFull'])?></span>
  <?php endif; ?>
  <div class="text">
    <?php if ($xcal = $item['xcal'] ?? []): ?>
      <?php if (!empty($xcal['startDate'])): ?>
        <?php if ($xcal['singleDay']): ?>
          <p class="xcal"><i class="fa fa-calendar" aria-label="<?=$this->transEscAttr('xcal_date') ?>"></i> <?=$this->escapeHtml($xcal['startDate']) ?></div>
          <?php if (!empty($xcal['startTime'])): ?>
            <p class="xcal"><i class="fa fa-clock-o" aria-label="<?=$this->transEscAttr('xcal_time') ?>"></i> <?=$this->escapeHtml($xcal['startTime']) ?>&nbsp;&ndash;&nbsp;<?=$this->escapeHtml($xcal['endTime'] ?? '') ?></p>
          <?php endif; ?>
        <?php else: ?>
          <p class="xcal"><i class="fa fa-calendar" aria-label="<?=$this->transEscAttr('xcal_date') ?>"></i> <?=$this->escapeHtml($xcal['startDate']) ?> &ndash;&nbsp;<?=$this->escapeHtml($xcal['endDate'])?></p>
        <?php endif; ?>
      <?php endif; ?>
      <?php if (!empty($xcal['location'])): ?>
        <p class="xcal"><i class="fa fa-map-marker" aria-label="<?=$this->transEscAttr('Location') ?>"></i> <?=$this->escapeHtml($xcal['location']) ?></p>
      <?php endif; ?>
    <?php endif; ?>
    <p><?=$this->escapeHtml($item['text']) ?></p>
  </div>
  <div class="carousel-text-shadow"></div>
  <?php if ($clickableLink): ?>
    <span class="carousel-description"><?= $linkTextEsc ?></span>
  <?php endif; ?>
</div>
<?php if ($hasImg): ?>
  <div class="wrapper" aria-hidden="true">
    <img data-src="<?=$this->escapeHtmlAttr($item['image']['url']) ?>" alt="<?=$this->transEsc('Image');?><?php if (isset($item['title'])): ?>: <?=$this->escapeHtml($item['title']) ?><?php endif; ?>">
  </div>
<?php endif; ?>
<?php if (isset($item['title']) || isset($item['dateFull'])): ?>
  <div class="carousel-slide-header">
    <p>
      <?php if ($hasIcon && !$hasImg): ?><?=$this->partial('Helpers/feed-icon.phtml', ['icon' => $item['icon']]);?><?php endif; ?>
      <?php if (isset($item['title'])): ?>
        <?=$this->escapeHtml($this->truncate($item['title'], 70));?>
      <?php endif; ?>
      <?php if (isset($item['dateFull'])): ?>
        <span class="carousel-header-date carousel-date"><?=$this->transEsc('Published')?> <?=$this->escapeHtml($item['dateFull'])?></span>
      <?php endif; ?>
      <span class="carousel-slide-more hidden"><?=$this->icon('carousel-slide')?></span>
    </p>
  </div>
<?php endif; ?>
<!-- END of: finna - ajax/feed-carousel-item.phtml -->
