<!-- START of: finna - ajax/feed-carousel.phtml -->
<div class="carousel">
  <?php if ($this->title || $this->translateTitle): ?>
    <h2 class="carousel-header"><?=$this->translateTitle ? $this->transEsc($this->translateTitle) : $this->escapeHtml($this->title); ?></h2>
  <?php endif; ?>
  <?php if (isset($this->description)): ?>
    <p class="additional-description"><?=$this->translate($this->description) // HTML, intentionally left unescaped ?></p>
  <?php endif; ?>
  <div class="carousel-feed">
    <?php $items = isset($this->visualItems) ? array_splice($this->items, 0, $this->visualItems) : $this->items; ?>
    <?php foreach ($items as $item): ?>
      <div class="feed-item-holder">
        <?php if (isset($item['link'])): ?>
          <?php
            $linkElement = [];
            if (isset($item['link'])) {
              $linkElement['href'] = $item['link'];
            }
            if ($this->linkTarget) {
              $linkElement['target'] = $this->linkTarget;
            }
            if ($item['modal']) {
              $linkElement['data-lightbox'] = '';
              $linkElement['data-lightbox-title'] = $item['title'];
            }
            $linkTextEsc = $this->transEsc($this->linkText ? $this->linkText : 'To the record');
          ?>
          <a class="feed-link" <?=$this->htmlElement()->getAttributes($linkElement)?>>
            <?=$this->partial("ajax/feed-$this->type-item.phtml", compact('item', 'linkTextEsc'))?>
          </a>
        <?php else: ?>
          <?=$this->partial("ajax/feed-$this->type-item.phtml", compact('item', 'linkTextEsc'))?>
        <?php endif; ?>
      </div>
    <?php endforeach; ?>
  </div>
</div>
<!-- END of: finna - ajax/feed-carousel.phtml -->
