<?php if ($data = $this->recommend->getTemplateData()): ?>
  <!-- START of: finna - Recommend/Feedback.phtml -->
  <div class="recommendation-feedback alert alert-info">
    <?php $question = $this->translate('recommendation_feedback_question', ['%%term%%' => $data['recommendation']]);?>
    <p><?=$this->transEsc($question)?></p>
    <a href="<?=$this->url('feedback-form', ['id' => 'FeedbackRecommendation'], ['query' => ['data' => $data['formData']]]) ?>"
      class="btn btn-primary" data-lightbox data-lightbox-title="<?=$this->transEscAttr($question)?>"
      onclick="$(this).parent().hide()">
      <?=$this->transEsc('Give Feedback') ?>
    </a>
  </div>
  <?php $this->plugin('piwik')->trackCustomVar($data['customVarName'], $data['customVarValue']); ?>
  <!-- END of: finna - Recommend/Feedback.phtml -->
<?php endif; ?>
