<!-- START of: finna - Recommend/SideFacetsDeferred.phtml -->
<?php
  $this->assetManager()->appendScriptLink('facets.js');
  $this->assetManager()->appendScriptLink('vendor/jquery.colorhelpers.min.js');
  $this->assetManager()->appendScriptLink('vendor/jquery.flot.min.js');
  $this->assetManager()->appendScriptLink('vendor/jquery.flot.selection.min.js');
  $this->assetManager()->appendScriptLink('finna-daterange-vis.js');

  $results = $this->recommend->getResults();

  $resultsTotal = $results->getResultTotal();
  $params = $results->getParams();

  $options = $this->searchOptions($params->getSearchClassId());
  $filterList = $params->getFilterList(true);
  $checkboxFilters = $params->getCheckboxFacets();
  $filterCount = $this->searchbox()->getFilterCount($checkboxFilters, $filterList);
  $defaultFilters = $options->getDefaultFilters();
  $onlyDefaultsApplied = count($defaultFilters) == $filterCount;
  foreach ($defaultFilters as $currentDefault) {
    if (!$params->hasFilter($currentDefault)) {
      $onlyDefaultsApplied = false;
      break;
    }
  }

  $side = $this->config()->offcanvasSide();
?>
<?php if ($resultsTotal > 0): ?>
  <?php
    // We need to pass the current URL query to the Javascript; we use substr() to
    // strip off the leading ? character. The "suppress query" option is used for
    // special search types like course reserves / new items. The AJAX handler needs
    // the real Solr query in order to process facets correctly, so we need to
    // unsuppress it here.
    $querySuppressed = $results->getUrlQuery()->isQuerySuppressed();
    $urlQuery = substr($results->getUrlQuery()->setSuppressQuery(false)->getParams(false), 1);
    $results->getUrlQuery()->setSuppressQuery($querySuppressed); // restore original config
    // We also need to inform the helper about any special parameters used in place
    // of the suppressed query:
    $extraUrlFields = $results->getUrlQuery()->getParamsWithConfiguredDefaults();
    $urlQueryFromResult = $results->getUrlQuery();
    $resetLink = !$onlyDefaultsApplied && isset($urlQueryFromResult) ? $urlQueryFromResult->removeAllFilters()->resetDefaultFilters() : false;
  ?>
  <div class="side-facets-container-ajax" data-search-class-id="<?=$this->escapeHtmlAttr($this->searchClassId) ?>" data-location="<?=$this->escapeHtmlAttr($this->location) ?>" data-config-index="<?=$this->escapeHtmlAttr($this->configIndex)?>" data-query="<?=$this->escapeHtmlAttr($urlQuery)?>" data-query-suppressed="<?=$querySuppressed ? '1' : '0' ?>" data-extra-fields="<?=$this->escapeHtml(implode(',', $extraUrlFields))?>">
    <div class="mobile-navigation-header-container">
      <span class="visible-xs visible-sm close-offcanvas">
      <a class="visible-xs visible-sm close-offcanvas-btn" href="#" role="button" data-toggle="vufind-offcanvas">
        <?='left' === $side ? $this->icon($this->layout()->rtl ? 'offcanvas-hide-left' : 'offcanvas-hide-right') : ''?>
        <span class="btn-link__label"><?=$this->transEsc('navigate_back') ?></span>
        <?='right' === $side ? $this->icon($this->layout()->rtl ? 'offcanvas-hide-right' : 'offcanvas-hide-left') : ''?>
      </a>
      </span>
      <h1 class="hidden-xs hidden-sm"><?=$this->transEsc($this->slot('side-facet-caption')->get('Narrow Search')) ?></h1>
      <?php if (null === $this->slot('side-facet-caption')->get() && !$this->translationEmpty('tooltip_facet_html')): ?>
        <div class="hidden-xs hidden-sm">
          <?=$this->component(
            'finna-toggletip',
            [
              'icon' => 'help',
              'ariaLabel' => $this->translate('Help'),
              'contentHtml' => $this->translate('tooltip_facet_html'),
            ]
          );
          ?>
        </div>
      <?php endif; ?>
      <?php if ($resetLink): ?>
        <a class="reset-filters-btn visible-xs visible-sm" role="button" href="<?=$resetLink?>"><?=$this->transEsc('reset_filters_button')?> (<?=$filterCount?>)</a>
      <?php endif; ?>
    </div>
<?php endif; ?>
<?php $checkboxFilters = $params->getCheckboxFacets(); ?>
<?php $checkboxesShown = false; ?>
<?php if (count($checkboxFilters) > 0):
    foreach ($checkboxFilters as $current) {
      if ($resultsTotal > 0 || $current['selected'] || $current['alwaysVisible']) {
        $checkboxesShown = true;
        break;
      }
    }
  ?>
  <?php if ($checkboxesShown): ?>
    <div class="checkbox-filters">
      <fieldset>
        <legend class="visually-hidden"><?=$this->transEsc('checkbox_filter')?></legend>
        <?=$this->context($this)->renderInContext('Recommend/SideFacets/checkbox-filters.phtml', ['checkboxFilters' => $checkboxFilters, 'results' => $results, 'counts' => false]); ?>
      </fieldset>
    </div>
  <?php endif; ?>
<?php endif; ?>
<?php $extraFilters = $this->extraSideFacetFilters ?? []; ?>
<?php $collapsedFacets = $this->recommend->getCollapsedFacets(); ?>
<?php $hierarchicalFacetSortOptions = $this->recommend->getHierarchicalFacetSortOptions(); ?>
<?php $hierarchicalFacets = $this->recommend->getHierarchicalFacets(); ?>
<?php $filterList = array_merge($params->getFilterList(true), $extraFilters); ?>
<?php $module = $this->layout()->templateDir; ?>
<?php
  $plotFrom = null;
  $daterangeFacetField = null;
  if (null === $module || in_array($module, ['blender', 'search', 'primo'])) {
    $options = $results->getOptions();
    if (is_callable([$options, 'getDateRangeSearchField'])) {
        $daterangeFacetField = $options->getDateRangeSearchField();
    }
    if (is_callable([$params, 'getDateRangeFilter'])) {
      $dateRangeFilter = $params->getDateRangeFilter();
    }
  }
?>
<?php
if ($this->fromStreetSearch) {
  if (($key = array_search('geographic_facet', $collapsedFacets)) !== false) {
    unset($collapsedFacets[$key]);
  }
}
?>
<?=$this->sideFacetExtraControls ?? '' ?>
<?php $activeFacets = $this->recommend->getActiveFacets();
$rangeFacets = $this->recommend->getAllRangeFacets(); ?>
<?php if (!empty($activeFacets) && $resultsTotal > 0): ?>
  <?php
    $msgFailed = $this->transEsc('ajax_load_interrupted');
  ?>
  <?php foreach ($activeFacets as $field => $facetName): ?>
    <?php
      $daterangeFacet = $field == $daterangeFacetField;
      $escAttrField = $this->escapeHtmlAttr($field);
      $isCollapsed = in_array($field, $collapsedFacets);
      $dataTarget = 'side-collapse-' . $escAttrField;
    ?>
    <div class="list-group facet<?= $daterangeFacet ? ' daterange-facet' : '' ?> facet-group" id="side-panel-<?=$escAttrField?>">
      <button class="list-group-item title<?php if ($isCollapsed): ?> collapsed<?php endif ?>" data-bs-toggle="collapse" data-bs-target="#<?=$dataTarget?>" aria-controls="<?=$dataTarget?>" aria-expanded="<?= !$isCollapsed ? 'true' : 'false';?>">
        <span class="facet-title"><?=$this->transEsc($facetName)?></span>
        <?=$this->icon('collapse', 'facet-title-icon') ?>
      </button>
      <div id="facet-title-<?=$escAttrField?>" class="visually-hidden" aria-hidden="true"><?=$this->transEsc($facetName)?></div>
      <div id="<?=$dataTarget?>" aria-labelledby="facet-title-<?=$escAttrField?>" role="group" class="collapse<?= !$isCollapsed ? ' show' : '';?>" data-facet="<?=$escAttrField ?>">
        <span class="facet-load-failed hidden"><?=$msgFailed?></span>
        <div class="facet-load-indicator hidden">
          <?=$this->icon('spinner') ?> <?=$this->transEsc('loading_ellipsis')?>
        </div>
      </div>
    </div>
  <?php endforeach; ?>
<?php endif; ?>
<?php if ($resultsTotal > 0): ?>
  </div>
<?php endif; ?>
<!-- END of: finna - Recommend/SideFacetsDeferred.phtml -->
