<!-- START of: finna - Recommend/SideFacets.phtml -->
<?php
  $this->assetManager()->appendScriptLink('facets.js');

  // Save results/options to $this so they are available to sub-templates:
  $this->results = $results = $this->recommend->getResults();
  $this->options = $options = $results->getOptions();

  $resultsTotal = $results->getResultTotal();

  $params = $results->getParams();
  $filterList = $params->getFilterList(true);
  $checkboxFilters = $params->getCheckboxFacets();
  $filterCount = $this->searchbox()->getFilterCount($checkboxFilters, $filterList);
  $defaultFilters = $options->getDefaultFilters();
  $onlyDefaultsApplied = count($defaultFilters) == $filterCount;
  foreach ($defaultFilters as $currentDefault) {
    if (!$params->hasFilter($currentDefault)) {
      $onlyDefaultsApplied = false;
      break;
    }
  }
  $resetLink = !$onlyDefaultsApplied ? $results->getUrlQuery()->removeAllFilters()->resetDefaultFilters() : false;

  $side = $this->config()->offcanvasSide();
?>
<?php if ($resultsTotal > 0): ?>
  <div class="mobile-sidebar-container">
    <div class="mobile-navigation-header-container">
      <span class="visible-xs visible-sm close-offcanvas">
        <a class="visible-xs visible-sm close-offcanvas-btn" href="#" data-toggle="vufind-offcanvas" role="button">
          <?='left' === $side ? $this->icon($this->layout()->rtl ? 'offcanvas-hide-left' : 'offcanvas-hide-right') : ''?>
          <span class="btn-link__label"><?=$this->transEsc('navigate_back') ?></span>
          <?='right' === $side ? $this->icon($this->layout()->rtl ? 'offcanvas-hide-right' : 'offcanvas-hide-left') : ''?>
        </a>
      </span>
      <h1 class="hidden-xs hidden-sm"><?=$this->transEsc($this->slot('side-facet-caption')->get('Narrow Search')) ?></h1>
      <?php if (null === $this->slot('side-facet-caption')->get() && !$this->translationEmpty('tooltip_facet_html')): ?>
        <div class="hidden-xs hidden-sm">
          <?=$this->component(
            'finna-toggletip',
            [
              'icon' => 'help',
              'aria-label' => $this->translate('Help'),
              'contentHtml' => $this->translate('tooltip_facet_html'),
            ]
          );
          ?>
        </div>
      <?php endif; ?>
      <span class="visually-hidden"><?=$this->transEsc('page_reload_on_select_hint') ?></span>
      <?php if ($resetLink): ?>
        <a class="reset-filters-btn visible-xs visible-sm" role="button" href="<?=$resetLink?>"><?=$this->transEsc('reset_filters_button')?> (<?=$filterCount?>)</a>
      <?php endif; ?>
    </div>
<?php endif; ?>
<?php $checkboxFilters = $results->getParams()->getCheckboxFacets(); ?>
<?php $checkboxesShown = false; ?>
<?php if (count($checkboxFilters) > 0):
    foreach ($checkboxFilters as $current) {
      if ($resultsTotal > 0 || $current['selected'] || $current['alwaysVisible']) {
        $checkboxesShown = true;
        break;
      }
    }
  ?>
  <?php if ($checkboxesShown): ?>
    <div class="checkbox-filters">
      <fieldset>
        <legend class="visually-hidden"><?=$this->transEsc('checkbox_filter')?></legend>
        <?=$this->context($this)->renderInContext('Recommend/SideFacets/checkbox-filters.phtml', ['checkboxFilters' => $checkboxFilters, 'results' => $results]); ?>
      </fieldset>
    </div>
  <?php endif; ?>
<?php endif; ?>
<?php
  $extraFilters = $this->extraSideFacetFilters ?? [];
  $collapsedFacets = $this->recommend->getCollapsedFacets();
  $filterList = array_merge($results->getParams()->getFilterList(true), $extraFilters);
  $plotFrom = null;
  $daterangeFacetField = null;
  if (is_callable([$options, 'getDateRangeSearchField'])) {
    $daterangeFacetField = $options->getDateRangeSearchField();
  }
  if ($this->fromStreetSearch) {
    if (($key = array_search('geographic_facet', $collapsedFacets)) !== false) {
      unset($collapsedFacets[$key]);
    }
  }
?>
<?=$this->sideFacetExtraControls ?? '' ?>
<?php $sideFacetSet = $this->recommend->getFacetSet(); ?>
<?php if (!empty($sideFacetSet) && $results->getResultTotal() > 0): ?>
  <?php foreach ($sideFacetSet as $title => $cluster): ?>
    <?php
      $allowExclude = $this->recommend->excludeAllowed($title);
      $daterangeFacet = $title == $daterangeFacetField;
      $escTitle = $this->escapeHtmlAttr($title);
      $isCollapsed = in_array($title, $collapsedFacets);
      $dataTarget = 'side-collapse-' . $escTitle;
    ?>
    <div class="list-group facets<?= $daterangeFacet ? ' daterange-facet' : '' ?> facet-group" id="side-panel-<?=$escTitle?>">
      <button class="list-group-item title<?= $isCollapsed ? ' collapsed' : '' ?>" data-bs-toggle="collapse" data-bs-target="#<?=$dataTarget?>" aria-controls="<?=$dataTarget?>" aria-expanded="<?= !$isCollapsed ? 'true' : 'false';?>">
        <span class="facet-title"><?=$this->transEsc($cluster['label'])?></span>
        <?=$this->icon('collapse', 'facet-title-icon') ?>
      </button>
      <div id="facet-title-<?=$dataTarget?>" class="visually-hidden" aria-hidden="true"><?=$this->transEsc($cluster['label'])?></div>
      <div id="<?=$dataTarget?>" aria-labelledby="facet-title-<?=$dataTarget?>" role="group" class="collapse<?= !$isCollapsed ? ' show' : '' ?>" data-facet="<?=$escTitle?>" aria-expanded="<?= !$isCollapsed ? 'true' : 'false';?>">
        <?=
          $this->context($this)->renderInContext(
              'Recommend/SideFacets/facet.phtml',
              [
                  'facet' => $title,
                  'cluster' => $cluster,
                  'collapsedFacets' => $collapsedFacets,
                  'plotImmediately' => false,
              ]
          )?>
      </div>
    </div>
  <?php endforeach; ?>
<?php endif; ?>
<?php if ($resultsTotal > 0): ?>
  </div>
<?php endif; ?>
<?=$this->assetManager()->outputInlineScriptString('registerSideFacetTruncation();');?>
<!-- END of: finna - Recommend/SideFacets.phtml -->
