<div class="library-card-terms">
  Go lasihat girjerádjogoartta kontosat, vurkejuvvo neahttabálvalussii girjerádjogoartta dovddaldat, PIN-koda, sisačáliheaddji namma, šleađgapoastačujuhus ja ruoktogirjerádju.
  Fuolaheaddji galgá sihkkut eret iežas konttus áittardanvuloš mánáid, go sii leat deavdán 15 jagi.
  Lassedieđut persovdnadieđuid gieđahallamis <a href="<?=$this->url('content-page', ['page' => 'privacy'])?>" data-lightbox-ignore target="_blank"><?=$this->transEsc('Privacy')?>-siiddus</a>.
</div>
