<div class="library-card-terms">
  Go lasihat girjerádjokoartta iežat kontui, vurkejuvvo neahttabálvalussii girjerádjokoartta dovddaldat, PIN-koda, sisačáliheaddji namma, šleađgapoastačujuhus ja ruovttugirjerádju.
  Fuolaheaddji ferte sihkkut eret iežat konttus mánáid girjerádjokoarttaid, go sii leat deavdán 15 jagi.
  Lassidiehtu persovdnadieđuid gieđahallamis <a href="<?=$this->url('content-page', ['page' => 'privacy'])?>" data-lightbox-ignore target="_blank"><?=$this->transEsc('Privacy')?>-siiddus</a>.
</div>
