<?php $__attributes = $this->htmlAttributes($attributes ?? []); ?>
<div<?= $__attributes->add('class', 'finna-multi-level-nav') ?>>
  <?php
    $__tabsNavAttributes = $this->htmlAttributes($tabsNavAttributes ?? []);
    if (!isset($__tabsNavAttributes['class'])) {
      $__tabsNavAttributes['class'] = 'hidden-xs';
    }
    if ($__attributes->hasValue('class', 'finna-multi-level-nav-lg')) {
      $__tabsNavAttributes->add('class', 'finna-tabs-nav-lg');
    }
  ?>
  <?= $this->render('components/organisms/navigation/finna-tabs-nav', [
      'ariaCurrent' => 'page',
      'ariaLabel' => $ariaLabel ?? null,
      'attributes' => $__tabsNavAttributes,
      'items' => $items ?? [],
    ]); ?>
  <?php
    $__navbarAttributes = $this->htmlAttributes($navbarAttributes ?? []);
    if (!isset($__navbarAttributes['class'])) {
      $__navbarAttributes['class'] = 'visible-xs';
    }
    if ($__attributes->hasValue('class', 'finna-multi-level-nav-content')) {
      $__navbarAttributes->add('class', 'finna-navbar-content');
    }
  ?>
  <?= $this->render('components/organisms/navigation/finna-navbar', [
      'ariaLabel' => $ariaLabel ?? null,
      'attributes' => $__navbarAttributes,
      'brandContent' => $brandContent ?? null,
      'brandLink' => $brandLink ?? null,
      'brandSrOnly' => $brandSrOnly ?? null,
      'collapseContent' => $this->render('components/molecules/navigation/finna-nav', [
          'attributes' => ['class' => ['finna-nav-navbar']],
          'items' => $items ?? [],
        ]),
      'collapseId' => $collapseId ?? null,
      'toggleBtnIconClass' => $toggleBtnIconClass ?? 'finna-navbar-icon-caret',
      'toggleBtnLabel' => $toggleBtnLabel ?? null,
      'toggleBtnSrOnly' => $toggleBtnSrOnly ?? null,
    ]); ?>
</div>
