<!-- START of: finna - Helpers/location-service-modal.phtml -->
<h2><?=$this->transEsc('Location Service') ?></h2>
<div class="location-service">
  <div class="link">
    <a href="<?=$this->url?>" target="location-service" class=""><?=$this->icon('new-window') ?> <?=$this->translate('Open in a new window')?></a>
  </div>
  <iframe class="frame" src="<?=$this->url?>"></iframe>
</div>
<!-- END of: finna - Helpers/location-service-modal.phtml -->
