<!-- START of: finna - myresearch/historicloans.phtml -->
<?php
    // Set up page title:
    $this->headTitle($this->translate('Loan History'));

    // Set up breadcrumbs:
    $this->layout()->breadcrumbs = '<li><a href="' . $this->url('myresearch-home') . '">' . $this->transEsc('Your Account') . '</a></li> <li class="active">' . $this->transEsc('Loan History') . '</li>';

    $recordCount = $this->paginator ? $this->paginator->getTotalItemCount() : count($this->transactions ?? []);
    $catalog = $this->ils();
    $user = $this->auth()->isLoggedIn();
    $patron = $user ? $this->auth()->getILSPatron() : false;
?>

<!-- Leftside navigationbar -->
<?= $this->context($this)->renderInContext("myresearch/menu.phtml", ['active' => 'historicLoans']); ?>

<div class="<?=$this->layoutClass('mainbody-myresearch')?>">
  <div class="my-research-content">
    <div class="myresearch-grid-list">
      <?php if (!$this->translationEmpty('loan_history_instructions_html')): ?><p class="no-content-message"><?=$this->translate('loan_history_instructions_html')?></p><?php endif; ?>
      <?=$this->flashmessages()?>
      <div class="useraccount-row">
        <?=$this->context($this)->renderInContext('librarycards/selectcard.phtml', ['user' => $user, 'label' => 'Library Card'])?>
      </div>
      <div class="useraccount-header">
        <h2><?=$this->transEsc('Loan History')?> (<?=$recordCount;?>)</h2>
      </div>
      <?php if (isset($this->noSupport)): ?>
        <?php if ($user->getLibraryCards()->count() > 1): ?>
          <div class="support-notice">
            <p><?=$this->transEsc("no_ils_support_description") ?></p>
          </div>
        <?php endif; ?>
      <?php else: ?>
        <?php if ($template = $this->content()->findTemplateForLng('content/Additions/historic-loans-pre-list')): ?>
          <div class="historic-loans-pre-list"><?=$this->render($template)?></div>
        <?php endif; ?>
        <?php if (!empty($this->transactions)): ?>
          <?php if ($paginator): ?>
            <div class="pagination-container">
              <?=$paginator ? $this->paginationControl($paginator, 'Sliding', 'Helpers/pagination-simple.phtml', ['params' => $params]) : ''?>
            </div>
          <?php endif; ?>
          <div class="toolbar-button-sort">
            <div class="sort-col visible-xs">
              <?php if ($this->sortList): ?>
                <?=$this->context($this)->renderInContext('myresearch/controls/sort.phtml', ['sortList' => $this->sortList]); ?>
              <?php endif; ?>
            </div>
          </div>
          
          <?php if ($purgeAllAllowed || $purgeSelectedAllowed): ?>
            <div class="toolbar-sticky-container">
            <form name="purge_history" method="post" action="<?=$this->url('checkouts-purgehistory')?>" id="purge_history" data-disable-on-submit>
            <input type="hidden" id="submitType" name="purgeSelected" value="1">
            <input type="hidden" name="csrf" value="<?=$this->escapeHtmlAttr($this->auth()->getManager()->getCsrfHash())?>">
            <div class="toolbar-sticky">
          <?php endif; ?>
            <table class="myresearch-table history-table" role="presentation" aria-label="<?=$this->transEscAttr('Actions');?>">
              <tr class="toolbar">
                <?php if ($purgeSelectedAllowed): ?>
                  <td class="text-left checkbox-col">
                    <div class="checkboxFilter mylist-select-all">
                      <div class="checkbox">
                        <label>
                          <input type="checkbox" name="selectAll" class="checkbox-select-all">
                          <span class="selected"></span>
                        </label>
                      </div>
                    </div>
                  </td>
                <?php endif; ?>
                <td>
                  <div class="renew-button-col">
                    <?php if ($purgeSelectedAllowed): ?>
                      <div class="btn-group">
                        <input type="submit" id="purgeSelected" name="purgeSelected" value="<?=$this->transEscAttr('loan_history_purge_selected')?>" class="btn btn-primary dropdown-toggle" data-toggle="dropdown" data-lightbox-ignore>
                        <ul class="dropdown-menu">
                          <li class="disabled"><span class="prompt-text"><?=$this->transEsc('loan_history_confirm_purge_selected')?></span></li>
                          <li><a href="#" id="confirm_purge_selected_yes"><?=$this->transEsc('confirm_dialog_yes')?></a></li>
                          <li><a href="#" class="confirm_purge_no"><?=$this->transEsc('confirm_dialog_no')?></a></li>
                        </ul>
                      </div>
                    <?php endif; ?>
                    <?php if ($purgeAllAllowed): ?>
                      <div class="btn-group">
                        <input type="submit" id="purgeAll" name="purgeAll" value="<?=$this->transEscAttr('loan_history_purge_all')?>" class="btn btn-primary dropdown-toggle" data-toggle="dropdown" data-lightbox-ignore>
                        <ul class="dropdown-menu">
                          <li class="disabled"><span class="prompt-text"><?=$this->transEsc('loan_history_confirm_purge_all')?></span></li>
                          <li><a href="#" id="confirm_purge_all_yes"><?=$this->transEsc('confirm_dialog_yes')?></a></li>
                          <li><a href="#" class="confirm_purge_no"><?=$this->transEsc('confirm_dialog_no')?></a></li>
                        </ul>
                      </div>
                    <?php endif; ?>
                    <div class="sort-col hidden-xs">
                      <?php if ($this->sortList): ?>
                        <?=$this->context($this)->renderInContext('myresearch/controls/sort.phtml', ['sortList' => $this->sortList]); ?>
                      <?php endif; ?>
                    </div>
                  </div>
                </td>
              </tr>
            </table>
          </div>

          <table class="myresearch-table" aria-label="<?=$this->transEscAttr('Loan History')?>" tabindex="0">
            <tr class="sr-only myresearch-row" aria-hidden="true">
              <?php if ($purgeSelectedAllowed): ?>
                <th id="label-select-column"><?=$this->transEsc('Select');?></th>
              <?php endif; ?>
              <th class="hidden-xs"></th>
              <th id="label-title-column"><?=$this->transEsc('Loan Details');?></th>
              <th id="label-status-column"><?=$this->transEsc('Additional data');?></th>
            </tr>
            <?php $i = 0;
            foreach ($this->transactions as $resource): ?>
              <?php $ilsDetails = $resource->getExtraDetail('ils_details'); ?>
              <tr class="myresearch-row">
                <?php if ($this->purgeSelectedAllowed): ?>
                  <td class="text-left checkbox-col" headers="label-select-column" aria-labelledby="label-select-column">
                    <div class="checkboxFilter">
                      <div class="checkbox">
                        <?php if (isset($ilsDetails['row_id'])): ?>
                          <?php $safeId = preg_replace('/[^a-zA-Z0-9]/', '', $ilsDetails['row_id']); ?>
                          <label>
                            <input class="checkbox-select-item" type="checkbox" name="purgeSelectedIDs[]" value="<?=$this->escapeHtmlAttr($ilsDetails['row_id'])?>" id="checkbox_<?=$safeId?>">
                          </label>
                        <?php else: ?>
                          <label> </label>
                        <?php endif; ?>
                      </div>
                    </div>
                  </td>
                <?php endif; ?>
                <td class="text-left hidden-xs" aria-hidden="true">
                  <div class="cover-image">
                    <?php if ($summThumb = $this->record($resource)->getThumbnail()): ?>
                      <img src="<?=$this->escapeHtmlAttr($summThumb)?>" class="recordcover" alt="<?=$this->transEscAttr('Cover Image')?>">
                    <?php else: ?>
                      <img src="<?=$this->url('cover-unavailable')?>" class="recordcover" alt="<?=$this->transEscAttr('No Cover Image')?>">
                    <?php endif; ?>
                  </div>
                </td>
                <td headers="label-title-column" aria-labelledby="label-title-column">
                  <?php
                    // If this is a non-missing Solr record, we should display a link:
                    if (is_a($resource, 'VuFind\\RecordDriver\\SolrDefault') && !is_a($resource, 'VuFind\\RecordDriver\\Missing')) {
                      // Use ILS title if available since it may contain e.g. issue number
                      if (!empty($ilsDetails['title'])) {
                        $title = trim($ilsDetails['title'], '/: ');
                      } else {
                        $title = $resource->getTitle();
                        $title = empty($title) ? $this->transEsc('Title not available') : $this->escapeHtml($title);
                      }
                      echo '<a href="' . $this->escapeHtmlAttr($this->recordLinker()->getUrl($resource)) .
                        '" class="record-title">' . $title . '</a>';
                    } elseif (isset($ilsDetails['title']) && !empty($ilsDetails['title'])) {
                      // If the record is not available in Solr, perhaps the ILS driver sent us a title we can show...
                      echo '<span class="record-title">' . $this->escapeHtml($ilsDetails['title']) . '</span>';
                    } else {
                      // Last resort -- indicate that no title could be found.
                      echo '<span class="record-title">' . $this->transEsc('Title not available') . '</span>';
                    }
                  ?>
                  <div class="record-core-metadata">
                    <?php $formats = $resource->getFormats();
                    if (count($formats) > 0): ?>
                      <?=$this->record($resource)->getFormatList() ?>
                      <br>
                    <?php endif; ?>
                    <?=$this->partial('myresearch/helpers/record-author.phtml', ['record' => $resource]);?>
                    <?php if (!empty($ilsDetails['volume'])): ?>
                      <strong><?=$this->transEsc('Issue')?>:</strong> <?=$this->escapeHtml($ilsDetails['volume'])?>
                      <br>
                    <?php endif; ?>

                    <?php if (!empty($ilsDetails['publication_year'])): ?>
                      <strong><?=$this->transEsc('Year of Publication')?>:</strong> <?=$this->escapeHtml($ilsDetails['publication_year'])?>
                      <br>
                    <?php endif; ?>
                  </div>
                </td>
                <td class="checkedout-status-information" headers="label-status-column" aria-labelledby="label-status-column">
                  <?php if (!empty($ilsDetails['institution_name']) && (empty($ilsDetails['borrowingLocation']) || $ilsDetails['institution_name'] != $ilsDetails['borrowingLocation'])): ?>
                    <strong><?=$this->transEscWithPrefix('location_', $ilsDetails['institution_name'])?></strong>
                    <br>
                  <?php endif; ?>

                  <?php if (!empty($ilsDetails['borrowingLocation'])): ?>
                    <strong><?=$this->transEsc('Borrowing Location')?>:</strong> <?=$this->transEscWithPrefix('location_', $ilsDetails['borrowingLocation'])?>
                    <br>
                  <?php endif; ?>

                  <?php if (!empty($ilsDetails['checkoutDate'])): ?>
                    <strong><?=$this->transEsc('Checkout Date')?>:</strong> <?=$this->escapeHtml($ilsDetails['checkoutDate'])?>
                    <br>
                  <?php endif; ?>
                  <?php if (!empty($ilsDetails['returnDate'])): ?>
                    <strong><?=$this->transEsc('Return Date')?>:</strong> <?=$this->escapeHtml($ilsDetails['returnDate'])?>
                    <br>
                  <?php endif; ?>
                  <?php if (!empty($ilsDetails['dueDate'])): ?>
                    <strong><?=$this->transEsc('Due Date')?>:</strong> <?=$this->escapeHtml($ilsDetails['dueDate'])?><?php if (isset($ilsDetails['dueTime'])): ?> <span class="due-time"><?=$this->escapeHtml($ilsDetails['dueTime'])?></span><?php endif; ?>
                  <?php endif; ?>
                </td>
              </tr>
            <?php endforeach; ?>
          </table>

          <?php if ($purgeAllAllowed || $purgeSelectedAllowed): ?>
              </div>
            </form>
            </div>
          <?php endif; ?>

          <?=$this->paginator ? $this->paginationControl($this->paginator, 'Sliding', 'Helpers/pagination.phtml', ['params' => $this->params]) : ''?>
          <?php if ($template = $this->content()->findTemplateForLng("content/Additions/checkout-history-post-list")): ?>
            <div class="checkout-history-post-list"><?=$this->render($template)?></div>
          <?php endif; ?>
        <?php else: ?>
          <div class="useraccount-header">
            <h3><?=$this->transEsc('You do not have any items in the checkout history')?>.</h3>
          </div>
        <?php endif; ?>
      <?php endif; ?>
    </div>
  </div>
</div>
<!-- END of: finna - myresearch/historicloans.phtml -->
