<!-- START of: finna - Helpers/OnlinePayment/Paytrail.phtml -->
<?php // NOTE: This template exists for back-compatibility only ?>
<div class="online-payment-area">
  <form id="paytrail-form" class="online-payment-form" action="<?=$this->url('myresearch-fines')?>" method="post" data-lightbox data-clear-account-cache="fines">
    <input name="transactionId" type="hidden" value="<?=$this->escapeHtmlAttr($this->transactionId)?>">
    <input type="submit" name="pay" class="btn btn-primary btn-lg" value="<?=$this->transEscAttr('online_payment_go_to_pay', ['%%amount%%' => $this->safeMoneyFormat($this->amount / 100.00)])?>">
  </form>
</div>
<img src="<?=$this->imageLink('online-payment-paytrail.png')?>" id="paytrail-logo" alt="Paytrail">
<!-- END of: finna - Helpers/OnlinePayment/Paytrail.phtml -->
