<?php
  $cart = $this->cart();
  $recordView = $this->layout()->templateDir;
  $inToolbar = $this->inToolBar ?? false;
?>
<?php if ($cart->isActive()): ?>
  <?php $cartId = $this->source . '|' . $this->id; ?>
  <div class="btn-bookbag-toggle" data-cart-id="<?=$this->escapeHtmlAttr($this->id)?>" data-cart-source="<?=$this->escapeHtmlAttr($this->source)?>">
    <a class="cart-add<?php if ($inToolbar): ?> btn-record-toolbar<?php endif; ?> hidden<?php if (!$cart->contains($cartId)): ?> correct<?php endif ?>" role="button" href="#" aria-label="<?=$this->transEsc('Add to Book Bag') ?>">
      <?=$this->icon('cart-add') ?>
      <?php if ($inToolbar): ?>
        <?=$this->transEsc('Add to Book Bag')?>
      <?php else: ?>
        <span class="hidden-sm hidden-md hidden-lg"><?=$this->transEsc('Add to Book Bag') ?></span>
      <?php endif; ?>
    </a>
    <a class="cart-remove<?php if ($inToolbar): ?> btn-record-toolbar<?php endif; ?> hidden<?php if ($cart->contains($cartId)): ?> correct<?php endif ?>" role="button" href="#" aria-label="<?=$this->transEsc('Remove from Book Bag') ?>">
      <?=$this->icon('cart-remove') ?>
      <?php if ($inToolbar): ?>
        <?=$this->transEsc('Remove from Book Bag')?>
      <?php else: ?>
        <span class="hidden-sm hidden-md hidden-lg"><?=$this->transEsc('Remove from Book Bag') ?></span>
      <?php endif; ?>
    </a>
  </div>
<?php endif; ?>
