<!-- START of: finna - record/view.phtml -->
<?php
  // Set up standard record scripts:
  $this->assetManager()->appendScriptLink('record.js');
  $this->assetManager()->appendScriptLink('check_save_statuses.js');
  $this->assetManager()->appendScriptLink('finna-comments.js');
  // Add any extra scripts the tabs require:
  foreach ($this->tabsExtraScripts as $script) {
    $this->assetManager()->appendScriptLink($script);
  }

  // Add RDF header link if applicable:
  if ($this->export()->recordSupportsFormat($this->driver, 'RDF')) {
    $this->headLink()->appendAlternate($this->recordLinker()->getActionUrl($this->driver, 'RDF'), 'application/rdf+xml', 'RDF Representation');
  }

  // Set up breadcrumbs:
  $this->breadcrumbs()->reset();
  if ($url = $this->searchMemory()->getLastSearchUrl()) {
    $this->breadcrumbs()->add($this->translate('Search'), $url);
  }
  $this->breadcrumbs()->add(...$this->recordLinker()->getBreadcrumbParams($this->driver), active: true);

  $this->headMeta()->appendName('format-detection', 'telephone=no');

  // Set page title.
  $title = $this->truncate($this->driver->getTitle(), 180);
  $this->layout()->title = $title;

  $headText = $title;
  $organisationName = $this->organisationDisplayName($this->driver);
  if (!empty($organisationName)) {
      $headText .= " | $organisationName";
  }
  $this->headTitle($headText);

  $this->jsTranslations()->addStrings(
      [
          'map_zoom_in' => 'map_zoom_in',
          'map_zoom_out' => 'map_zoom_out',
      ]
  );

  if ($lastUrl = $this->searchMemory()->getLastSearchUrl() && $this->searchMemory()->getLastSearchClassId() === $this->searchClassId) {
      $params = $this->searchMemory()->getLastSearchParams($this->searchClassId);
      $filterList = $params->getFilterList(true);

      if (!empty($params->getFilterList(false))) {
          $checkboxFilters = $params->getCheckboxFacets();
          $lastSort = $this->searchMemory()->getLastSort($this->searchClassId);
          $options = $this->searchOptions($this->searchClassId);
          $defaultSortApplied = !isset($params) || $lastSort == $options->getDefaultSortByHandler($params->getSearchHandler());
          // Set up filters
          $filterSettingsArray = [
            'filterList' => $filterList,
            'checkboxFilters' => $checkboxFilters,
            'defaultSortApplied' => $params->hasDefaultsApplied(),
            'options' => $options,
            'params' => $params,
          ];
          $this->layout()->finnaFilters = $this->context($this)->renderInContext(
              'search/filters.phtml',
              $filterSettingsArray,
          );
          $filterSettingsArray['dropdown'] = false;
          $this->layout()->finnaMobileFilters = $this->context($this)->renderInContext(
              'search/filters.phtml',
              $filterSettingsArray,
          );
      }
  }

  $params = $this->searchMemory()->getLastSearchParams($this->searchClassId);
  $recordFormat = $this->driver->tryMethod('getRecordFormat');
  $fullWidthLayout = $this->record($this->driver)->hasFullWidthLayout();
  $largeImageLayout = $this->record($this->driver)->hasLargeImageLayout();

  if ($oldRecordId = $this->driver->getExtraDetail('redirectedFromId')) {
      echo $this->assetManager()->outputInlineScriptString(
          'finna.record.handleRedirect(' . json_encode($oldRecordId) . ', ' . json_encode($this->driver->getUniqueID()) . ');'
      );
  }

  // Store scrollData for searchbox:
  $this->layout()->scrollData = $this->scrollData;

  // Set record selection data if a Bazaar session is active.
  $this->bazaarSession()->setSelectionData(
      $this->driver->getUniqueId(),
      $this->driver->getTitle()
  );
?>
<?= $this->record($this->driver)->getBanner() ?>
<?php $recordAttributes = $this->htmlAttributes([
    'class' => [
      'record',
      'source' . $this->driver->getSourceIdentifier(),
      $recordFormat ? 'record-format-' . $recordFormat : '',
      $fullWidthLayout ? 'full-width-layout' : '',
      $largeImageLayout ? 'large-image-layout' : '',
    ],
  ]); ?>
<div<?= $recordAttributes ?>>
  <div>
      <?=$this->record($this->driver)->getToolbar()?>
  </div>
  <?php if ($this->config()->inlineVideoEnabled()): ?>
    <?php
      $videoUrls = [];
      foreach ($this->record($this->driver)->getLinkDetails() as $url) {
        if (!empty($url['videoSources']) || !empty($url['embed']) && $url['embed'] == 'video' || $this->recordLinker()->getEmbeddedVideo($url['url']) == 'data-embed-iframe') {
          $videoUrls[] = $url;
        }
      }
    ?>
    <?php if (!empty($videoUrls)): ?>
      <div class="inline-video-container">
        <div class="inline-video" id="inline-video"></div>
        <?=$this->record($this->driver)->renderTemplate('record-video-player.phtml', ['videoUrls' => $videoUrls, 'inlineVideo' => true]);?>
      </div>
    <?php endif; ?>
  <?php endif; ?>
  <?php if ($iiifManifests = $this->driver->tryMethod('getIiifManifests')):
      echo $this->record($this->driver)->renderTemplate(
          'record-iiif-viewer.phtml',
          ['manifests' => $iiifManifests]
      );
  endif; ?>
  <div class="record-main <?= (!$fullWidthLayout && !$largeImageLayout) ? 'mainbody left' : ''?>">
    <input type="hidden" value="<?=$this->escapeHtmlAttr($this->driver->getUniqueId())?>" class="hiddenId">
    <input type="hidden" value="<?=$this->escapeHtmlAttr($this->driver->getSourceIdentifier()) ?>" class="hiddenSource">
    <?=$this->flashmessages()?>
    <?=$this->record($this->driver)->getMetaTags();?>
    <?=$this->record($this->driver)->getCoreMetadata()?>

    <?=$this->driver->supportsCoinsOpenURL() ? '<span class="Z3988" aria-hidden="true" title="' . $this->escapeHtmlAttr($this->driver->getCoinsOpenURL()) . '"></span>' : ''?>

    <div class="clearfix hidden-lg hidden-md"></div>
    <div class="record-tabs">
      <?php if ($this->tabs): ?>
        <a id="tabnav"><h2 class="visually-hidden"><?=$this->transEsc('Additional Information')?></h2></a>
        <?=$this->component(
          'tabs',
          [
            'tabs' => $this->recordTabs()->getTabs($this->driver, $this->tabs, $this->activeTab),
            'activeTab' => $this->activeTab,
            'tabNavClasses' => ['nav-tabs recordTabs'],
            'scrollable' => true,
          ]
        )?>
      <?php endif; ?>
    </div>
  </div>

  <?php if (!$fullWidthLayout && !$largeImageLayout):?>
    <?php // This sidebar is used for larger screens when not in full width or large image layout ?>
    <div class="sidebar right smaller-image-sidebar hidden-xs hidden-sm">
      <?= $this->render('record/sidebar-contents.phtml'); ?>
    </div>
  <?php endif; ?>
</div>

<?php if (!$fullWidthLayout): ?>
  <?php // This sidebar is used for smaller screens and always in large image layout, but never in full width layout ?>
  <div class="sidebar left large-image-sidebar <?php if (!$largeImageLayout): ?> visible-xs visible-sm<?php endif; ?>">
    <?= $this->render('record/sidebar-contents.phtml'); ?>
  </div>
<?php endif; ?>
<?php if ($this->config()->getSimilarRecordsCarouselLocation() === 'after_tabs' && $this->driver->getSourceIdentifier() === 'Solr'): ?>
  <div class="similar-bottom container">
    <?=$this->render('RecordTab/channels.phtml', ['tab' => $this->record($this->driver)->getChannelsTab()])?>
  </div>
<?php endif; ?>
<!-- END of: finna - record/view.phtml -->
