<!-- START of: finna - RecordDriver/SolrForward/core-fields.phtml -->
<?php
  $formatter = $this->recordDataFormatter($this->driver);
  $coreFields = $formatter->getDefaults();
  $coreFields['Distribution']['context']['title'] = 'Distributor';
  $coreFields['Description FWD']['context']['title'] = '';
  $coreFieldGroups = $formatter->getGroupedData($this->driver, $formatter->getGroupedFields([
    ['lines' => ['Genre', 'Age Limit', 'Actors', 'Secondary Authors']],
    ['label' => 'Production Information',
      'lines' => ['Production', 'Production Costs', 'Funding', 'Published', 'Original Work'],
      'options' => ['context' => ['class' => 'field-group-production']]],
    ['label' => 'Distribution Information',
      'lines' => ['Distribution', 'Premiere Night', 'Premiere Theaters',
        'Film Copies', 'Number of Viewers', 'Other Screenings', 'Broadcasting Dates', 'Awards',
        'Film Festivals', 'Foreign Distribution',
      ],
      'options' => ['context' => ['class' => 'field-group-distribution']]],
    ['label' => 'Filming Locations',
      'lines' => ['Exterior Images', 'Interior Images', 'Studios',
        'Filming Location Notes'],
      'options' => ['context' => ['class' => 'field-group-filming-locations']]],
    ['lines' => ['Filming Date']],
    ['label' => 'Description FWD',
      'lines' => ['Description FWD', 'Subjects'],
      'options' => ['context' => ['class' => 'field-group-content-description']]],
    ['lines' => ['Press Reviews', 'Item Description FWD', 'Music', 'Movie Thanks', 'Archive Films', 'Inspection Details']],
    ['label' => 'Technical Data',
      'lines' => ['Color', 'Sound', 'Aspect Ratio', 'Playing Time'],
      'options' => ['context' => ['class' => 'field-group-rating-technical-data']]],
    ['lines' => ['Access']],
  ], $coreFields));
?>
<?php if (!empty($coreFieldGroups)): ?>
  <table class="table table-finna-record record-details record-details-more record-field-groups" role="presentation">
    <?=$this->record($this->driver)->renderTemplate('core-field-groups.phtml', ['data' => $coreFieldGroups]);?>
  </table>
<?php endif; ?>
<button class="btn show-details-button hidden"><?=$this->transEsc('show_more_details');?> <?=$this->icon('show-more') ?></button>
<button class="btn hide-details-button hidden"><?=$this->transEsc('show_less_details');?> <?=$this->icon('show-less') ?></button>
<!-- END of: finna - RecordDriver/SolrForward/core-fields.phtml -->
