<!-- START of: finna - organisationinfo/home-standalone.phtml -->
<div class="organisation-info-page loading organisation-page-information-wrapper last-section">
  <div class="loader">
    <?=$this->icon('spinner') ?>
  </div>

  <?=$this->render('organisationinfo/map-information.phtml')?>
  <div class="source-desc">
    <p class="text-muted"><?= $this->transEsc('organisation_data_source_desc') ?></p>
  </div>
</div>
<!-- END of: finna - organisationinfo/home-standalone.phtml -->
