<!-- START of: finna - organisationinfo/home-standalone.phtml -->
<div class="organisation-info-page loading organisation-page-information-wrapper last-section">
  <div class="loader">
    <i class="fa fa-spinner fa-spin" style="text-align: center;"></i>
  </div>

  <?=$this->render('organisationinfo/map-information.phtml')?>
  <div class="source_desc">
    <p class="text-muted"><?= $this->transEsc('organisation_data_source_desc') ?></p>
  </div>
</div>
<!-- END of: finna - organisationinfo/home-standalone.phtml -->
