<?php if (!($data = $this->results)) {
  return;
} ?>
<div class="related-records">
  <h1><?=$this->transEsc('Related Materials')?></h1>
  <ul class="list-group">
    <?php foreach ($data as $type => $records): ?>
      <li class="list-group-item">
        <p><?=$this->transEsc("RelatedRecordType::$type")?></p>
        <ul class="list-group list-sub-group <?=$this->escapeHtmlAttr($type)?>">
        <?php foreach ($records as $record): ?>
        <?php $formats = $record->getFormats(); ?>
        <?php $parentSource = $record->getSourceIdentifier(); ?>
          <li>
            <a href="<?=$this->escapeHtmlAttr($this->recordLinker()->getUrl($record))?>">
              <?=$this->escapeHtml($record->getTitle())?>
            </a>
            <br>
            <?=$this->record($record)->getFormatList();?>
            <?php $topTitles = $record->getHierarchyTopTitle();
            if ($topTitles): ?>
              <?php
                $topTitle = $topTitles[0];
                $topIds = $record->getHierarchyTopId();
                $topId = $topIds[0] ?? '';
              ?>
              <?php if ($record->getUniqueId() !== $topId): ?>
                <br>
                <a href="<?=$this->escapeHtmlAttr($this->recordLinker()->getUrl("$parentSource|$topId"))?>">
                  <?=$this->escapeHtml($this->truncate($topTitle, 180)) ?>
                </a>
              <?php endif; ?>
            <?php endif?>
          </li>
        <?php endforeach; ?>
        </ul>
      </li>
    <?php endforeach; ?>
  </ul>
</div>
