<!-- START of: finna - list/list-notes.phtml -->
<?php
  if (!in_array($this->layout()->templateDir, ['content', 'list', 'search']) || $this->layout()->templateName === 'results' || !is_callable([$this->results, 'getListObject'])) {
    return;
  }
  $notes = $this->driver->getListNotes($this->results->getListObject()->id);
  if (empty($notes)) {
    return;
  }
?>
<?php
  $note = implode('', $notes);
  $note = $this->markdown()->toHtml($note);
  $grid = $this->params->getView() === 'grid';
  $noteDesc = $this->transEsc('Note');
?>
<div class="<?= $grid ? 'note-overlay note-hide' : '' ?>">
  <div class="notes">
    <br/>
    <div class="note-rows">
      <?=$note;?>
    </div>
  </div>
</div>
<?php if ($grid): ?>
  <button class="note-button" aria-hidden="true" title="<?=$noteDesc?>"><i class="fa fa-file-text-o"></i><?=$noteDesc?><span class="caret"></span></button>
<?php endif; ?>
<!-- END of: finna - list/list-notes.phtml -->
