<!-- START of: finna - list/list-notes.phtml -->
<?php
  if (!in_array($this->layout()->templateDir, ['content', 'list', 'search']) || $this->layout()->templateName === 'results' || !is_callable([$this->results, 'getListObject'])) {
    return;
  }
  $notes = $this->driver->getListNotes($this->results->getListObject()->id);
  if (empty($notes)) {
    return;
  }
?>
<?php
  $note = implode('', $notes);
  $note = $this->markdown()->toHtml($note);
  $view = $this->params->getView();

  $noteDesc = $this->transEsc('Note');
?>
<?php if ($view === 'condensed'): ?>
  <button class="note-button condensed" aria-hidden="true" title="<?=$noteDesc?>"><i class="fa fa-file-text-o"></i><?=$noteDesc?><span class="caret"></span></button>
<?php endif; ?>
<div class="<?= in_array($view, ['grid', 'condensed']) ? "note-overlay-$view note-hide" : '' ?>">
  <div class="notes">
    <?php if ($view === 'grid'): ?>
      <br/>
    <?php endif; ?>
    <div class="note-rows">
      <?=$note;?>
    </div>
  </div>
</div>
<?php if ($view === 'grid'): ?>
  <button class="note-button" aria-hidden="true" title="<?=$noteDesc?>"><i class="fa fa-file-text-o"></i><?=$noteDesc?><span class="caret"></span></button>
<?php endif; ?>
<!-- END of: finna - list/list-notes.phtml -->
