<!-- START of: finna - list/list-notes.phtml -->
<?php
  if (!in_array($this->layout()->templateDir, ['content', 'list', 'search', 'record']) || $this->layout()->templateName === 'results') {
    return;
  }
  if (is_callable([$this->results, 'getListObject'])) {
      $notes = $this->record($this->driver)->getListNotes($this->results->getListObject());
  } elseif (isset($this->curatedRecord) && !empty($notes = $this->curatedRecord->getNotes())) {
      $notes = [$notes];
  }
  if (empty($notes)) {
    return;
  }
?>
<?php
  $note = implode('', $notes);
  $note = $this->markdown()->toHtml($note);
  $view = $this->params->getView();

  $noteTitleEsc = $this->escapeHtml($this->listNoteTitle ?? $this->translate('Note'));
?>
<?php if ($view === 'condensed'): ?>
  <button class="note-button condensed" aria-hidden="true" title="<?=$noteTitleEsc?>"><?=$this->icon('list-note') ?><?=$noteTitleEsc?><span class="caret"></span></button>
<?php endif; ?>
<div class="<?= in_array($view, ['grid', 'condensed']) ? "note-overlay-$view note-hide" : 'note-overlay-list' ?>">
  <div class="notes">
    <?php if ($view === 'grid'): ?>
      <br>
    <?php endif; ?>
    <div class="note-rows">
      <?php if ($view === 'list' || $view === 'compact'): ?>
        <?=$this->icon('list-note') ?><span><?=$noteTitleEsc?>:</span>
      <?php endif; ?>
      <?=$note;?>
    </div>
  </div>
</div>
<?php if ($view === 'grid'): ?>
  <button class="note-button" aria-hidden="true" title="<?=$noteTitleEsc?>"><?=$this->icon('list-note') ?><?=$noteTitleEsc?><span class="caret"></span></button>
<?php endif; ?>
<!-- END of: finna - list/list-notes.phtml -->
